// Implementation of the project writer and the document serialiser.
#include "builder/write_project.hh"

#include <cmath>
#include <functional>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>

namespace g4gpu::builder {

namespace {

namespace fs = std::filesystem;

/// Everything a solid needs emitted before it can be referenced: a boolean's operands come
/// first, and the world comes first of all. Returns indices in emission order.
///
/// Booleans reference their operands by variable name, so a topological order is not a
/// nicety - emitting a subtraction before its operand produces code that does not compile.
std::vector<int> EmissionOrder(const Model& m) {
  std::vector<int> order;
  std::vector<char> done(m.solids.size(), 0);
  std::vector<char> visiting(m.solids.size(), 0);

  std::function<void(int)> visit = [&](int i) {
    if (i < 0 || i >= static_cast<int>(m.solids.size())) { return; }
    if (done[i] != 0 || visiting[i] != 0) { return; }
    visiting[i] = 1;
    visit(m.solids[i].operand_a);
    visit(m.solids[i].operand_b);
    visiting[i] = 0;
    done[i] = 1;
    order.push_back(i);
  };
  for (std::size_t i = 0; i < m.solids.size(); ++i) { visit(static_cast<int>(i)); }
  return order;
}

/// True if this solid is only used as a boolean operand, and so should not itself be placed.
bool IsOperandOnly(const Model& m, int i) {
  for (const Solid& s : m.solids) {
    if (s.operand_a == i || s.operand_b == i) { return true; }
  }
  return false;
}

void WriteDetectorHeader(std::ofstream& f, const Model& m) {
  f << "/// \\file DetectorConstruction.hh\n"
    << "/// \\brief Geometry for " << m.name << ", generated by the g4gpu model builder.\n"
    << "\n#ifndef DetectorConstruction_h\n#define DetectorConstruction_h 1\n\n"
    << "#include \"G4VUserDetectorConstruction.hh\"\n"
    << "#include \"globals.hh\"\n\n"
    << "class G4LogicalVolume;\n\n"
    << "/// Built by the model builder. Edit freely: this is ordinary Geant4-shaped code and\n"
    << "/// nothing here needs the builder to compile or run.\n"
    << "class DetectorConstruction : public G4VUserDetectorConstruction {\n"
    << " public:\n"
    << "  DetectorConstruction() = default;\n"
    << "  ~DetectorConstruction() override = default;\n\n";
  f << "  G4VPhysicalVolume* Construct() override;\n"
    << "  void ConstructSDandField() override;\n\n";
  // The first scored volume, for SteppingAction's filter. B1 has exactly this accessor and
  // its SteppingAction is written against it, so a generated project's stepping action can be
  // the same code - which is the point of generating the file at all.
  f << "  /// The first volume that feeds a scorer, or null if the model has no scorer.\n"
    << "  ///\n"
    << "  /// SteppingAction uses it to ignore steps outside the region of interest. Change it\n"
    << "  /// to any logical volume you like; nothing else depends on which one it is.\n";
  if (m.scorers.empty()) {
    f << "  G4LogicalVolume* GetScoringVolume() const { return nullptr; }\n\n";
  } else {
    f << "  G4LogicalVolume* GetScoringVolume() const {\n"
      << "    return fScored0.empty() ? nullptr : fScored0.front();\n"
      << "  }\n\n";
  }
  for (const Scorer& sc : m.scorers) {
    f << "  /// Volumes feeding the \"" << sc.name << "\" scorer.\n";
  }
  f << " private:\n";
  for (std::size_t i = 0; i < m.scorers.size(); ++i) {
    f << "  std::vector<G4LogicalVolume*> fScored" << i << ";\n";
  }
  f << "};\n\n#endif\n";
}

void WriteMaterials(std::ofstream& f, const Model& m) {
  f << "  // ---------------------------------------------------------------- materials\n";
  bool needs_nist = false;
  for (const Material& mm : m.materials) {
    if (!mm.nist_name.empty()) { needs_nist = true; }
  }
  if (needs_nist) { f << "  auto* nist = G4NistManager::Instance();\n\n"; }

  // Elements first: a compound refers to them.
  bool any_element = false;
  for (std::size_t i = 0; i < m.elements.size(); ++i) {
    const Element& e = m.elements[i];
    bool used = false;
    for (const Material& mm : m.materials) {
      if (!mm.nist_name.empty()) { continue; }
      for (const Component& c : mm.components) {
        if (c.element == static_cast<int>(i)) { used = true; }
      }
    }
    if (!used) { continue; }
    any_element = true;
    f << "  auto* " << detail::ElemVar(m, static_cast<int>(i)) << " = new G4Element(\""
      << e.name << "\", \"" << e.symbol << "\", " << detail::Num(e.z) << ", "
      << detail::Num(e.a) << " * g / mole);\n";
  }
  if (any_element) { f << "\n"; }

  for (std::size_t i = 0; i < m.materials.size(); ++i) {
    const Material& mm = m.materials[i];
    const std::string var = detail::MatVar(m, static_cast<int>(i));
    if (!mm.nist_name.empty()) {
      f << "  auto* " << var << " = nist->FindOrBuildMaterial(\"" << mm.nist_name << "\");\n";
      continue;
    }
    const char* state = (mm.state == MatterState::kGas)      ? "kStateGas"
                        : (mm.state == MatterState::kLiquid) ? "kStateLiquid"
                                                             : "kStateSolid";
    f << "  auto* " << var << " = new G4Material(\"" << mm.name << "\", "
      << detail::Num(mm.density) << " * g / cm3, " << mm.components.size() << ", " << state
      << ");\n";
    for (const Component& c : mm.components) {
      if (c.element < 0) { continue; }
      if (mm.fraction_kind == Fraction::kAtomCount) {
        f << "  " << var << "->AddElement(" << detail::ElemVar(m, c.element) << ", "
          << static_cast<int>(c.amount + 0.5) << ");\n";
      } else {
        f << "  " << var << "->AddElement(" << detail::ElemVar(m, c.element) << ", "
          << detail::Num(c.amount) << ");\n";
      }
    }
    if (mm.mean_excitation_eV > 0) {
      f << "  " << var << "->SetMeanExcitationEnergy(" << detail::Num(mm.mean_excitation_eV)
        << " * eV);\n";
    }
  }
  f << "\n";
}

/// Emits ExeDir(), which both sidecar loaders need.
///
/// Voxel cells and mesh triangles go to files next to the source rather than into it: a 512^3
/// grid is 134 million values and a coarse CAD import is a few hundred thousand, and no
/// compiler will take either as an initialiser list. Those files are copied nowhere, so a run
/// started from any other directory has to find them by the executable's own path.
bool WriteExeDir(std::ofstream& f, const Model& m) {
  if (!detail::NeedsVoxelLoader(m) && !detail::NeedsMeshLoader(m)) { return false; }
  f << "namespace {\n"
       "/// The directory this executable is in. Resolving against argv[0] would not do: a\n"
       "/// program launched through PATH gets a bare name there.\n"
       "std::string ExeDir() {\n"
       "  char buf[1024] = {0};\n"
       "  const unsigned long n = GetModuleFileNameA(nullptr, buf, sizeof buf);\n"
       "  std::string p(buf, (n > 0) ? n : 0);\n"
       "  const std::size_t cut = p.find_last_of(\"\\\\/\");\n"
       "  return (cut == std::string::npos) ? std::string(\".\") : p.substr(0, cut);\n"
       "}\n"
       "}  // namespace\n\n";
  return true;
}

/// Emits the voxel-cell loader, and returns true if any solid needs it.
///
/// The per-class layers of @p s, or empty when every class is on the volume's own layer.
///
/// The same rule build_scene.hh applies, and it has to be the same one: if the two disagree
/// about whether a phantom HAS per-class layers, the builder and the project it generates
/// transport it differently, and the comparison between them is what would notice - which is
/// a slow and confusing way to find a duplicated rule. Hence one function, called by the
/// writer for the sidecar and by the emitter for the code.
///
/// Which classes are ABSENT from the scene, or empty if none are. Absence is a fact about a
/// class and not a layer it sits on - see builder::kNullLayer - so it travels as its own run.
inline std::vector<unsigned char> ClassAbsentOf(const Solid& s) {
  if (s.shape != Shape::kVoxelGrid || s.voxel_classes.empty()) { return {}; }
  std::vector<unsigned char> absent(s.voxel_classes.size(), 0u);
  bool any = false;
  for (std::size_t i = 0; i < s.voxel_classes.size(); ++i) {
    if (s.voxel_classes[i].layer == kNullLayer) {
      absent[i] = 1u;
      any = true;
    }
  }
  return any ? absent : std::vector<unsigned char>{};
}

/// True if this solid is not part of the scene at all. See builder::kNullLayer.
///
/// The generated project has to agree with the builder's own scene or the whole point of
/// generating it is lost: a run in the builder and a run of the emitted Geant4 code must be
/// the same detector. build_scene.hh has the matching skip in its placement loop.
inline bool IsNullLayer(const Solid& s) { return s.layer == kNullLayer; }

inline std::vector<int> ClassLayersOf(const Solid& s) {
  if (s.shape != Shape::kVoxelGrid || s.voxel_classes.empty()) { return {}; }
  std::vector<int> layers(s.voxel_classes.size(), s.layer);
  bool differs = false;
  for (std::size_t i = 0; i < s.voxel_classes.size(); ++i) {
    const int L = s.voxel_classes[i].layer;
    // AN ABSENT CLASS CARRIES THE VOLUME'S LAYER HERE, exactly as in build_scene.hh. The tag
    // is not a layer and must never be written as one: a generated project that emitted it
    // would rank those cells two billion below everything instead of leaving them out, which
    // is a different detector from the one the builder ran. See builder::kNullLayer.
    if (L == kNullLayer) { continue; }
    if (L != kInheritLayer && L != s.layer) {
      layers[i] = L;
      differs = true;
    }
  }
  // Non-empty when EITHER thing has been said, because the runs travel together: the class
  // index per cell, the colours, the layers and the absence all arrive or none of them do.
  return (differs || !ClassAbsentOf(s).empty()) ? layers : std::vector<int>{};
}

/// Deliberately strict about the count: a cell file that did not match its grid would
/// otherwise transport with whatever happened to be in memory after it.
bool WriteVoxelLoader(std::ofstream& f, const Model& m) {
  if (!detail::NeedsVoxelLoader(m)) { return false; }
  f << "namespace {\n"
       "/// Reads nx*ny*nz shorts written next to the executable by the model builder.\n"
       "void LoadVoxelCells(G4VoxelGrid* grid, const char* file) {\n"
       "  const std::size_t want =\n"
       "      static_cast<std::size_t>(grid->GetNx()) * grid->GetNy() * grid->GetNz();\n"
       "  const std::string path = ExeDir() + \"\\\\\" + file;\n"
       "  FILE* f = std::fopen(path.c_str(), \"rb\");\n"
       "  if (f == nullptr) { f = std::fopen(file, \"rb\"); }\n"
       "  if (f == nullptr) {\n"
       "    std::printf(\"FATAL: cannot open voxel cells %s (nor %s)\\n\", path.c_str(),\n"
       "                file);\n"
       "    std::exit(2);\n"
       "  }\n"
       "  const std::size_t got = std::fread(grid->Cells().data(), sizeof(short), want, f);\n"
       "  std::fclose(f);\n"
       "  if (got != want) {\n"
       "    std::printf(\"FATAL: %s holds %zu cells, the grid needs %zu\\n\", path.c_str(),\n"
       "                got, want);\n"
       "    std::exit(2);\n"
       "  }\n"
       "}\n"
       "/// The same, for the per-cell CLASS index.\n"
       "///\n"
       "/// Only written when some class of this phantom is on a layer of its own: the class\n"
       "/// of a cell is what says which layer applies to it, and without it the project\n"
       "/// would transport the phantom as one layer while the builder transported it as\n"
       "/// several. Two answers from one model is what the comparison between them exists\n"
       "/// to prevent.\n"
       "void LoadVoxelClasses(G4VoxelGrid* grid, const char* file) {\n"
       "  const std::size_t want =\n"
       "      static_cast<std::size_t>(grid->GetNx()) * grid->GetNy() * grid->GetNz();\n"
       "  grid->ClassCells().assign(want, static_cast<short>(-1));\n"
       "  const std::string path = ExeDir() + \"\\\\\" + file;\n"
       "  FILE* f = std::fopen(path.c_str(), \"rb\");\n"
       "  if (f == nullptr) { f = std::fopen(file, \"rb\"); }\n"
       "  if (f == nullptr) {\n"
       "    std::printf(\"FATAL: cannot open voxel classes %s (nor %s)\\n\", path.c_str(),\n"
       "                file);\n"
       "    std::exit(2);\n"
       "  }\n"
       "  const std::size_t got =\n"
       "      std::fread(grid->ClassCells().data(), sizeof(short), want, f);\n"
       "  std::fclose(f);\n"
       "  if (got != want) {\n"
       "    std::printf(\"FATAL: %s holds %zu classes, the grid needs %zu\\n\",\n"
       "                path.c_str(), got, want);\n"
       "    std::exit(2);\n"
       "  }\n"
       "}\n"
       "}  // namespace\n\n";
  return true;
}

/// Emits the polycone/polyhedra section helper, and returns true if any solid needs it.
///
/// G4Polycone and G4Polyhedra take three parallel arrays - z, rInner, rOuter - and the model
/// holds one flat list of triples, in the order the builder's section editor shows them.
/// Splitting that in the generated code would mean three arrays per solid and a reader
/// checking that they line up; this way the generated line reads as triples and the split is
/// in one place.
bool WritePolyHelper(std::ofstream& f, const Model& m) {
  if (!detail::NeedsPolyHelper(m)) { return false; }
  f << "namespace {\n"
       "/// Splits a flat list of (z, rInner, rOuter) triples into the three arrays\n"
       "/// G4Polycone wants. The solid copies them in its constructor, so the vectors here\n"
       "/// can be local.\n"
       "void SplitSections(std::initializer_list<G4double> zrr, std::vector<G4double>& z,\n"
       "                   std::vector<G4double>& ri, std::vector<G4double>& ro) {\n"
       "  const G4double* p = zrr.begin();\n"
       "  for (std::size_t i = 0; i + 2 < zrr.size(); i += 3) {\n"
       "    z.push_back(p[i]);\n"
       "    ri.push_back(p[i + 1]);\n"
       "    ro.push_back(p[i + 2]);\n"
       "  }\n"
       "}\n"
       "\n"
       "G4Polycone* MakePolycone(const G4String& name, G4double sphi, G4double dphi,\n"
       "                         std::initializer_list<G4double> zrr) {\n"
       "  std::vector<G4double> z, ri, ro;\n"
       "  SplitSections(zrr, z, ri, ro);\n"
       "  return new G4Polycone(name, sphi, dphi, static_cast<G4int>(z.size()), z.data(),\n"
       "                        ri.data(), ro.data());\n"
       "}\n"
       "\n"
       "G4Polyhedra* MakePolyhedra(const G4String& name, G4double sphi, G4double dphi,\n"
       "                           G4int sides, std::initializer_list<G4double> zrr) {\n"
       "  std::vector<G4double> z, ri, ro;\n"
       "  SplitSections(zrr, z, ri, ro);\n"
       "  return new G4Polyhedra(name, sphi, dphi, sides, static_cast<G4int>(z.size()),\n"
       "                         z.data(), ri.data(), ro.data());\n"
       "}\n"
       "}  // namespace\n\n";
  return true;
}

/// Emits the mesh-triangle loader, and returns true if any solid needs it.
bool WriteMeshLoader(std::ofstream& f, const Model& m) {
  if (!detail::NeedsMeshLoader(m)) { return false; }
  f << "namespace {\n"
       "/// Reads a triangle list written next to the executable: a count, then that many\n"
       "/// nine-double triangles. Closing the solid is what builds its BVH, so it happens\n"
       "/// here rather than being left to the caller to forget.\n"
       "void LoadMeshTriangles(G4TessellatedSolid* solid, const char* file) {\n"
       "  const std::string path = ExeDir() + \"\\\\\" + file;\n"
       "  FILE* f = std::fopen(path.c_str(), \"rb\");\n"
       "  if (f == nullptr) { f = std::fopen(file, \"rb\"); }\n"
       "  if (f == nullptr) {\n"
       "    std::printf(\"FATAL: cannot open mesh %s (nor %s)\\n\", path.c_str(), file);\n"
       "    std::exit(2);\n"
       "  }\n"
       "  unsigned long long n = 0;\n"
       "  if (std::fread(&n, sizeof n, 1, f) != 1 || n == 0) {\n"
       "    std::printf(\"FATAL: %s has no triangle count\\n\", path.c_str());\n"
       "    std::exit(2);\n"
       "  }\n"
       "  std::vector<double> tri(static_cast<std::size_t>(n) * 9);\n"
       "  const std::size_t got = std::fread(tri.data(), sizeof(double), tri.size(), f);\n"
       "  std::fclose(f);\n"
       "  if (got != tri.size()) {\n"
       "    std::printf(\"FATAL: %s holds %zu of %zu numbers\\n\", path.c_str(), got,\n"
       "                tri.size());\n"
       "    std::exit(2);\n"
       "  }\n"
       "  solid->AddTriangles(tri);\n"
       "  solid->SetSolidClosed(true);\n"
       "}\n"
       "}  // namespace\n\n";
  return true;
}

void WriteSolids(std::ofstream& f, const Model& m) {
  f << "  // ---------------------------------------------------------------- solids\n";
  for (int i : EmissionOrder(m)) {
    f << "  auto* " << detail::SolidVar(m, i) << " = " << detail::SolidExpr(m, i) << ";\n";
    if (m.solids[i].shape == Shape::kVoxelGrid) {
      // Fill the cells from the sidecar. The loader is emitted once, below.
      f << "  LoadVoxelCells(" << detail::SolidVar(m, i) << ", \"" << m.solids[i].name
        << ".cells\");\n";
      // AND SAY WHAT THE NUMBERS IN IT MEAN.
      //
      // The .cells file holds MODEL material indices - see the writer below, which walks the
      // classes and stores `c.material`. Read straight into a grid they are numbers from the
      // wrong table: G4VoxelGrid expects device indices, which are handed out later and in
      // placement order. So the grid is given the model's material list, in model order, and
      // translates for itself. Same mechanism as build_scene.hh, because it is the same file
      // format being read.
      //
      // This was missing and the builder's comparison against the generated project could not
      // see it: both sides were tested on a model of air and water alone, where model order
      // and device order coincide. The moment the selftest phantom used a third material the
      // two disagreed by 96%, which is what a phantom of the wrong material deposits. See
      // docs/RISK.md V20.
      if (!m.materials.empty()) {
        f << "  " << detail::SolidVar(m, i) << "->SetCellMaterials({";
        for (std::size_t k = 0; k < m.materials.size(); ++k) {
          if (k > 0) { f << ", "; }
          f << detail::MatVar(m, static_cast<int>(k));
        }
        f << "});\n";
      }
      // PER-CLASS LAYERS, when this phantom has any that differ from its own layer.
      //
      // Three things have to arrive together or none of them mean anything: the class index
      // per cell, one colour per class (which is what tells the grid it HAS classes, and so
      // where its per-class run goes), and the layers themselves.
      const std::vector<int> cl = ClassLayersOf(m.solids[i]);
      if (!cl.empty()) {
        f << "  LoadVoxelClasses(" << detail::SolidVar(m, i) << ", \"" << m.solids[i].name
          << ".classes\");\n";
        f << "  " << detail::SolidVar(m, i) << "->ClassColours() = {";
        for (std::size_t k = 0; k < m.solids[i].voxel_classes.size(); ++k) {
          const VoxelClass& vc = m.solids[i].voxel_classes[k];
          const unsigned int al =
              vc.visible ? static_cast<unsigned int>(vc.opacity * 255.0f + 0.5f) : 0u;
          const unsigned int rgba =
              (al << 24) | (static_cast<unsigned int>(vc.r * 255.0f + 0.5f) << 16)
              | (static_cast<unsigned int>(vc.g * 255.0f + 0.5f) << 8)
              | static_cast<unsigned int>(vc.b * 255.0f + 0.5f);
          if (k > 0) { f << ", "; }
          f << "0x" << std::hex << rgba << std::dec << "u";
        }
        f << "};\n";
        f << "  " << detail::SolidVar(m, i) << "->ClassLayers() = {";
        for (std::size_t k = 0; k < cl.size(); ++k) {
          if (k > 0) { f << ", "; }
          f << cl[k];
        }
        f << "};\n";
        // AND WHICH CLASSES ARE NOT IN THE SCENE AT ALL. Emitted only when some class is
        // absent, so an ordinary phantom's generated code is unchanged.
        const std::vector<unsigned char> ab = ClassAbsentOf(m.solids[i]);
        if (!ab.empty()) {
          f << "  " << detail::SolidVar(m, i) << "->ClassAbsent() = {";
          for (std::size_t k = 0; k < ab.size(); ++k) {
            if (k > 0) { f << ", "; }
            f << static_cast<int>(ab[k]) << "u";
          }
          f << "};\n";
        }
      }
    }
    if (m.solids[i].shape == Shape::kImportedMesh) {
      // Fill the triangles from the sidecar and close the solid, which builds its BVH.
      f << "  LoadMeshTriangles(" << detail::SolidVar(m, i) << ", \"" << m.solids[i].name
        << ".mesh\");\n";
    }
  }
  f << "\n";
}

void WritePlacements(std::ofstream& f, const Model& m) {
  f << "  // ------------------------------------------------- logical volumes and placements\n"
    << "  //\n"
    << "  // Placements use the layer form of G4PVPlacement: the last argument is the layer\n"
    << "  // index, and a higher layer wins wherever two volumes overlap. The world is layer\n"
    << "  // 0. See src/geometry/navigator.cuh for why the layer model replaces the\n"
    << "  // mother/daughter tree, and G4PVPlacement.hh for the constructor that still takes\n"
    << "  // a mother if you prefer to express containment that way.\n";

  const int world = m.world();
  for (std::size_t i = 0; i < m.solids.size(); ++i) {
    const int idx = static_cast<int>(i);
    if (IsOperandOnly(m, idx)) { continue; }  // consumed by a boolean, never placed
    // Not in the scene, so not in the file. The builder's own build_scene.hh skips it in the
    // same place and for the same reason; a project that emitted it would be a different
    // detector from the one that was run, which is the one thing this file must never be.
    if (IsNullLayer(m.solids[i]) && idx != world) { continue; }
    const Solid& s = m.solids[i];
    const std::string logic = detail::LogicVar(m, idx);
    const std::string mat = (s.material >= 0) ? detail::MatVar(m, s.material)
                                              : "nullptr /* no material assigned */";
    f << "\n  auto* " << logic << " = new G4LogicalVolume(" << detail::SolidVar(m, idx)
      << ", " << mat << ", \"" << s.name << "\");\n";

    // The rotation, and the position, after the anchor chain has been followed. A volume
    // anchored to another is placed in that volume's frame; SolidWorldPlacement in model.hh
    // composes the chain, and it is the same function the GUI's own build calls - two
    // implementations of this would be two chances for a saved project to place a volume
    // somewhere other than where it was run.
    //
    // The rotation is emitted as the chain of rotateX/Y/Z calls rather than as nine numbers,
    // because that is what a person editing the generated file would have written and can
    // still read. rotateX and friends pre-multiply, so emitting the outermost anchor's calls
    // first and the volume's own last composes in the right order. The *position* is emitted
    // as a number: it is a number, and the arithmetic that produced it - an offset rotated
    // into a parent frame - would only be noise in a detector description.
    double world_rot[9], world_pos[3];
    SolidWorldPlacement(m, static_cast<int>(idx), world_rot, world_pos);

    // The chain, outermost anchor first.
    std::vector<int> chain;
    for (int at = static_cast<int>(idx); at >= 0 && chain.size() <= m.solids.size();) {
      chain.push_back(at);
      const int next = m.solids[static_cast<std::size_t>(at)].anchor;
      if (next < 0 || next == at || next >= static_cast<int>(m.solids.size())) { break; }
      at = next;
    }
    bool has_rot = false;
    for (int at : chain) {
      const Solid& q = m.solids[static_cast<std::size_t>(at)];
      if (q.rot[0] != 0 || q.rot[1] != 0 || q.rot[2] != 0) { has_rot = true; }
    }
    std::string rot_var = "nullptr";
    if (has_rot) {
      rot_var = detail::Ident(s.name, "rot");
      f << "  auto* " << rot_var << " = new G4RotationMatrix();\n";
      if (chain.size() > 1) {
        f << "  // anchored to " << m.solids[static_cast<std::size_t>(chain[1])].name
          << "; its rotation is applied first\n";
      }
      // The matrix Geant4 takes is the world -> solid map, so rotating the object by +a means
      // rotating the frame by -a. The builder stores the object rotation, which is what the
      // user manipulated, so the signs are inverted here.
      for (std::size_t k = chain.size(); k-- > 0;) {
        const Solid& q = m.solids[static_cast<std::size_t>(chain[k])];
        if (q.rot[0] != 0) {
          f << "  " << rot_var << "->rotateX(" << detail::Deg(-q.rot[0]) << ");\n";
        }
        if (q.rot[1] != 0) {
          f << "  " << rot_var << "->rotateY(" << detail::Deg(-q.rot[1]) << ");\n";
        }
        if (q.rot[2] != 0) {
          f << "  " << rot_var << "->rotateZ(" << detail::Deg(-q.rot[2]) << ");\n";
        }
      }
    }

    // The world is the one placement with no mother, and Construct() has to return it. Every
    // other volume takes the layer form. Emitting both for the world would place it twice -
    // harmless to look at, since the second is identical, but wrong in the volume count and
    // confusing to read.
    if (idx == world) {
      f << "  auto* physWorld = new G4PVPlacement(" << rot_var << ", G4ThreeVector("
        << detail::Len(world_pos[0]) << ", " << detail::Len(world_pos[1]) << ", "
        << detail::Len(world_pos[2]) << "), " << logic << ", \"" << s.name
        << "\", nullptr, false, 0, true);\n";
    } else {
      f << "  new G4PVPlacement(" << rot_var << ", G4ThreeVector("
        << detail::Len(world_pos[0]) << ", " << detail::Len(world_pos[1]) << ", "
        << detail::Len(world_pos[2]) << "), " << logic << ", \"" << s.name << "\", "
        << s.layer << ");\n";
    }

    // Visualisation.
    char col[128];
    // The alpha is emitted too: G4Colour carries it, Geant4 means transparency by it, and a
    // saved project that came back opaque would have lost something the user set.
    std::snprintf(col, sizeof col, "G4Colour(%.3f, %.3f, %.3f, %.3f)", s.r, s.g, s.b,
                  s.opacity);
    const std::string vis = detail::Ident(s.name, "vis");
    f << "  static G4VisAttributes " << vis << "(" << (s.visible ? "true" : "false") << ", "
      << col << ");\n";
    if (s.wireframe) { f << "  " << vis << ".SetForceWireframe(true);\n"; }
    f << "  " << logic << "->SetVisAttributes(&" << vis << ");\n";

    for (std::size_t k = 0; k < m.scorers.size(); ++k) {
      for (int v : m.scorers[k].solids) {
        if (v == idx) { f << "  fScored" << k << ".push_back(" << logic << ");\n"; }
      }
    }
  }
  f << "\n  return physWorld;\n}\n\n";
}

/// The base primitive a scorer is written against, and the class name a custom one gets.
/// Defined below with the emitter that uses them most; declared here because WriteSD, which
/// comes first, has to name the same classes the emitter writes.
const char* BaseScorerClass(const Scorer& sc);
std::string CustomScorerClass(const Scorer& sc);

void WriteSD(std::ofstream& f, const Model& m) {
  f << "void DetectorConstruction::ConstructSDandField() {\n";
  if (m.scorers.empty()) {
    f << "  // No scorers were defined in the model, so nothing is sensitive. Add one with\n"
      << "  // G4MultiFunctionalDetector and SetSensitiveDetector, as in examples/B1.\n";
  }
  for (std::size_t k = 0; k < m.scorers.size(); ++k) {
    const Scorer& sc = m.scorers[k];
    // The same choice ConstructSDandField makes in build_scene.hh, and it has to be the same
    // choice: a project that registered a plain G4PSEnergyDeposit where the GUI ran a 3D one
    // would step differently and report a different number for the same model.
    //
    // A custom scorer registers its own generated subclass instead. As generated that class
    // behaves identically to the base, so this changes what the code says and not what it
    // computes - until somebody edits the file, which is what the flag is for.
    const std::string prim = sc.custom ? CustomScorerClass(sc) : BaseScorerClass(sc);
    f << "  {\n    auto* det = new G4MultiFunctionalDetector(\"" << sc.name << "SD\");\n"
      << "    det->RegisterPrimitive(new " << prim << "(\"" << sc.name << "\"));\n"
      << "    for (G4LogicalVolume* lv : fScored" << k << ") { SetSensitiveDetector(lv, det); }\n"
      << "  }\n";
  }
  f << "}\n";
}

/// One source's gun configuration, as a `case` body. Used by both the single- and the
/// multi-source form, so the two cannot describe the same source differently.
void WriteOneSource(std::ofstream& f, const Source& s, const char* ind) {
  f << ind << "fParticleGun->SetParticleDefinition(table->FindParticle(\"" << s.particle
    << "\"));\n";
  if (s.spectrum_file.empty()) {
    f << ind << "fParticleGun->SetParticleEnergy(" << detail::Num(s.energy_MeV) << " * MeV);\n";
  } else {
    f << ind << "fParticleGun->SetEnergySpectrumFromCSV(\"" << s.spectrum_file << "\");\n";
  }
  f << ind << "fParticleGun->SetParticlePosition(G4ThreeVector(" << detail::Len(s.pos[0])
    << ", " << detail::Len(s.pos[1]) << ", " << detail::Len(s.pos[2]) << "));\n"
    << ind << "fParticleGun->SetParticleMomentumDirection(G4ThreeVector("
    << detail::Num(s.dir[0]) << ", " << detail::Num(s.dir[1]) << ", " << detail::Num(s.dir[2])
    << "));\n";

  switch (s.kind) {
    case SourceKind::kBeam:
      if (s.profile == BeamProfile::kElliptical) {
        f << ind << "fParticleGun->SetBeamCrossSectionElliptical(" << detail::Len(s.half_x)
          << ", " << detail::Len(s.half_y) << ");\n";
      } else {
        f << ind << "fParticleGun->SetBeamCrossSectionRectangular(" << detail::Len(s.half_x)
          << ", " << detail::Len(s.half_y) << ");\n";
      }
      break;
    case SourceKind::kPoint:
      if (s.angular_spread_deg > 0) {
        f << ind << "fParticleGun->SetAngularSpread(" << detail::Deg(s.angular_spread_deg)
          << ");\n";
      }
      break;
    case SourceKind::kIsotropicShell:
      f << ind << "fParticleGun->SetIsotropicShell(" << detail::Len(s.radius) << ");\n";
      break;
    case SourceKind::kVolume:
      f << ind << "fParticleGun->SetSourceVolumeBox(" << detail::Len(s.half_x) << ", "
        << detail::Len(s.half_y) << ", " << detail::Len(s.half_z) << ");\n";
      break;
    case SourceKind::kRadioactive:
      f << ind << "// Radioactive source: " << s.nuclide << " at " << detail::Num(s.activity)
        << (s.activity_in_curie ? " Ci" : " Bq") << ".\n"
        << ind << "// Decay sampling is not implemented yet, so this is emitted as an\n"
        << ind << "// isotropic source of the nuclide's principal gamma. Check the energy\n"
        << ind << "// before trusting it.\n"
        << ind << "fParticleGun->SetIsotropic();\n";
      break;
  }
}

void WritePrimary(std::ofstream& f, const Model& m) {
  f << "/// \\file PrimaryGeneratorAction.cc\n"
    << "/// \\brief Sources for " << m.name << ", generated by the g4gpu model builder.\n"
    << "///\n"
    << "/// GeneratePrimaries is called once per event, as Geant4 calls it, and everything in\n"
    << "/// it is ordinary host code. Edit it freely: draw from a Gaussian, read a phase-space\n"
    << "/// file, fire a different particle on alternate events. Anything set on the gun before\n"
    << "/// GeneratePrimaryVertex wins, so\n"
    << "///\n"
    << "///     fParticleGun->SetParticlePosition(G4ThreeVector(G4RandGauss::shoot(0, 3*mm),\n"
    << "///                                                     G4RandGauss::shoot(0, 3*mm),\n"
    << "///                                                     -20*cm));\n"
    << "///     fParticleGun->GeneratePrimaryVertex(anEvent);\n"
    << "///\n"
    << "/// is a Gaussian beam spot, and needs nothing the builder has to know about.\n\n"
    << "#include \"PrimaryGeneratorAction.hh\"\n\n"
    << "#include \"G4ParticleTable.hh\"\n"
    << "#include \"G4RunManager.hh\"\n"
    << "#include \"G4SystemOfUnits.hh\"\n"
    << "#include \"Randomize.hh\"\n\n"
    << "PrimaryGeneratorAction::PrimaryGeneratorAction() {\n"
    << "  fParticleGun = new G4ParticleGun(1);\n"
    << "  if (G4RunManager::Instance() != nullptr) {\n"
    << "    G4RunManager::Instance()->SetGun(fParticleGun);\n"
    << "  }\n}\n\n"
    << "PrimaryGeneratorAction::~PrimaryGeneratorAction() { delete fParticleGun; }\n\n";

  std::vector<const Source*> live;
  double wsum = 0;
  for (const Source& s : m.sources) {
    if (!s.enabled || s.weight <= 0) { continue; }
    live.push_back(&s);
    wsum += s.weight;
  }

  if (live.empty()) {
    f << "void PrimaryGeneratorAction::GeneratePrimaries(G4Event*) {\n"
      << "  // No enabled source with a positive weight. A run would produce nothing, so this\n"
      << "  // says so rather than firing an unconfigured gun.\n"
      << "  static bool warned = false;\n"
      << "  if (!warned) {\n"
      << "    G4cerr << \"PrimaryGeneratorAction: the model has no enabled source.\\n\";\n"
      << "    warned = true;\n"
      << "  }\n}\n";
    return;
  }

  if (live.size() == 1) {
    f << "void PrimaryGeneratorAction::GeneratePrimaries(G4Event* anEvent) {\n"
      << "  auto* table = G4ParticleTable::GetParticleTable();\n";
    WriteOneSource(f, *live.front(), "  ");
    f << "  fParticleGun->GeneratePrimaryVertex(anEvent);\n"
      << "}\n";
    return;
  }

  // Several sources: one per event, by weight.
  //
  // A uniform draw against a cumulative table, which is the obvious thing to write and is now
  // the correct thing to write. An earlier version of this file emitted exactly this loop when
  // GeneratePrimaries was called once per *run*, and it therefore chose one source for the
  // whole run - two million events from whichever beam the first random number landed on.
  // The loop was never the problem.
  f << "namespace {\n\n"
    << "/// Cumulative source weights, normalised. Edit them here if you like; nothing else\n"
    << "/// reads them.\n"
    << "const G4double kSourceCdf[" << live.size() << "] = {";
  double run = 0;
  for (std::size_t i = 0; i < live.size(); ++i) {
    run += live[i]->weight;
    if (i > 0) { f << ", "; }
    f << detail::Num(run / wsum);
  }
  f << "};\n\n"
    << "/// Which source fires this event.\n"
    << "int PickSource() {\n"
    << "  const G4double u = G4UniformRand();\n"
    << "  for (int i = 0; i < " << live.size() << "; ++i) {\n"
    << "    if (u < kSourceCdf[i]) { return i; }\n"
    << "  }\n"
    << "  return " << (live.size() - 1) << ";\n"
    << "}\n\n"
    << "}  // namespace\n\n";

  f << "void PrimaryGeneratorAction::GeneratePrimaries(G4Event* anEvent) {\n"
    << "  // One source per event, chosen by weight. Over a run each gets its share; per event\n"
    << "  // it gets all or nothing, which is what a source is.\n"
    << "  auto* table = G4ParticleTable::GetParticleTable();\n"
    << "  switch (PickSource()) {\n";
  for (std::size_t i = 0; i < live.size(); ++i) {
    f << "    case " << i << ":  // " << live[i]->name << ", weight "
      << detail::Num(live[i]->weight) << " (" << detail::Num(100.0 * live[i]->weight / wsum)
      << "%)\n";
    WriteOneSource(f, *live[i], "      ");
    f << "      break;\n";
  }
  f << "    default: break;\n"
    << "  }\n"
    << "  fParticleGun->GeneratePrimaryVertex(anEvent);\n"
    << "}\n";
}

/// RunAction, and the accumulator EventAction feeds.
///
/// Two numbers come out of a run and they are not the same number. The *scorers* produce the
/// authoritative one: they run on the device, step by step, and B1's agreement with Geant4 to
/// 0.09 sigma is measured on them. `fEdep` is what the generated SteppingAction adds up, and
/// it exists so that the stepping hook is a working example rather than an empty function -
/// for a scorer over one volume the two agree, and where they do not it is because the
/// stepping action was edited, which is what it is there for.
void WriteRunActionFiles(const fs::path& dir) {
  {
    std::ofstream f(dir / "include" / "RunAction.hh");
    f << "/// \\file RunAction.hh\n\n#ifndef RunAction_h\n#define RunAction_h 1\n\n"
      << "#include \"G4UserRunAction.hh\"\n#include \"globals.hh\"\n\nclass G4Run;\n\n"
      << "/// Start and end of run. Prints what the scorers measured.\n"
      << "class RunAction : public G4UserRunAction {\n public:\n"
      << "  RunAction() = default;\n  ~RunAction() override = default;\n\n"
      << "  void BeginOfRunAction(const G4Run*) override;\n"
      << "  void EndOfRunAction(const G4Run*) override;\n\n"
      << "  /// Called by EventAction at the end of each event. See the note in RunAction.cc\n"
      << "  /// about how this relates to what the scorers report.\n"
      << "  void AddEdep(G4double edep) {\n"
      << "    fEdep += edep;\n"
      << "    fEdep2 += edep * edep;\n"
      << "  }\n\n"
      << " private:\n"
      << "  G4double fEdep = 0.;\n"
      << "  G4double fEdep2 = 0.;\n"
      << "};\n\n#endif\n";
  }
  {
    std::ofstream f(dir / "src" / "RunAction.cc");
    f << "/// \\file RunAction.cc\n\n#include \"RunAction.hh\"\n\n"
      << "#include <cmath>\n#include <cstdio>\n\n"
      << "#include \"G4RunManager.hh\"\n#include \"G4SDManager.hh\"\n"
      << "#include \"G4SystemOfUnits.hh\"\n\n"
      << "void RunAction::BeginOfRunAction(const G4Run*) {\n"
      << "  fEdep = 0.;\n  fEdep2 = 0.;\n"
      << "  std::printf(\"\\n### Run start\\n\");\n"
      << "}\n\n"
      << "void RunAction::EndOfRunAction(const G4Run* run) {\n"
      << "  const G4int n = run->GetNumberOfEvent();\n"
      << "  if (n == 0) { return; }\n"
      << "  auto* rm = G4RunManager::Instance();\n"
      << "  const auto& scorers = G4SDManager::GetSDMpointer()->Scorers();\n"
      << "  std::printf(\"\\n--------------------End of Global Run-----------------------\\n\");\n"
      << "  std::printf(\" %d events\\n\", n);\n"
      << "  for (std::size_t i = 0; i < scorers.size(); ++i) {\n"
      << "    const G4double total = scorers[i]->total;\n"
      << "    // The uncertainty on the sum, from the per-event sum of squares.\n"
      << "    G4double rms = scorers[i]->total_sq - total * total / n;\n"
      << "    rms = (rms > 0.) ? std::sqrt(rms) : 0.;\n"
      << "    const G4double mass = rm->ScoredMass(static_cast<G4int>(i));\n"
      << "    std::printf(\" %-16s %.6g MeV  rms %.4g\", scorers[i]->GetName().c_str(),\n"
      << "                total, rms);\n"
      << "    if (mass > 0) {\n"
      << "      std::printf(\"   dose %.5g pGy\", total * MeV / joule / mass * gray / picogray);\n"
      << "    }\n"
      << "    std::printf(\"\\n\");\n"
      << "  }\n"
      << "  // What SteppingAction accumulated, for comparison.\n"
      << "  //\n"
      << "  // The scorers above are the authoritative numbers: they are computed on the\n"
      << "  // device, step by step, where the steps are. This total comes through\n"
      << "  // SteppingAction -> EventAction -> here, which is the hook you edit, and it is\n"
      << "  // printed so that an edit to that hook has somewhere to show up. For the stock\n"
      << "  // filter - one scoring volume, energy added - the two agree.\n"
      << "  if (fEdep > 0.) {\n"
      << "    G4double rms = fEdep2 - fEdep * fEdep / n;\n"
      << "    rms = (rms > 0.) ? std::sqrt(rms) : 0.;\n"
      << "    std::printf(\" %-16s %.6g MeV  rms %.4g   (SteppingAction)\\n\", \"stepping\",\n"
      << "                fEdep, rms);\n"
      << "  }\n"
      << "  std::printf(\"------------------------------------------------------------\\n\");\n"
      << "  const auto& st = rm->GetLastRunStats();\n"
      << "  std::printf(\"time %.3f ms = %.3g events/s\\n\", st.milliseconds,\n"
      << "              n / (st.milliseconds * 1e-3));\n"
      << "}\n";
  }
}
/// The action classes a Geant4 example has, written out so a generated project has them too.
///
/// The generator used to emit three files - DetectorConstruction, PrimaryGeneratorAction,
/// RunAction - and wire them into main() by hand. That compiles and runs, but it is not what a
/// Geant4 project looks like, and the difference is not cosmetic: there was nowhere to put
/// per-event code, nowhere to put per-step code, and no ActionInitialization, which is the
/// class Geant4 documentation tells you to edit first. Somebody opening the project to *do*
/// something with it found no hook and had to add the file themselves.
///
/// These are deliberately close to examples/B1's, which is the file every Geant4 user has read.
/// SteppingAction accumulates into EventAction, EventAction into RunAction, exactly as B1 does.
/// The scorers still produce the authoritative numbers - RunAction prints those - so the
/// accumulation here is a worked example of the hook rather than the thing the run depends on.
void WriteActionFiles(const fs::path& dir, const Model& m) {
  // ---- ActionInitialization
  {
    std::ofstream f(dir / "include" / "ActionInitialization.hh");
    f << "/// \\file ActionInitialization.hh\n"
      << "/// \\brief Where a generated project's user actions are registered.\n\n"
      << "#ifndef ActionInitialization_h\n#define ActionInitialization_h 1\n\n"
      << "#include \"G4VUserActionInitialization.hh\"\n\n"
      << "/// Registers the run, event, stepping and primary-generator actions.\n"
      << "///\n"
      << "/// This is the first file to edit when adding behaviour to the project: everything\n"
      << "/// the run does that is not geometry or physics is reached from here.\n"
      << "class ActionInitialization : public G4VUserActionInitialization {\n"
      << " public:\n"
      << "  ActionInitialization() = default;\n"
      << "  ~ActionInitialization() override = default;\n\n"
      << "  void BuildForMaster() const override;\n"
      << "  void Build() const override;\n"
      << "};\n\n#endif\n";
  }
  {
    std::ofstream f(dir / "src" / "ActionInitialization.cc");
    f << "/// \\file ActionInitialization.cc\n\n"
      << "#include \"ActionInitialization.hh\"\n\n"
      << "#include \"EventAction.hh\"\n"
      << "#include \"PrimaryGeneratorAction.hh\"\n"
      << "#include \"RunAction.hh\"\n"
      << "#include \"SteppingAction.hh\"\n\n"
      << "void ActionInitialization::BuildForMaster() const {\n"
      << "  // The master thread accumulates but does not generate primaries.\n"
      << "  SetUserAction(new RunAction);\n"
      << "}\n\n"
      << "void ActionInitialization::Build() const {\n"
      << "  SetUserAction(new PrimaryGeneratorAction);\n"
      << "  auto* runAction = new RunAction;\n"
      << "  SetUserAction(runAction);\n"
      << "  auto* eventAction = new EventAction(runAction);\n"
      << "  SetUserAction(eventAction);\n"
      << "  SetUserAction(new SteppingAction(eventAction));\n"
      << "}\n";
  }

  // ---- EventAction
  {
    std::ofstream f(dir / "include" / "EventAction.hh");
    f << "/// \\file EventAction.hh\n\n"
      << "#ifndef EventAction_h\n#define EventAction_h 1\n\n"
      << "#include \"G4UserEventAction.hh\"\n#include \"globals.hh\"\n\n"
      << "class RunAction;\n\n"
      << "/// Per-event accumulation.\n"
      << "///\n"
      << "/// SteppingAction adds each step's deposit here; at the end of the event the total\n"
      << "/// goes to RunAction, which is where a per-event distribution would be built. The\n"
      << "/// scorers attached in DetectorConstruction produce the numbers the run reports;\n"
      << "/// this is the hook for anything they do not cover.\n"
      << "class EventAction : public G4UserEventAction {\n"
      << " public:\n"
      << "  explicit EventAction(RunAction* runAction) : fRunAction(runAction) {}\n"
      << "  ~EventAction() override = default;\n\n"
      << "  void BeginOfEventAction(const G4Event*) override;\n"
      << "  void EndOfEventAction(const G4Event*) override;\n\n"
      << "  void AddEdep(G4double edep) { fEdep += edep; }\n\n"
      << " private:\n"
      << "  RunAction* fRunAction = nullptr;\n"
      << "  G4double fEdep = 0.;\n"
      << "};\n\n#endif\n";
  }
  {
    std::ofstream f(dir / "src" / "EventAction.cc");
    f << "/// \\file EventAction.cc\n\n"
      << "#include \"EventAction.hh\"\n\n"
      << "#include \"RunAction.hh\"\n\n"
      << "void EventAction::BeginOfEventAction(const G4Event*) { fEdep = 0.; }\n\n"
      << "void EventAction::EndOfEventAction(const G4Event*) {\n"
      << "  if (fRunAction != nullptr) { fRunAction->AddEdep(fEdep); }\n"
      << "}\n";
  }

  // ---- SteppingAction
  {
    std::ofstream f(dir / "include" / "SteppingAction.hh");
    f << "/// \\file SteppingAction.hh\n\n"
      << "#ifndef SteppingAction_h\n#define SteppingAction_h 1\n\n"
      << "#include \"G4UserSteppingAction.hh\"\n#include \"globals.hh\"\n\n"
      << "class EventAction;\n"
      << "class G4LogicalVolume;\n\n"
      << "/// Per-step code. Called for every step of every track.\n"
      << "///\n"
      << "/// The filter matters: without one this adds up the deposit in the whole world, and\n"
      << "/// the number means nothing. `fScoringVolume` is set from the first scored volume in\n"
      << "/// DetectorConstruction; change it, or drop the test, depending on what you want.\n"
      << "class SteppingAction : public G4UserSteppingAction {\n"
      << " public:\n"
      << "  explicit SteppingAction(EventAction* eventAction) : fEventAction(eventAction) {}\n"
      << "  ~SteppingAction() override = default;\n\n"
      << "  void UserSteppingAction(const G4Step*) override;\n\n"
      << " private:\n"
      << "  EventAction* fEventAction = nullptr;\n"
      << "  G4LogicalVolume* fScoringVolume = nullptr;\n"
      << "};\n\n#endif\n";
  }
  {
    std::ofstream f(dir / "src" / "SteppingAction.cc");
    f << "/// \\file SteppingAction.cc\n\n"
      << "#include \"SteppingAction.hh\"\n\n"
      << "#include \"DetectorConstruction.hh\"\n"
      << "#include \"EventAction.hh\"\n"
      << "#include \"G4LogicalVolume.hh\"\n"
      << "#include \"G4RunManager.hh\"\n"
      << "#include \"G4Step.hh\"\n\n"
      << "void SteppingAction::UserSteppingAction(const G4Step* step) {\n"
      << "  if (fScoringVolume == nullptr) {\n"
      << "    const auto* det = static_cast<const DetectorConstruction*>(\n"
      << "        G4RunManager::Instance()->GetUserDetectorConstruction());\n"
      << "    fScoringVolume = (det != nullptr) ? det->GetScoringVolume() : nullptr;\n"
      << "    if (fScoringVolume == nullptr) { return; }\n"
      << "  }\n"
      << "  auto* here = step->GetPreStepPoint()->GetTouchableHandle()->GetVolume()\n"
      << "                   ->GetLogicalVolume();\n"
      << "  if (here != fScoringVolume) { return; }\n"
      << "  if (fEventAction != nullptr) {\n"
      << "    fEventAction->AddEdep(step->GetTotalEnergyDeposit());\n"
      << "  }\n"
      << "}\n";
  }
}
/// The base primitive a scorer is written against, as a class name.
const char* BaseScorerClass(const Scorer& sc) {
  if (sc.per_voxel && (sc.quantity == ScoreQuantity::kEnergyDeposit
                       || sc.quantity == ScoreQuantity::kDose)) {
    return "G4PSEnergyDeposit3D";
  }
  switch (sc.quantity) {
    case ScoreQuantity::kDose: return "G4PSDoseDeposit";
    case ScoreQuantity::kFluence: return "G4PSCellFlux";
    case ScoreQuantity::kTrackLength: return "G4PSTrackLength";
    case ScoreQuantity::kStepCount: return "G4PSNofStep";
    case ScoreQuantity::kEnergyDeposit:
    default: return "G4PSEnergyDeposit";
  }
}

/// The class name a custom scorer is emitted under.
std::string CustomScorerClass(const Scorer& sc) {
  return detail::Ident(sc.name, "Scorer");
}

/// Writes one file pair per scorer flagged custom.
///
/// One pair per scorer, not one file holding all of them, because the point is that each is a
/// place to write code: two scorers with different filters in one file would have to be told
/// apart by name inside a shared function, which is the arrangement the flag exists to avoid.
///
/// The generated class does nothing its base does not - it overrides the hook and calls up -
/// so a project saved with the flag on and never edited reports the same numbers as one saved
/// with it off. That matters: the flag changes the *code*, and it should not change the
/// answer until somebody makes it.
void WriteCustomScorers(const fs::path& dir, const Model& m) {
  for (const Scorer& sc : m.scorers) {
    if (!sc.custom) { continue; }
    const std::string cls = CustomScorerClass(sc);
    const char* base = BaseScorerClass(sc);

    {
      std::ofstream f(dir / "include" / (cls + ".hh"));
      f << "/// \\file " << cls << ".hh\n"
        << "/// \\brief User-editable scorer for \"" << sc.name << "\".\n"
        << "///\n"
        << "/// Generated once, from the model builder, because \"" << sc.name
        << "\" is flagged\n"
        << "/// custom. **Saving the project again will overwrite it**, so if you edit this\n"
        << "/// file, either stop saving over it or rename the class.\n"
        << "///\n"
        << "/// It derives from " << base << " and, as written, does exactly what that does.\n"
        << "/// The hook is Accept(): return false and the deposit is ignored. That is where a\n"
        << "/// filter goes - an energy threshold, a particle species, a region within the\n"
        << "/// volume - and where a weighting goes, by scaling what you pass on.\n\n"
        << "#ifndef " << cls << "_h\n#define " << cls << "_h 1\n\n"
        << "#include \"G4SDManager.hh\"\n"
        << "#include \"globals.hh\"\n\n"
        << "class " << cls << " : public " << base << " {\n"
        << " public:\n"
        << "  explicit " << cls << "(const G4String& name) : " << base << "(name) {}\n"
        << "  ~" << cls << "() override = default;\n\n"
        << "  /// Says the per-event hook below is live. Leave it true, or the hook is never\n"
        << "  /// called and this class is just a rename.\n"
        << "  G4bool IsFiltered() const override { return true; }\n\n"
        << "  /// Whether this event's contribution counts, and how much of it.\n"
        << "  ///\n"
        << "  /// The value is **one event's total in this scorer's volumes**, not one step's\n"
        << "  /// deposit: the steps are on the GPU and never reach the host. See the note on\n"
        << "  /// G4VPrimitiveScorer::Accept before writing anything that assumes otherwise.\n"
        << "  G4bool Accept(G4double& value, G4int event_id) override;\n"
        << "};\n\n#endif\n";
    }
    {
      std::ofstream f(dir / "src" / (cls + ".cc"));
      f << "/// \\file " << cls << ".cc\n\n"
        << "#include \"" << cls << ".hh\"\n\n"
        << "#include \"G4SystemOfUnits.hh\"\n\n"
        << "G4bool " << cls << "::Accept(G4double& value, G4int event_id) {\n"
        << "  // As generated: every event counts, unweighted. That is what " << base << "\n"
        << "  // reports on its own, so an unedited custom scorer gives the same number as a\n"
        << "  // stock one - the flag changes the code, not the answer, until you change it.\n"
        << "  //\n"
        << "  // Things you might write here. Note that all of them are per *event*:\n"
        << "  //\n"
        << "  //   if (value < 100 * keV) { return false; }   // a trigger threshold\n"
        << "  //   value *= 1.2;                              // a detector response factor\n"
        << "  //   if ((event_id % 2) != 0) { return false; } // every other event\n"
        << "  (void)value;\n"
        << "  (void)event_id;\n"
        << "  return true;\n"
        << "}\n";
    }
  }
}
}  // namespace

bool WriteProject(const Model& model, const std::string& dir) {
  // Refuse before writing anything, rather than emitting code that does not compile. A
  // polycone used to reach the emitter's default case and come out as
  //
  //     auto* solidCone = nullptr /* Polycone is not yet emitted */;
  //
  // in a file the user is told is a working project. Both poly solids are emitted now; this
  // check is what keeps the next unemittable shape from repeating it, and what catches a
  // section list that is too short for G4Polycone's three parallel arrays.
  for (const Solid& s : model.solids) {
    if (detail::CanEmitSolid(s)) { continue; }
    std::printf("cannot save: \"%s\" is a %s and cannot be written as C++.\n", s.name.c_str(),
                ShapeName(s.shape));
    if (s.shape == Shape::kPolycone || s.shape == Shape::kPolyhedra) {
      std::printf("  It has %zu section values; G4%s needs whole (z, rInner, rOuter)\n"
                  "  triples and at least three of them.\n",
                  s.sections.size(), ShapeName(s.shape));
    }
    return false;
  }

  std::error_code ec;
  fs::create_directories(fs::path(dir) / "src", ec);
  fs::create_directories(fs::path(dir) / "include", ec);
  if (ec) {
    std::printf("cannot create %s: %s\n", dir.c_str(), ec.message().c_str());
    return false;
  }
  const std::string app = detail::Ident(model.name, "");

  // ---- include/DetectorConstruction.hh
  {
    std::ofstream f(fs::path(dir) / "include" / "DetectorConstruction.hh");
    if (!f) { return false; }
    f << "#include <vector>\n";
    WriteDetectorHeader(f, model);
  }

  // ---- src/DetectorConstruction.cc
  {
    std::ofstream f(fs::path(dir) / "src" / "DetectorConstruction.cc");
    if (!f) { return false; }
    f << "/// \\file DetectorConstruction.cc\n"
      << "/// \\brief Geometry for " << model.name
      << ", generated by the g4gpu model builder.\n\n"
      << "#include \"DetectorConstruction.hh\"\n\n"
      << "#include \"G4Colour.hh\"\n"
      << "#include \"G4LogicalVolume.hh\"\n"
      << "#include \"G4Material.hh\"\n"
      << "#include \"G4MultiFunctionalDetector.hh\"\n"
      << "#include \"G4NistManager.hh\"\n"
      << "#include \"G4PVPlacement.hh\"\n"
      << "#include \"G4SDManager.hh\"\n"
      << "#include \"G4Solids.hh\"\n"
      << "#include \"G4SystemOfUnits.hh\"\n"
      << "#include \"G4VisAttributes.hh\"\n";
    // The generated scorer classes, for the volumes that register them.
    for (const Scorer& sc : model.scorers) {
      if (sc.custom) { f << "#include \"" << CustomScorerClass(sc) << ".hh\"\n"; }
    }
    f << "\n"
      << "#include <cstdio>\n#include <cstdlib>\n#include <initializer_list>\n"
         "#include <string>\n#include <vector>\n\n";
    if (detail::NeedsVoxelLoader(model) || detail::NeedsMeshLoader(model)) {
      // Only when a sidecar loader is emitted: windows.h is a large include and ExeDir is
      // the only thing here that needs it.
      f << "#define WIN32_LEAN_AND_MEAN\n#define NOMINMAX\n#include <windows.h>\n\n";
    }
    WriteExeDir(f, model);
    WriteVoxelLoader(f, model);
    WriteMeshLoader(f, model);
    WritePolyHelper(f, model);
    f << "G4VPhysicalVolume* DetectorConstruction::Construct() {\n";
    WriteMaterials(f, model);
    WriteSolids(f, model);
    WritePlacements(f, model);
    WriteSD(f, model);
  }

  // ---- include/PrimaryGeneratorAction.hh
  {
    std::ofstream f(fs::path(dir) / "include" / "PrimaryGeneratorAction.hh");
    if (!f) { return false; }
    f << "/// \\file PrimaryGeneratorAction.hh\n\n"
      << "#ifndef PrimaryGeneratorAction_h\n#define PrimaryGeneratorAction_h 1\n\n"
      << "#include \"G4ParticleGun.hh\"\n"
      << "#include \"G4VUserPrimaryGeneratorAction.hh\"\n"
      << "#include \"globals.hh\"\n\n"
      << "class G4Event;\n\n"
      << "class PrimaryGeneratorAction : public G4VUserPrimaryGeneratorAction {\n"
      << " public:\n  PrimaryGeneratorAction();\n"
      << "  ~PrimaryGeneratorAction() override;\n\n"
      << "  void GeneratePrimaries(G4Event* anEvent) override;\n"
      << "  G4ParticleGun* GetParticleGun() { return fParticleGun; }\n\n"
      << " private:\n  G4ParticleGun* fParticleGun = nullptr;\n};\n\n#endif\n";
  }

  // ---- src/PrimaryGeneratorAction.cc
  {
    std::ofstream f(fs::path(dir) / "src" / "PrimaryGeneratorAction.cc");
    if (!f) { return false; }
    WritePrimary(f, model);
  }

  // ---- the action classes
  //
  // RunAction, EventAction, SteppingAction, ActionInitialization - the file set a Geant4
  // example has. The generator used to emit three files in total and wire them into main()
  // by hand; that compiles, but it leaves nowhere to put per-event or per-step code, which is
  // the first thing somebody opening a generated project wants to do.
  WriteRunActionFiles(fs::path(dir));
  WriteActionFiles(fs::path(dir), model);

  // ---- one file pair per scorer flagged custom
  WriteCustomScorers(fs::path(dir), model);

  // ---- the main file
  {
    std::ofstream f(fs::path(dir) / (app + ".cc"));
    if (!f) { return false; }
    f << "/// \\file " << app << ".cc\n"
      << "/// \\brief Main program for " << model.name
      << ", generated by the g4gpu model builder.\n"
      << "///\n"
      << "/// Run interactively:     " << app << "\n"
      << "/// With a macro:          " << app << " run1.mac\n"
      << "/// Or in batch:           " << app << " -n 1000000\n\n"
      << "#include <cstdio>\n#include <cstdlib>\n#include <cstring>\n#include <string>\n\n"
      << "#include \"ActionInitialization.hh\"\n"
      << "#include \"DetectorConstruction.hh\"\n"
      << "#include \"G4RunManager.hh\"\n"
      << "#include \"G4SystemOfUnits.hh\"\n"
      << "#include \"G4UIExecutive.hh\"\n"
      << "#include \"G4UImanager.hh\"\n"
      << "#include \"G4VisExecutive.hh\"\n\n"
      << "int main(int argc, char** argv) {\n"
      << "  auto* runManager = new G4RunManager;\n"
      << "  runManager->SetUserInitialization(new DetectorConstruction);\n"
      << "  // Every user action is registered from one place, as a Geant4 example does it.\n"
      << "  // Add a new one in ActionInitialization::Build rather than here.\n"
      << "  runManager->SetUserInitialization(new ActionInitialization);\n"
      << "  runManager->SetCutValue(" << detail::Num(model.physics.range_cut_mm) << " * mm);\n\n"
      << "  int n_events = 0;\n  std::string macro;\n"
      << "  for (int i = 1; i < argc; ++i) {\n"
      << "    if (std::strcmp(argv[i], \"-n\") == 0 && i + 1 < argc) {\n"
      << "      n_events = std::atoi(argv[++i]);\n"
      << "    } else if (argv[i][0] != '-') {\n      macro = argv[i];\n    }\n  }\n\n"
      << "  // The visualisation manager, as a Geant4 example creates it: /vis/open in a\n"
      << "  // macro then opens the viewer, with its run control bar, on this geometry.\n"
      << "  G4VisManager* visManager = new G4VisExecutive;\n"
      << "  visManager->Initialize();\n"
      << "  auto* ui = G4UImanager::GetUIpointer();\n\n"
      << "  if (!macro.empty()) {\n"
      << "    // A macro whose commands failed has not done what the file said, so the exit\n"
      << "    // code says so rather than reporting a run that did not happen.\n"
      << "    const int errors = ui->ExecuteMacroFile(macro);\n"
      << "    delete runManager;\n"
      << "    return (errors == 0) ? 0 : 1;\n"
      << "  }\n"
      << "  if (n_events > 0) {\n"
      << "    runManager->Initialize();\n"
      << "    runManager->BeamOn(n_events);\n"
      << "    delete runManager;\n    return 0;\n  }\n\n"
      << "  // Interactive: initialise, open the viewer, hand over.\n"
      << "  runManager->Initialize();\n"
      << "  auto* session = new G4UIExecutive(argc, argv);\n"
      << "  ui->ApplyCommand(\"/vis/open OGL 1280x800\");\n"
      << "  ui->ApplyCommand(\"/vis/drawVolume\");\n"
      << "  session->SessionStart();\n"
      << "  delete session;\n"
      << "  delete visManager;\n"
      << "  delete runManager;\n  return 0;\n}\n";
  }

  // ---- build script
  //
  // Two things about it are deliberate. It links the prebuilt engine archive and viewer
  // object rather than compiling the engine's eight translation units itself, because that is
  // minutes of nvcc and build_engine.bat has already done it. And the object files go
  // into build\ rather than next to the source: a project that can import CAD meshes should
  // not have a directory of files called *.obj in it meaning something else entirely.
  {
    std::ofstream f(fs::path(dir) / "build.bat");
    if (!f) { return false; }

    // Every translation unit, in one list, used for both the compile loop and the link. It is
    // built rather than written out because the set is no longer fixed: a project has one file
    // per scorer flagged custom, and a hand-maintained list would compile a file the link did
    // not mention, or the other way round.
    std::vector<std::string> units{app, "DetectorConstruction", "PrimaryGeneratorAction",
                                   "RunAction", "EventAction", "SteppingAction",
                                   "ActionInitialization"};
    for (const Scorer& sc : model.scorers) {
      if (sc.custom) { units.push_back(CustomScorerClass(sc)); }
    }

    f << "@echo off\n"
      << "rem Generated by the g4gpu model builder. Edit freely.\n"
      << "call \"D:/g4gpu/setupenv.bat\" || exit /b 1\n"
      << "call \"D:/g4gpu/build_engine.bat\" || exit /b 1\n"
      << "call \"D:/g4gpu/build_vis.bat\" || exit /b 1\n"
      << "pushd \"%~dp0\"\n"
      << "if not exist build mkdir build\n"
      << "set INC=-I \"%~dp0include\" -I D:\\g4gpu\\src -I D:\\g4gpu\\src\\g4\n"
      << "rem -x cu applies to every input that follows it and nvcc has no -x none to turn it\n"
      << "rem back off, so the prebuilt objects cannot be listed in the same command as the\n"
      << "rem sources: the CUDA frontend would try to parse them. Compile, then link.\n"
      << "for %%F in (";
    for (std::size_t i = 0; i < units.size(); ++i) {
      if (i > 0) { f << " "; }
      f << units[i];
    }
    f << ") do (\n"
      << "  if exist \"%%F.cc\" (\n"
      << "    nvcc -std=c++17 -O2 -arch=sm_86 %INC% -x cu -c -o build\\%%F.obj \"%%F.cc\""
      << " || goto :fail\n"
      << "  ) else (\n"
      << "    nvcc -std=c++17 -O2 -arch=sm_86 %INC% -x cu -c -o build\\%%F.obj"
      << " \"src\\%%F.cc\" || goto :fail\n"
      << "  )\n"
      << ")\n"
      << "nvcc -std=c++17 -O2 -arch=sm_86 -o " << app << ".exe ^\n";
    for (std::size_t i = 0; i < units.size(); ++i) {
      f << "  build\\" << units[i] << ".obj";
      f << ((i + 1 < units.size()) ? " ^\n" : " ^\n");
    }
    f << "  \"%G4GPU_ENGINE_OBJ%\" \"%G4GPU_VIS_OBJ%\" ^\n"
      << "  -lopengl32 -luser32 -lgdi32 -Xlinker /IMPLIB:build/" << app << ".lib"
      << " || goto :fail\n"
      << "popd\n"
      << "echo built " << app << ".exe\n"
      << "exit /b 0\n\n"
      << ":fail\n"
      << "popd\n"
      << "exit /b 1\n";
  }

  // ---- CMakeLists.txt and README
  //
  // A Geant4 example has both, and a project without them is a project you can only build the
  // one way its author built it. The build.bat above is the direct nvcc route the pipeline
  // uses; this is the portable one.
  {
    std::ofstream f(fs::path(dir) / "CMakeLists.txt");
    if (!f) { return false; }
    f << "#----------------------------------------------------------------------------\n"
      << "# " << model.name << ", generated by the g4gpu model builder.\n"
      << "#\n"
      << "# The same shape as a Geant4 example's CMakeLists.txt, with CUDA in place of a\n"
      << "# find_package(Geant4): there is no installed library to find, so this compiles the\n"
      << "# transport engine and the visualisation manager from the g4gpu tree alongside its\n"
      << "# own sources.\n"
      << "#\n"
      << "#   cmake -S . -B build -DG4GPU_DIR=D:/g4gpu\n"
      << "#   cmake --build build --config Release\n"
      << "#\n"
      << "# The transport engine is eight translation units and takes minutes to compile. If\n"
      << "# build_engine.bat has already produced out/transport_run.lib, link that instead:\n"
      << "#\n"
      << "#   cmake -S . -B build -DG4GPU_USE_PREBUILT_ENGINE=ON\n"
      << "cmake_minimum_required(VERSION 3.18)\n"
      << "project(" << app << " LANGUAGES CXX CUDA)\n\n"
      << "set(G4GPU_DIR \"D:/g4gpu\" CACHE PATH \"Root of the g4gpu source tree\")\n"
      << "if(NOT EXISTS \"${G4GPU_DIR}/src/host/transport_run.cu\")\n"
      << "  message(FATAL_ERROR\n"
      << "    \"G4GPU_DIR=${G4GPU_DIR} does not contain src/host/transport_run.cu. \"\n"
      << "    \"Pass -DG4GPU_DIR=<root of the g4gpu tree>.\")\n"
      << "endif()\n\n"
      << "option(G4GPU_USE_PREBUILT_ENGINE\n"
      << "       \"Link the prebuilt engine and vis objects instead of compiling them\" OFF)\n\n"
      << "set(CMAKE_CXX_STANDARD 17)\n"
      << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
      << "set(CMAKE_CUDA_STANDARD 17)\n"
      << "if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)\n"
      << "  set(CMAKE_CUDA_ARCHITECTURES 86)\n"
      << "endif()\n\n"
      << "# Every source is compiled as CUDA: they include headers with __host__ __device__\n"
      << "# functions in them, which the host compiler alone cannot parse.\n"
      << "set(SOURCES\n";
    // The same unit list the build script uses, so the two cannot disagree about what the
    // project consists of.
    f << "  ${PROJECT_SOURCE_DIR}/" << app << ".cc\n";
    std::vector<std::string> srcs{"DetectorConstruction", "PrimaryGeneratorAction",
                                  "RunAction", "EventAction", "SteppingAction",
                                  "ActionInitialization"};
    for (const Scorer& sc : model.scorers) {
      if (sc.custom) { srcs.push_back(CustomScorerClass(sc)); }
    }
    for (const std::string& s : srcs) {
      f << "  ${PROJECT_SOURCE_DIR}/src/" << s << ".cc\n";
    }
    f << ")\n"
      << "if(NOT G4GPU_USE_PREBUILT_ENGINE)\n"
      << "  # GLOBbed, and that is the right call here rather than a hand-written list: the\n"
      << "  # engine is one translation unit per kernel family and the set is the engine's to\n"
      << "  # know, not this project's. A list written out here would go stale the day a\n"
      << "  # family is split further, and the symptom would be an unresolved launch stub.\n"
      << "  file(GLOB G4GPU_ENGINE_UNITS \"${G4GPU_DIR}/src/host/transport_run*.cu\")\n"
      << "  list(APPEND SOURCES ${G4GPU_ENGINE_UNITS})\n"
      << "  list(APPEND SOURCES \"${G4GPU_DIR}/src/render/vis_manager.cu\")\n"
      << "endif()\n"
      << "set_source_files_properties(${SOURCES} PROPERTIES LANGUAGE CUDA)\n\n"
      << "add_executable(" << app << " ${SOURCES})\n"
      << "target_include_directories(" << app << " PRIVATE\n"
      << "  ${PROJECT_SOURCE_DIR}/include\n"
      << "  ${G4GPU_DIR}/src\n"
      << "  ${G4GPU_DIR}/src/g4)\n"
      << "target_link_libraries(" << app << " PRIVATE opengl32 user32 gdi32)\n"
      << "if(G4GPU_USE_PREBUILT_ENGINE)\n"
      << "  target_link_libraries(" << app << " PRIVATE\n"
      << "    \"${G4GPU_DIR}/out/transport_run.lib\"\n"
      << "    \"${G4GPU_DIR}/out/vis_manager.obj\")\n"
      << "endif()\n\n"
      << "# The macros and any data sidecars, beside the executable, because the project\n"
      << "# looks for them next to itself at run time.\n"
      << "file(GLOB " << app << "_DATA \"${PROJECT_SOURCE_DIR}/*.mac\"\n"
      << "     \"${PROJECT_SOURCE_DIR}/*.cells\" \"${PROJECT_SOURCE_DIR}/*.mesh\"\n"
      << "     \"${PROJECT_SOURCE_DIR}/*.model\")\n"
      << "foreach(_f ${" << app << "_DATA})\n"
      << "  configure_file(${_f} ${PROJECT_BINARY_DIR} COPYONLY)\n"
      << "endforeach()\n";
  }
  {
    std::ofstream f(fs::path(dir) / "README");
    if (!f) { return false; }
    f << model.name << "\n";
    for (std::size_t i = 0; i < model.name.size(); ++i) { f << "="; }
    f << "\n\nGenerated by the g4gpu model builder. This is ordinary Geant4-shaped C++ and\n"
      << "nothing in it needs the builder to compile or to run.\n\n"
      << "WHAT IS HERE\n\n"
      << "  " << app << ".cc              main(); creates the run manager and hands over\n"
      << "  include/ and src/\n"
      << "    DetectorConstruction     the geometry, the materials, and the scorers\n"
      << "    PrimaryGeneratorAction   the source"
      << ((model.sources.size() > 1) ? "s, sampled by weight per event\n" : "\n")
      << "    ActionInitialization     where the user actions are registered\n"
      << "    RunAction                start and end of run; prints what the scorers read\n"
      << "    EventAction              per-event accumulation\n"
      << "    SteppingAction           per-step hook, filtered to the scoring volume\n";
    for (const Scorer& sc : model.scorers) {
      if (!sc.custom) { continue; }
      f << "    " << CustomScorerClass(sc);
      for (std::size_t i = CustomScorerClass(sc).size(); i < 25; ++i) { f << " "; }
      f << "an editable scorer for \"" << sc.name << "\"\n";
    }
    f << "  build.bat                the direct nvcc build\n"
      << "  CMakeLists.txt           the portable build\n"
      << "  run1.mac                 a macro that runs the model as the builder had it\n\n"
      << "BUILDING\n\n"
      << "  build.bat\n\n"
      << "or\n\n"
      << "  cmake -S . -B build -DG4GPU_DIR=D:/g4gpu -DG4GPU_USE_PREBUILT_ENGINE=ON\n"
      << "  cmake --build build --config Release\n\n"
      << "RUNNING\n\n"
      << "  " << app << " -n 100000      batch\n"
      << "  " << app << " run1.mac       a macro\n"
      << "  " << app << "                interactive, with the viewer\n\n"
      << "WHERE TO EDIT\n\n"
      << "  ActionInitialization::Build is the first place to look: every user action is\n"
      << "  registered there. SteppingAction is called once per event per scored volume\n"
      << "  rather than once per step - the steps are on the GPU - and the reason, and what\n"
      << "  it means for what you can compute there, is at the top of g4/G4Step.hh in the\n"
      << "  g4gpu tree.\n\n"
      << "  Saving the project again from the builder overwrites every file here.\n";
  }

  // ---- a macro
  {
    std::ofstream f(fs::path(dir) / "run1.mac");
    if (!f) { return false; }
    const Source* src = nullptr;
    for (const Source& s : model.sources) {
      if (s.enabled) { src = &s; break; }
    }
    f << "# Generated by the g4gpu model builder.\n/control/verbose 1\n\n/run/initialize\n\n";
    if (src != nullptr) {
      f << "/gun/particle " << src->particle << "\n";
      if (src->spectrum_file.empty()) {
        f << "/gun/energy " << detail::Num(src->energy_MeV) << " MeV\n";
      } else {
        f << "/gun/spectrum " << src->spectrum_file << "\n";
      }
      f << "/gun/position " << detail::Num(src->pos[0]) << " " << detail::Num(src->pos[1])
        << " " << detail::Num(src->pos[2]) << " mm\n"
        << "/gun/direction " << detail::Num(src->dir[0]) << " " << detail::Num(src->dir[1])
        << " " << detail::Num(src->dir[2]) << "\n";
      if (src->kind == SourceKind::kBeam) {
        f << (src->profile == BeamProfile::kElliptical ? "/gun/beamElliptical "
                                                       : "/gun/beamRectangular ")
          << detail::Num(src->half_x) << " " << detail::Num(src->half_y) << " mm\n";
      }
    }
    f << "\n/run/beamOn 100000\n";
  }

  // ---- voxel cells, one sidecar per grid
  //
  // The class assignment is applied here rather than shipping the raw values, so the
  // generated project does not need the classifier: it reads material indices directly. That
  // also means editing a class's material in the builder and saving again changes the data
  // file, which is the behaviour a user expects from a Save.
  for (const Solid& s : model.solids) {
    if (s.shape != Shape::kVoxelGrid) { continue; }
    const std::size_t n = static_cast<std::size_t>(s.p[3] + 0.5)
                          * static_cast<std::size_t>(s.p[4] + 0.5)
                          * static_cast<std::size_t>(s.p[5] + 0.5);
    std::vector<short> cells(n, static_cast<short>(s.material));
    if (s.voxel_values.size() == n && !s.voxel_classes.empty()) {
      for (std::size_t i = 0; i < n; ++i) {
        const float v = s.voxel_values[i];
        for (const VoxelClass& c : s.voxel_classes) {
          const bool hit = (s.voxel_kind == VoxelKind::kDiscrete)
                               ? (static_cast<double>(v) == c.value)
                               : (v >= c.value && v < c.value_max);
          if (hit) {
            cells[i] = static_cast<short>(c.material);
            break;
          }
        }
      }
    }
    const std::string path = (fs::path(dir) / (s.name + ".cells")).string();
    FILE* cf = std::fopen(path.c_str(), "wb");
    if (cf == nullptr) {
      std::printf("cannot write %s\n", path.c_str());
      return false;
    }
    std::fwrite(cells.data(), sizeof(short), n, cf);
    std::fclose(cf);
    std::printf("  wrote %s (%zu cells)\n", path.c_str(), n);

    // The class index per cell, when the classes are on layers of their own. Same walk as
    // above; only what is stored differs, because the layer of a cell is decided by its class
    // and not by its material - two classes may share a material and still rank differently.
    if (!ClassLayersOf(s).empty() && s.voxel_values.size() == n) {
      std::vector<short> classes(n, static_cast<short>(-1));
      for (std::size_t i = 0; i < n; ++i) {
        const float v = s.voxel_values[i];
        for (std::size_t ci = 0; ci < s.voxel_classes.size(); ++ci) {
          const VoxelClass& c = s.voxel_classes[ci];
          const bool hit = (s.voxel_kind == VoxelKind::kDiscrete)
                               ? (static_cast<double>(v) == c.value)
                               : (v >= c.value && v < c.value_max);
          if (hit) {
            classes[i] = static_cast<short>(ci);
            break;
          }
        }
      }
      const std::string cpath = (fs::path(dir) / (s.name + ".classes")).string();
      FILE* clf = std::fopen(cpath.c_str(), "wb");
      if (clf == nullptr) {
        std::printf("cannot write %s\n", cpath.c_str());
        return false;
      }
      std::fwrite(classes.data(), sizeof(short), n, clf);
      std::fclose(clf);
      std::printf("  wrote %s (%zu class indices)\n", cpath.c_str(), n);
    }
  }


  // ---- mesh triangles, one sidecar per import
  //
  // The triangles as the model holds them, widened to double: a count, then nine doubles per
  // triangle. The original CAD file is not referenced, because a project has to keep working
  // when that file is moved or the units it was in are forgotten - the scale and offset the
  // builder applied are baked in here.
  for (const Solid& s : model.solids) {
    if (s.shape != Shape::kImportedMesh) { continue; }
    const unsigned long long n = static_cast<unsigned long long>(s.mesh.size() / 9);
    const std::string path = (fs::path(dir) / (s.name + ".mesh")).string();
    FILE* mf = std::fopen(path.c_str(), "wb");
    if (mf == nullptr) {
      std::printf("cannot write %s\n", path.c_str());
      return false;
    }
    std::fwrite(&n, sizeof n, 1, mf);
    std::vector<double> tri(s.mesh.begin(), s.mesh.end());
    std::fwrite(tri.data(), sizeof(double), tri.size(), mf);
    std::fclose(mf);
    std::printf("  wrote %s (%llu triangles)\n", path.c_str(), n);
  }
  // ---- the editable document, so the builder can reopen it
  WriteModelFile(model, (fs::path(dir) / (app + ".model")).string());

  std::printf("wrote project %s (%s.cc, src/, include/, build.bat, run1.mac)\n", dir.c_str(),
              app.c_str());
  return true;
}

// ---------------------------------------------------------------- document serialisation
//
// A flat key-value text format, one record per line. Deliberately not a binary blob and not
// JSON-with-a-parser: it diffs, it can be hand-edited when something goes wrong, and adding a
// field later does not invalidate old files, because an unknown key is skipped and a missing
// key keeps its default.

bool WriteModelFile(const Model& m, const std::string& path) {
  std::ofstream f(path);
  if (!f) {
    std::printf("cannot write %s\n", path.c_str());
    return false;
  }
  f << "# g4gpu model, version 1\n";
  f << "model " << m.name << "\n";
  f << "physics " << m.physics.photoelectric << " " << m.physics.compton << " "
    << m.physics.rayleigh << " " << m.physics.pair_production << " " << 1
    << " " << m.physics.bremsstrahlung << " " << m.physics.annihilation << " "
    << m.physics.multiple_scattering << " " << m.physics.range_cut_mm << "\n";

  for (const Element& e : m.elements) {
    f << "element " << e.z << " " << e.a << " " << e.symbol << " " << e.name << "\n";
  }
  for (const Material& mm : m.materials) {
    f << "material " << mm.density << " " << static_cast<int>(mm.state) << " "
      << static_cast<int>(mm.fraction_kind) << " " << mm.mean_excitation_eV << " "
      << (mm.nist_name.empty() ? "-" : mm.nist_name) << " " << mm.name << "\n";
    for (const Component& c : mm.components) {
      f << "  component " << c.element << " " << c.amount << "\n";
    }
  }
  for (const Solid& s : m.solids) {
    f << "solid " << static_cast<int>(s.shape) << " " << s.layer << " " << s.material << " "
      << s.anchor << " " << s.operand_a << " " << s.operand_b << " " << s.visible << " "
      << s.wireframe << " " << s.r << " " << s.g << " " << s.b << " " << s.name << "\n";
    f << "  p";
    for (double v : s.p) { f << " " << v; }
    f << "\n";
    f << "  pos " << s.pos[0] << " " << s.pos[1] << " " << s.pos[2] << "\n";
    f << "  rot " << s.rot[0] << " " << s.rot[1] << " " << s.rot[2] << "\n";
    // Written as its own keyed line, and only when it is not the default, so that a model
    // saved by this version still loads in one that predates opacity - and one saved by an
    // older version loads here with everything opaque. The `solid` line itself cannot grow a
    // field: the name is last on it and is read to end of line.
    if (s.opacity != 1.0f) { f << "  solidopacity " << s.opacity << "\n"; }
    if (!s.sections.empty()) {
      f << "  sections " << s.sections.size();
      for (double v : s.sections) { f << " " << v; }
      f << "\n";
    }
    if (!s.source_file.empty()) { f << "  source_file " << s.source_file << "\n"; }
    if (!s.voxel_classes.empty()) {
      f << "  voxel " << static_cast<int>(s.voxel_kind) << " " << s.det_rows << " "
        << s.det_cols << "\n";
      for (const VoxelClass& v : s.voxel_classes) {
        f << "  voxelclass " << v.value << " " << v.value_max << " " << v.material << " "
          << v.r << " " << v.g << " " << v.b << " " << v.visible << " "
          << (v.label.empty() ? "-" : v.label) << "\n";
        if (v.opacity != 1.0f) { f << "  vcopacity " << v.opacity << "\n"; }
        if (v.layer != kInheritLayer) { f << "  vclayer " << v.layer << "\n"; }
      }
    }
  }
  for (const Source& s : m.sources) {
    f << "source " << static_cast<int>(s.kind) << " " << static_cast<int>(s.profile) << " "
      << s.pos[0] << " " << s.pos[1] << " " << s.pos[2] << " " << s.dir[0] << " " << s.dir[1]
      << " " << s.dir[2] << " " << s.half_x << " " << s.half_y << " " << s.half_z << " "
      << s.radius << " " << s.angular_spread_deg << " " << s.energy_MeV << " " << s.activity
      << " " << s.activity_in_curie << " " << s.enabled << " " << s.particle << " "
      << (s.spectrum_file.empty() ? "-" : s.spectrum_file) << " " << s.nuclide << " "
      << s.name << "\n";
    if (s.weight != 1.0) { f << "  weight " << s.weight << "\n"; }
  }
  for (const Scorer& sc : m.scorers) {
    f << "scorer " << static_cast<int>(sc.quantity) << " " << sc.solids.size();
    for (int v : sc.solids) { f << " " << v; }
    f << " " << sc.name << "\n";
    // Its own keyed line, and only when set, for the same reason solidopacity has one: the
    // scorer line ends with the name, which is read to end of line and so cannot grow a
    // field. A model written here still loads in a build that predates per-voxel scoring.
    if (sc.per_voxel) { f << "  pervoxel 1\n"; }
    if (sc.custom) { f << "  customscorer 1\n"; }
  }
  return true;
}

bool ReadModelFile(Model& m, const std::string& path) {
  std::ifstream f(path);
  if (!f) {
    std::printf("cannot read %s\n", path.c_str());
    return false;
  }
  m = Model{};
  std::string line;
  while (std::getline(f, line)) {
    std::istringstream in(line);
    std::string key;
    in >> key;
    if (key.empty() || key[0] == '#') { continue; }

    if (key == "model") {
      std::getline(in >> std::ws, m.name);
    } else if (key == "physics") {
      int a, b, c, d, e, g, h, i;
      in >> a >> b >> c >> d >> e >> g >> h >> i >> m.physics.range_cut_mm;
      m.physics.photoelectric = a;
      m.physics.compton = b;
      m.physics.rayleigh = c;
      m.physics.pair_production = d;
      (void)e;  // the ionisation field is gone; older files still carry the column
      m.physics.bremsstrahlung = g;
      m.physics.annihilation = h;
      m.physics.multiple_scattering = i;
    } else if (key == "element") {
      Element e;
      in >> e.z >> e.a >> e.symbol;
      std::getline(in >> std::ws, e.name);
      m.elements.push_back(e);
    } else if (key == "material") {
      Material mm;
      int st, fk;
      in >> mm.density >> st >> fk >> mm.mean_excitation_eV >> mm.nist_name;
      std::getline(in >> std::ws, mm.name);
      mm.state = static_cast<MatterState>(st);
      mm.fraction_kind = static_cast<Fraction>(fk);
      if (mm.nist_name == "-") { mm.nist_name.clear(); }
      m.materials.push_back(mm);
    } else if (key == "component") {
      if (!m.materials.empty()) {
        Component c;
        in >> c.element >> c.amount;
        m.materials.back().components.push_back(c);
      }
    } else if (key == "solid") {
      Solid s;
      int shape, vis, wf;
      in >> shape >> s.layer >> s.material >> s.anchor >> s.operand_a >> s.operand_b >> vis
         >> wf >> s.r >> s.g >> s.b;
      std::getline(in >> std::ws, s.name);
      s.shape = static_cast<Shape>(shape);
      s.visible = vis;
      s.wireframe = wf;
      m.solids.push_back(s);
    } else if (key == "p") {
      if (!m.solids.empty()) {
        for (double& v : m.solids.back().p) { in >> v; }
      }
    } else if (key == "pos") {
      if (!m.solids.empty()) {
        in >> m.solids.back().pos[0] >> m.solids.back().pos[1] >> m.solids.back().pos[2];
      }
    } else if (key == "rot") {
      if (!m.solids.empty()) {
        in >> m.solids.back().rot[0] >> m.solids.back().rot[1] >> m.solids.back().rot[2];
      }
    } else if (key == "solidopacity") {
      // Keyed sub-lines, because the `solid` and `source` lines end with a name read to end
      // of line and so cannot grow a field. A file written before these existed simply has
      // none, and the defaults - opaque, weight 1 - are what it meant.
      if (!m.solids.empty()) { in >> m.solids.back().opacity; }
    } else if (key == "vcopacity") {
      if (!m.solids.empty() && !m.solids.back().voxel_classes.empty()) {
        in >> m.solids.back().voxel_classes.back().opacity;
      }
    } else if (key == "vclayer") {
      if (!m.solids.empty() && !m.solids.back().voxel_classes.empty()) {
        in >> m.solids.back().voxel_classes.back().layer;
      }
    } else if (key == "weight") {
      if (!m.sources.empty()) { in >> m.sources.back().weight; }
    } else if (key == "sections") {
      if (!m.solids.empty()) {
        std::size_t n = 0;
        in >> n;
        m.solids.back().sections.resize(n);
        for (double& v : m.solids.back().sections) { in >> v; }
      }
    } else if (key == "source_file") {
      if (!m.solids.empty()) { std::getline(in >> std::ws, m.solids.back().source_file); }
    } else if (key == "voxel") {
      if (!m.solids.empty()) {
        int vk;
        in >> vk >> m.solids.back().det_rows >> m.solids.back().det_cols;
        m.solids.back().voxel_kind = static_cast<VoxelKind>(vk);
      }
    } else if (key == "voxelclass") {
      if (!m.solids.empty()) {
        VoxelClass v;
        int visible;
        in >> v.value >> v.value_max >> v.material >> v.r >> v.g >> v.b >> visible;
        std::getline(in >> std::ws, v.label);
        v.visible = visible;
        if (v.label == "-") { v.label.clear(); }
        m.solids.back().voxel_classes.push_back(v);
      }
    } else if (key == "source") {
      Source s;
      int kind, prof, curie, enabled;
      in >> kind >> prof >> s.pos[0] >> s.pos[1] >> s.pos[2] >> s.dir[0] >> s.dir[1]
         >> s.dir[2] >> s.half_x >> s.half_y >> s.half_z >> s.radius
         >> s.angular_spread_deg >> s.energy_MeV >> s.activity >> curie >> enabled
         >> s.particle >> s.spectrum_file >> s.nuclide;
      std::getline(in >> std::ws, s.name);
      s.kind = static_cast<SourceKind>(kind);
      s.profile = static_cast<BeamProfile>(prof);
      s.activity_in_curie = curie;
      s.enabled = enabled;
      if (s.spectrum_file == "-") { s.spectrum_file.clear(); }
      m.sources.push_back(s);
    } else if (key == "scorer") {
      Scorer sc;
      int q;
      std::size_t n = 0;
      in >> q >> n;
      sc.quantity = static_cast<ScoreQuantity>(q);
      sc.solids.resize(n);
      for (int& v : sc.solids) { in >> v; }
      std::getline(in >> std::ws, sc.name);
      m.scorers.push_back(sc);
    } else if (key == "pervoxel" && !m.scorers.empty()) {
      int v = 0;
      in >> v;
      m.scorers.back().per_voxel = (v != 0);
    } else if (key == "customscorer" && !m.scorers.empty()) {
      int v = 0;
      in >> v;
      m.scorers.back().custom = (v != 0);
    }
    // An unknown key is skipped: a file written by a newer builder still loads.
  }
  m.dirty = false;
  std::printf("loaded %s: %d solids, %d materials, %d sources\n", path.c_str(),
              static_cast<int>(m.solids.size()), static_cast<int>(m.materials.size()),
              static_cast<int>(m.sources.size()));
  return true;
}

}  // namespace g4gpu::builder
