// G4TwoBodyAngularDist, G4MultiBodyMomentumDist and the nineteen distribution objects they
// dispatch to.
//
// Transcribed from Geant4 11.1.1:
//   G4TwoBodyAngularDist::ChooseDist         (cascade/cascade/src/G4TwoBodyAngularDist.cc)
//   G4MultiBodyMomentumDist::ChooseDist      (cascade/cascade/src/G4MultiBodyMomentumDist.cc)
//   G4NumIntTwoBodyAngDst::GetCosTheta / Interpolate
//                                            (cascade/cascade/include/G4NumIntTwoBodyAngDst.icc)
//   G4ParamExpTwoBodyAngDst::GetCosTheta     (cascade/cascade/include/G4ParamExpTwoBodyAngDst.icc)
//   G4InuclParamAngDst::GetCosTheta          (cascade/cascade/src/G4InuclParamAngDst.cc)
//   G4InuclParamMomDst::GetMomentum          (cascade/cascade/src/G4InuclParamMomDst.cc)
//
// The tables are `src/data/bertini_angdst.hh`, generated by
// `tools/extract_bertini_angdst.pl`. This file is the code that samples them.
//
// ---------------------------------------------------------------------------------------------
// **ChooseDist's first test has nothing to do with angles.** Its opening lines are
//
//     if (fs==0 && kw==0) {
//       if (is == pro*pro || is == pro*neu || is == neu*neu) return nn3BodyDst;
//       else return hn3BodyDst;
//     }
//
// under a comment reading "TEMPORARY: Three-body distributions for hN/NN". A final state of 0
// is the sentinel G4CascadeFinalStateAlgorithm passes when it wants a THREE-BODY distribution
// rather than a two-body one, and the two objects it returns take `(ptype, ekin)` rather than
// `(ekin, pcm)` - a different signature reached through the same virtual. So the dispatcher has
// two return types in one function, and the caller has to know which it got. `choose_two_body`
// below returns a tagged union for that reason, rather than a pointer.
//
// **The order of the tests is the specification.** `is == pro*pro || is == neu*neu` returns the
// PP distribution before the hyperon block is reached, and `fs == is` gates the three elastic
// pion tests - so pi+p -> pi+p gets G4PipP2PipPAngDst while pi+p -> anything else falls through
// to the `kw == 2` strangeness test and then to the two hadron-nucleon elastic tables. Any
// reordering changes which table a reaction reads, and `ref/oracle/bertini_angchoice.csv` pins
// the whole map: every (is, fs, kw) the colliders can ask for, against the name of the object
// Geant4 returned.
//
// **The nn (NuclNucl) object is the HYPERON-nucleon distribution, not the neutron-neutron one.**
// It is constructed as `nnAngDst(new G4NuclNuclAngDst)` and returned only from the hyperon
// block; neutron-neutron elastic scattering gets `ppAngDst` (G4PP2PPAngDst) through
// `is == pro*pro || is == neu*neu`. The member name is the trap.
#ifndef G4GPU_BERTINI_ANGULAR_DIST_CUH
#define G4GPU_BERTINI_ANGULAR_DIST_CUH

#include <cmath>

#include "data/bertini_angdst.hh"
#include "physics/hadronic/bertini/cascade_interpolator.cuh"
#include "physics/hadronic/bertini/cascade_params.cuh"
#include "physics/hadronic/bertini/inucl_particle.cuh"

namespace g4gpu::physics::hadronic::bert {

/// Which family a chosen distribution belongs to, because the two families have different
/// sampling signatures and G4TwoBodyAngularDist returns both through one pointer.
enum class AngDstKind { kNone = 0, kNumInt, kParamExp, kParamAng3Body };

/// The index order in `data::bertini_numint_angdst()`, which is the order the extractor walks
/// the source files in. Named so that the dispatcher below reads like G4TwoBodyAngularDist's
/// constructor.
enum NumIntIndex {
  kNiGamP2NPip = 0, kNiGamP2PPi0, kNiNP2NP, kNiPP2PP,
  kNiPi0P2Pi0P, kNiPimP2Pi0N, kNiPimP2PimP, kNiPipP2PipP
};
enum ParamExpIndex { kPeGammaNucl = 0, kPeHadNElastic1, kPeHadNElastic2, kPeNuclNucl,
                     kPePiNInelastic };
enum ParamAngIndex { kPaHadNucl3Body = 0, kPaNuclNucl3Body };
enum ParamMomIndex { kPmHadNucl3Body = 0, kPmHadNucl4Body, kPmNuclNucl3Body, kPmNuclNucl4Body };

struct AngDstChoice {
  AngDstKind kind = AngDstKind::kNone;
  int index = -1;
};

/// G4TwoBodyAngularDist::ChooseDist(is, fs, kw), test for test and in order.
__host__ __device__ inline AngDstChoice choose_two_body_angdst(int is, int fs, int kw) {
  AngDstChoice c;
  // TEMPORARY (Geant4's word): the three-body distributions, reached with fs == 0 && kw == 0.
  if (fs == 0 && kw == 0) {
    c.kind = AngDstKind::kParamAng3Body;
    c.index = (is == kProton * kProton || is == kProton * kNeutron ||
               is == kNeutron * kNeutron) ? kPaNuclNucl3Body : kPaHadNucl3Body;
    return c;
  }
  // gamma-nucleon -> nucleon pi0
  if ((is == kPhoton * kProton && fs == kProton * kPionZero) ||
      (is == kPhoton * kNeutron && fs == kNeutron * kPionZero)) {
    c.kind = AngDstKind::kNumInt; c.index = kNiGamP2PPi0; return c;
  }
  // gamma-nucleon charge exchange
  if ((is == kPhoton * kProton && fs == kNeutron * kPionPlus) ||
      (is == kPhoton * kNeutron && fs == kProton * kPionMinus)) {
    c.kind = AngDstKind::kNumInt; c.index = kNiGamP2NPip; return c;
  }
  // pp and nn elastic - and NOTE this is G4PP2PPAngDst for BOTH, not the "nn" member
  if (is == kProton * kProton || is == kNeutron * kNeutron) {
    c.kind = AngDstKind::kNumInt; c.index = kNiPP2PP; return c;
  }
  // np and pn elastic
  if (is == kProton * kNeutron) { c.kind = AngDstKind::kNumInt; c.index = kNiNP2NP; return c; }
  // pi+ p and pi- n elastic
  if (fs == is && (is == kPionPlus * kProton || is == kPionMinus * kNeutron)) {
    c.kind = AngDstKind::kNumInt; c.index = kNiPipP2PipP; return c;
  }
  // pi- p and pi+ n elastic
  if (fs == is && (is == kPionMinus * kProton || is == kPionPlus * kNeutron)) {
    c.kind = AngDstKind::kNumInt; c.index = kNiPimP2PimP; return c;
  }
  // pi0 p and pi0 n elastic
  if (fs == is && (is == kPionZero * kProton || is == kPionZero * kNeutron)) {
    c.kind = AngDstKind::kNumInt; c.index = kNiPi0P2Pi0P; return c;
  }
  // the four pion charge exchanges
  if ((is == kPionMinus * kProton && fs == kPionZero * kNeutron) ||
      (is == kPionPlus * kNeutron && fs == kPionZero * kProton) ||
      (is == kPionZero * kProton && fs == kPionPlus * kNeutron) ||
      (is == kPionZero * kNeutron && fs == kPionMinus * kProton)) {
    c.kind = AngDstKind::kNumInt; c.index = kNiPimP2Pi0N; return c;
  }
  // hyperon-nucleon: this is where G4NuclNuclAngDst is used
  if (is == kProton * kLambda || is == kProton * kSigmaPlus || is == kProton * kSigmaZero ||
      is == kProton * kSigmaMinus || is == kProton * kXiZero || is == kProton * kXiMinus ||
      is == kProton * kOmegaMinus ||
      is == kNeutron * kLambda || is == kNeutron * kSigmaPlus || is == kNeutron * kSigmaZero ||
      is == kNeutron * kSigmaMinus || is == kNeutron * kXiZero || is == kNeutron * kXiMinus ||
      is == kNeutron * kOmegaMinus) {
    c.kind = AngDstKind::kParamExp; c.index = kPeNuclNucl; return c;
  }
  // gamma p -> K Y and isospin variants
  if (kw == 2 && (is == kProton * kPhoton || is == kNeutron * kPhoton)) {
    c.kind = AngDstKind::kParamExp; c.index = kPeGammaNucl; return c;
  }
  // pion-nucleon strangeness production
  if (kw == 2) { c.kind = AngDstKind::kParamExp; c.index = kPePiNInelastic; return c; }
  // gamma p, K+ p, K0bar p, gamma n, K- n, K0 n
  if (is == kProton * kPhoton || is == kProton * kKaonPlus || is == kProton * kKaonZeroBar ||
      is == kNeutron * kPhoton || is == kNeutron * kKaonMinus || is == kNeutron * kKaonZero) {
    c.kind = AngDstKind::kParamExp; c.index = kPeHadNElastic1; return c;
  }
  // K- p, K0bar n, K+ n, K0 p
  if (is == kProton * kKaonMinus || is == kProton * kKaonZero ||
      is == kNeutron * kKaonPlus || is == kNeutron * kKaonZeroBar) {
    c.kind = AngDstKind::kParamExp; c.index = kPeHadNElastic2; return c;
  }
  return c;   // ChooseDist returns 0: an invalid interaction
}

/// G4MultiBodyMomentumDist::ChooseDist(is, mult). The `use3BodyMom` branch is the one Vladimir
/// Uzhinsky's 2011 comment says was removed, kept behind the flag: with the dumped default
/// (false) a three-body final state gets the FOUR-body generator, which is why the four-body
/// tables carry the whole multiplicity range.
__host__ __device__ inline int choose_multibody_momdst(int is, int mult,
                                                       const CascadeParams& par) {
  const bool nn = (is == kProton * kProton || is == kProton * kNeutron ||
                   is == kNeutron * kNeutron);
  if (nn) {
    if (par.use_3body_mom && mult == 3) { return kPmNuclNucl3Body; }
    return kPmNuclNucl4Body;
  }
  if (par.use_3body_mom && mult == 3) { return kPmHadNucl3Body; }
  return kPmHadNucl4Body;
}

// =============================================================================================
// G4NumIntTwoBodyAngDst::GetCosTheta
// =============================================================================================

/// The CDF inversion. Two things are worth spelling out because both look like bugs and are not:
///
///   * the uniform is drawn BEFORE the energy branch, so the number of deviates is one either
///     way and the random stream does not depend on which arm ran;
///   * `Interpolate` loops `for j in 1..nDists` and `break`s on the first `ekin < labKE[j]`,
///     leaving `angDist` untouched if no j satisfies it. That cannot happen here because the
///     caller already tested `ekin < labKE[nDists-1]`, but the buffer is a MUTABLE MEMBER in
///     Geant4, so a failed interpolation would sample the previous call's distribution. Here the
///     buffer is a local and the guard is explicit.
///
/// Above the last tabulated energy the table is abandoned for
/// `costh = log(1 - u(1 - exp(2s)))/s - 1` with `s = 2*tcoeff*pcm^2`, which is an exponential in
/// t. Note `s` grows with pcm^2, so at a few GeV/c the distribution is extremely forward and the
/// logarithm's argument is `1 - u` to within rounding.
template <typename Rng>
__host__ __device__ inline double numint_cos_theta(const data::BertiniNumIntAngDst& d,
                                                   double ekin, double pcm, Rng& rng) {
  const double* base = data::bertini_numint_data();
  const double* ke = base + d.ke_off;
  const double* cosb = base + d.cos_off;
  const double* tab = base + d.tab_off;
  double costh = 1.0;
  double slope = 1.0;
  const double xrand = rng.uniform();
  if (ekin < ke[d.nke - 1]) {
    // Interpolate() between the bracketing energies.
    double dist[19];              // kMaxAngleBins; every table in 11.1.1 has 19
    bool filled = false;
    for (int j = 1; j < d.nke; ++j) {
      if (ekin >= ke[j]) { continue; }
      const double frac = (ekin - ke[j - 1]) / (ke[j] - ke[j - 1]);
      for (int i = 0; i < d.nang; ++i) {
        dist[i] = (1.0 - frac) * tab[(j - 1) * d.nang + i] +
                  frac * tab[j * d.nang + i];
      }
      filled = true;
      break;
    }
    if (!filled) { return 1.0; }   // unreachable under the caller's own test; see above
    for (int i = 1; i < d.nang; ++i) {
      if (xrand < dist[i]) {
        slope = (cosb[i] - cosb[i - 1]) / (dist[i] - dist[i - 1]);
        costh = (xrand - dist[i - 1]) * slope + cosb[i - 1];
        break;
      }
    }
  } else {
    slope = 2.0 * d.tcoeff * pcm * pcm;
    costh = std::log(1.0 - xrand * (1.0 - std::exp(2.0 * slope))) /
            slope - 1.0;
  }
  return costh;
}

// =============================================================================================
// G4ParamExpTwoBodyAngDst::GetCosTheta
// =============================================================================================

/// Four interpolations, a small/large angle choice, then an inverted exponential.
///
/// The interpolator here is G4CascadeInterpolator with extrapolation ON, so an energy above the
/// last bin extrapolates the parameters linearly rather than clamping - and `pCos` and `pFrac`
/// are then clamped to their physical ranges afterwards, which is what makes the extrapolation
/// safe. `pA` and `pC` are NOT clamped, so a high-energy extrapolation can hand `term1` either
/// sign; the two guards below (`|term1| < 1e-7` and `term1 > DBL_MAX_EXP`) are Geant4's.
///
/// `DBL_MAX_EXP` is 1024, an *exponent*, compared against `term1`, a slope - comparing a value
/// against an exponent bound is a units error in Geant4, and it is reproduced because it is what
/// runs. The guard it was meant to be would have been `term1 > 709` (log(DBL_MAX)); at 1024 the
/// `G4Exp(-2*term1)` below is already exactly 0 and the arithmetic degrades gracefully, so the
/// error changes nothing. Recorded rather than corrected.
template <typename Rng>
__host__ __device__ inline double paramexp_cos_theta(const data::BertiniParamExpAngDst& d,
                                                     double ekin, double pcm, Rng& rng) {
  const double* base = data::bertini_paramexp_data();
  const double pos = interp_get_bin(ekin, base + d.ke_off, d.nke);
  double pA = interp_apply(pos, base + d.a_off, d.nke);
  double pC = interp_apply(pos, base + d.c_off, d.nke);
  double pCos = interp_apply(pos, base + d.cos_off, d.nke);
  double pFrac = interp_apply(pos, base + d.frac_off, d.nke);
  pCos = (pCos > 1.0) ? 1.0 : (pCos < -1.0) ? -1.0 : pCos;
  pFrac = (pFrac > 1.0) ? 1.0 : (pFrac < 0.0) ? 0.0 : pFrac;

  const bool small_angle = (rng.uniform() < pFrac);
  const double term1 = 2.0 * pcm * pcm * (small_angle ? pA : pC);
  if (std::fabs(term1) < 1e-7) { return 1.0; }
  if (term1 > 1024.0) { return 1.0; }          // DBL_MAX_EXP, as written
  const double term2 = std::exp(-2.0 * term1);
  const double rand_scale =
      (std::exp(-term1 * (1.0 - pCos)) - term2) / (1.0 - term2);
  const double u = rng.uniform();
  const double rand_val = small_angle ? ((1.0 - rand_scale) * u + rand_scale)
                                      : (rand_scale * u);
  return 1.0 + std::log(rand_val * (1.0 - term2) + term2) / term1;
}

// =============================================================================================
// G4InuclParamAngDst::GetCosTheta and G4InuclParamMomDst::GetMomentum
// =============================================================================================

/// G4InuclParamAngDst::GetCosTheta(ptype, ekin). A rejection loop around
/// `randomInuclPowers` until the result lands in [0, 1], up to 100 tries, and then a FLAT
/// distribution if it never does - Geant4's comment says "Parametrizations aren't properly
/// bounded", and the flat fallback is reached for real at high energy.
///
/// `J` selects the coefficient block by whether the OUTGOING particle is a nucleon, so `ptype`
/// is the ejectile's type, not the projectile's.
template <typename Rng>
__host__ __device__ inline double paramang_cos_theta(const data::BertiniParamAngDst& d,
                                                     int ptype, double ekin, Rng& rng,
                                                     bool& used_flat) {
  const int J = (ptype == kProton || ptype == kNeutron) ? 0 : 1;
  const double* ab = data::bertini_paramang_data() + d.ab_off;
  double coeff[4][4];
  for (int i = 0; i < 4; ++i) {
    for (int k = 0; k < 4; ++k) { coeff[i][k] = ab[J * 16 + i * 4 + k]; }
  }
  const int itry_max = 100;
  double spow = -999.0;
  int itry = 0;
  while ((spow < 0.0 || spow > 1.0) && itry < itry_max) {
    ++itry;
    spow = inucl_random_powers(ekin, coeff, rng);
  }
  used_flat = (itry == itry_max);
  if (used_flat) { spow = rng.uniform(); }
  return 2.0 * spow - 1.0;
}

/// G4InuclParamMomDst::GetMomentum(ptype, ekin). One `randomInuclPowers` and a quadratic in
/// ekin, multiplied; `fabs` at the end because the product can come out negative.
///
/// There is NO rejection loop here, unlike the angular form - so `Spow` is used whatever it is,
/// including outside [0, 1], and `sqrt(S)*(PR + (1-PQ)S^4)` can be anything. That asymmetry
/// between the two classes is in Geant4 and it is why the momentum generator needs no
/// `used_flat`.
template <typename Rng>
__host__ __device__ inline double parammom_momentum(const data::BertiniParamMomDst& d,
                                                    int ptype, double ekin, Rng& rng) {
  const int JK = (ptype == kProton || ptype == kNeutron) ? 0 : 1;
  const double* pq = data::bertini_parammom_data() + d.pqpr_off;
  const double* ps_c = data::bertini_parammom_data() + d.ps_off;
  double coeff[4][4];
  for (int i = 0; i < 4; ++i) {
    for (int k = 0; k < 4; ++k) { coeff[i][k] = pq[JK * 16 + i * 4 + k]; }
  }
  const double spow = inucl_random_powers(ekin, coeff, rng);
  double ps = 0.0;
  for (int im = 0; im < 3; ++im) {
    ps += ps_c[JK * 3 + im] * g4pow_n(ekin, im);

  }
  return std::fabs(ps * spow);
}

}  // namespace g4gpu::physics::hadronic::bert

#endif  // G4GPU_BERTINI_ANGULAR_DIST_CUH
