// G4CascadeChannelTables and everything under it: the 34 two-body channel tables Bertini's
// colliders look every cross section, multiplicity and final state up in.
//
// Transcribed from Geant4 11.1.1:
//   G4CascadeChannelTables::GetTable / FindTable  (cascade/cascade/src/G4CascadeChannelTables.cc)
//   G4CascadeFunctions::getCrossSection / getCrossSectionSum / getMultiplicity /
//     getOutgoingParticleTypes                    (cascade/cascade/include/G4CascadeFunctions.icc)
//   G4CascadeSampler::findCrossSection / findMultiplicity / findFinalStateIndex /
//     fillSigmaBuffer / sampleFlat                (cascade/cascade/include/G4CascadeSampler.icc)
//   G4CascadeInterpolator::getBin / interpolate   (cascade/cascade/include/G4CascadeInterpolator.icc)
//   G4CascadeData::initialize                     (cascade/cascade/include/G4CascadeData.icc)
//   G4CascadeNNChannel / G4CascadeNPChannel / G4CascadePPChannel::findCrossSection
//                                                 (their own .cc files)
//   G4PionNucSampler / G4KaonSampler / G4KaonHypSampler  (their .cc files: the bin edges)
//
// The data is `src/data/bertini_channels.hh`, generated by
// `tools/extract_bertini_channels.pl`: 185,970 cross sections, 42,890 final-state codes and the
// 9,472 values G4CascadeData::initialize derives from them. This file is the code that reads it.
//
// ---------------------------------------------------------------------------------------------
// Four things about these tables that a reading of the class does not show.
//
// **1. `getCrossSection` and `getCrossSectionSum` are different numbers for eight channels and
// the same number for twenty-six.** `getCrossSection` interpolates `tot`, `getCrossSectionSum`
// interpolates `sum`, and `tot` IS `sum` - the same array, by reference - unless the channel's
// constructor was given a measured inclusive array. Eight were: gamma-N, the three pion-nucleon
// pairs, NN, NP, PP and mu-p. For those the measured total is LARGER than the sum of the
// exclusive channels, and `getMultiplicity` uses the shortfall:
//
//     if (&data.sum != &data.tot) {
//       if (G4UniformRand() > summed/total) return data.maxMultiplicity();
//     }
//
// so a fraction `1 - sum/tot` of collisions are forced to the highest multiplicity the table
// has, and the other twenty-six channels never take that branch **and never draw that deviate**.
// The random stream therefore depends on which constructor a channel used. `tot_off < 0` in the
// generated table is what records it.
//
// **2. `findFinalStateIndex` returns an ABSOLUTE index on one path and a RELATIVE one on the
// other.** Its body is
//
//     G4int start = index[mult-2], stop = index[mult-1];
//     if (stop-start <= 1) return start;          // absolute
//     fillSigmaBuffer(ke, xsec, start, stop);
//     return sampleFlat();                        // relative, 0..(stop-start-1)
//
// and `getOutgoingParticleTypes` then indexes the PER-MULTIPLICITY array `xMbfs[channel]` with
// the result. The two agree only when `start == 0`, which is multiplicity 2 and nothing else. Any
// channel with exactly one final state at a multiplicity above 2 reads out of bounds, and in
// 11.1.1 exactly one does: G4CascadeMuMinusPChannel is `G4CascadeData<30,1,1,1,1,1,1,1,1>`.
// `outgoing_particle_types` below returns `ChannelRefusal::kSingleChannelAboveMult2` for it
// rather than reproducing the out-of-bounds read. docs/RISK.md V119.
//
// **3. `sampleFlat` returns 0 when the cumulative walk falls off the end**, with Geant4's own
// question mark beside it ("Is this right? Shouldn't it return maximum, not minimum?"). It is
// reachable: `fsum = total * u` and then `if (fsum < partialSum) return i` - at u very close to 1
// the accumulated partial sum can round just below `fsum` and the loop exits. Reproduced, not
// corrected, and the branch is counted so a test can see it fire.
//
// **4. NN, NP and PP replace the whole 0-10 MeV bin with a closed form, and they select it by
// comparing ARRAY CONTENTS.** The override is
//
//     if (ke < 0.01 && (std::equal(xsec, xsec+30, npTotXSec) ||
//                       std::equal(xsec, xsec+30, npCrossSections[0])))
//
// - not a pointer comparison. So it fires for `tot` and for the elastic channel's own row, and
// it would fire for any other array that happened to hold the same 30 values. Below 10 MeV those
// two lookups return Stepanov's function and every other lookup on the same channel returns the
// interpolated table. `stepanov_kind` below carries which of the two arrays is being asked for,
// because the caller knows and a content comparison on the device would be 30 loads per lookup.
#ifndef G4GPU_BERTINI_CHANNEL_TABLES_CUH
#define G4GPU_BERTINI_CHANNEL_TABLES_CUH

#include <cmath>

#include "data/bertini_channels.hh"
#include "physics/hadronic/bertini/cascade_interpolator.cuh"
#include "physics/hadronic/bertini/inucl_particle.cuh"

namespace g4gpu::physics::hadronic::bert {

/// The most final states one channel can have at one multiplicity, over all 34 tables: 96, in
/// G4CascadeKminusPChannel's multiplicity-7 block. `sigmaBuf` is a std::vector in Geant4 and a
/// fixed array here, so the bound is asserted rather than assumed - `kMaxChannelsPerMult` is
/// checked against the generated table in tests/test_bertini_data.cu.
constexpr int kMaxChannelsPerMult = 96;

/// The most particles one final state can have: 9.
constexpr int kMaxFinalStateSize = 9;

enum class ChannelRefusal {
  kNone = 0,
  kNoTable,                        ///< GetTable returned null for this initial state
  kSingleChannelAboveMult2,        ///< see note 2 in the header - the mu- p out-of-bounds read
  kMultiplicityAboveMax,           ///< getOutgoingParticleTypes' own "Illegal multiplicity"
  kBufferTooSmall                  ///< kMaxChannelsPerMult exceeded; never in 11.1.1's data
};

// =============================================================================================
// A channel table, as a view over the generated data
// =============================================================================================

/// Which of the three arrays a caller is asking `find_cross_section` for. Only NN, NP and PP
/// care, and they care because their override identifies its two special arrays by CONTENT.
enum class XsArray { kTot = 0, kSum, kInelastic, kMultiplicity, kChannel };

struct ChannelTable {
  const data::BertiniChannel* def = nullptr;
  int slot = -1;                     ///< index into data::bertini_channels(), so that the host
                                     ///< can find the name in kBertiniChannelNames
  const double* bins = nullptr;
  const double* xs = nullptr;        ///< [nxs][ne] for this channel
  const double* tot = nullptr;       ///< [ne], or `sum` when the channel has no measured total
  const double* mult = nullptr;      ///< [n_mult][ne]
  const double* sum = nullptr;       ///< [ne]
  const double* inelastic = nullptr; ///< [ne]
  const signed char* fs[8] = {nullptr, nullptr, nullptr, nullptr,
                              nullptr, nullptr, nullptr, nullptr};
  bool has_measured_total = false;   ///< `&data.sum != &data.tot`
  bool stepanov = false;             ///< NN, NP or PP: the 0-10 MeV closed form
  double stepanov_a = 0.0;           ///< the numerator of the 1/ke term
  double stepanov_b = 0.0;
  double stepanov_c = 0.0;
  double stepanov_num = 0.0;         ///< 1.92 for NP, 4.0 for NN and PP
  __host__ __device__ bool valid() const { return def != nullptr; }
  __host__ __device__ int ne() const { return def->ne; }
  __host__ __device__ int n_mult() const { return def->n_mult; }
  __host__ __device__ int max_multiplicity() const { return def->n_mult + 1; }
};

/// G4CascadeChannelTables::GetTable(initialState). A linear scan of 34 entries, which is what
/// Geant4's std::map lookup amounts to and is cheaper on a device than any tree.
__host__ __device__ inline ChannelTable channel_table(int initial_state) {
  ChannelTable t;
  const data::BertiniChannel* all = data::bertini_channels();
  for (int i = 0; i < data::kBertiniChannels; ++i) {
    if (all[i].initial_state != initial_state) { continue; }
    const data::BertiniChannel& d = all[i];
    t.def = &d;
    t.slot = i;
    t.bins = (d.sampler == 0) ? data::bertini_bins_pionnuc()
           : (d.sampler == 1) ? data::bertini_bins_kaon()
                              : data::bertini_bins_kaonhyp();
    t.xs = data::bertini_channel_xs() + d.xs_off;
    const double* dv = data::bertini_channel_derived() + d.deriv_off;
    t.mult = dv;
    t.sum = dv + d.n_mult * d.ne;
    t.inelastic = t.sum + d.ne;
    t.has_measured_total = (d.tot_off >= 0);
    t.tot = t.has_measured_total ? (data::bertini_channel_tot() + d.tot_off) : t.sum;
    for (int m = 0; m < 8; ++m) {
      t.fs[m] = (d.fs_off[m] >= 0) ? (data::bertini_channel_fs() + d.fs_off[m]) : nullptr;
    }
    // The three nucleon-nucleon channels override findCrossSection below 10 MeV. The constants
    // are per channel: NP uses (3.0885, 0.0011748, 5.3107) with 1.92, NN and PP use
    // (9.0692, 0.0050574, 6.9466) with 4.0 - which are G4InuclSpecialFunctions::csPN's and
    // csNN's low-energy coefficients written a second time, in different units.
    if (initial_state == kNeutron * kProton) {
      t.stepanov = true;
      t.stepanov_a = 3.0885; t.stepanov_b = 0.0011748; t.stepanov_c = 5.3107;
      t.stepanov_num = 1.92;
    } else if (initial_state == kNeutron * kNeutron || initial_state == kProton * kProton) {
      t.stepanov = true;
      t.stepanov_a = 9.0692; t.stepanov_b = 0.0050574; t.stepanov_c = 6.9466;
      t.stepanov_num = 4.0;
    }
    return t;
  }
  return t;   // def == nullptr: no table, which is what FindTable's map miss returns
}

/// G4CascadeSampler::findCrossSection, including the NN/NP/PP override.
///
/// `which` says which array is being read, because the override's `std::equal` test is a
/// content comparison against `tot` and against `crossSections[0]` - and `crossSections[0]` is
/// the elastic channel's row for all three of these tables (their multiplicity-2 block has one
/// entry, `{pro,neu}` / `{neu,neu}` / `{pro,pro}`, and it is the elastic one). So the two arrays
/// the override fires for are exactly "the total" and "the elastic channel", and a caller always
/// knows which of those it is asking for.
__host__ __device__ inline double find_cross_section(const ChannelTable& t, double ke,
                                                     XsArray which, int chan_index = -1) {
  if (t.stepanov && ke < 0.01) {
    const bool is_elastic_row = (which == XsArray::kChannel && chan_index == t.def->elastic_chan);
    if (which == XsArray::kTot || is_elastic_row) {
      const double kemin = t.stepanov_num / t.tot[0];
      if (ke > 0.001) { return (t.stepanov_a - t.stepanov_b / ke) / ke + t.stepanov_c; }
      if (ke > kemin) { return t.stepanov_num / ke; }
      return t.tot[0];
    }
  }
  const double* y = nullptr;
  switch (which) {
    case XsArray::kTot: y = t.tot; break;
    case XsArray::kSum: y = t.sum; break;
    case XsArray::kInelastic: y = t.inelastic; break;
    case XsArray::kMultiplicity: y = t.mult + chan_index * t.def->ne; break;
    case XsArray::kChannel: y = t.xs + chan_index * t.def->ne; break;
  }
  return interp_value(ke, t.bins, y, t.def->ne);
}

/// G4CascadeFunctions::getCrossSection - the inclusive total.
__host__ __device__ inline double channel_cross_section(const ChannelTable& t, double ke) {
  return find_cross_section(t, ke, XsArray::kTot);
}

/// G4CascadeFunctions::getCrossSectionSum - the sum of the exclusive channels.
///
/// Note that for NN, NP and PP below 10 MeV this does NOT get Stepanov's form: `sum` is neither
// `tot` nor `crossSections[0]`, so `std::equal` fails on both and the base interpolator runs.
/// The two therefore disagree by a large factor there (the tabulated `tot[0]` is 20360 mb for NP
/// against a summed 20360 as well, but at 5 MeV the closed form gives 613 mb against the table's
/// linear interpolation between 20360 and 302) - and `getMultiplicity` divides one by the other.
__host__ __device__ inline double channel_cross_section_sum(const ChannelTable& t, double ke) {
  return find_cross_section(t, ke, XsArray::kSum);
}

/// G4CascadeSampler::sampleFlat over a filled buffer. Returns the index, and sets `fell_off`
/// when the cumulative walk ran past the end - the branch Geant4's own comment questions.
__host__ __device__ inline int sample_flat(const double* sigma, int n, double u,
                                          bool& fell_off) {
  fell_off = false;
  if (n <= 1) { return 0; }
  double fsum = 0.0;
  for (int i = 0; i < n; ++i) { fsum += sigma[i]; }
  fsum *= u;
  double partial = 0.0;
  for (int i = 0; i < n; ++i) {
    partial += sigma[i];
    if (fsum < partial) { return i; }
  }
  fell_off = true;
  return 0;
}

/// G4CascadeFunctions::getMultiplicity.
///
/// Two deviates or one, depending on the channel: the summed/total comparison is only made when
/// the table carries a measured inclusive cross section, and `findMultiplicity` itself draws one
/// only when the buffer has more than one entry - which it always does here, since every channel
/// has at least six multiplicities.
template <typename Rng>
__host__ __device__ inline int channel_multiplicity(const ChannelTable& t, double ke, Rng& rng,
                                                    bool& fell_off) {
  fell_off = false;
  if (t.has_measured_total) {
    const double summed = find_cross_section(t, ke, XsArray::kSum);
    const double total = find_cross_section(t, ke, XsArray::kTot);
    if (rng.uniform() > summed / total) { return t.max_multiplicity(); }
  }
  double buf[8];
  const int nm = t.def->n_mult;
  const double pos = interp_get_bin(ke, t.bins, t.def->ne);
  for (int im = 0; im < nm; ++im) {
    buf[im] = interp_apply(pos, t.mult + im * t.def->ne, t.def->ne);
  }
  return sample_flat(buf, nm, rng.uniform(), fell_off) + 2;
}

/// G4CascadeSampler::findFinalStateIndex + G4CascadeFunctions::getOutgoingParticleTypes.
///
/// Writes `mult` type codes into `kinds` and returns the refusal, if any. The
/// `stop - start <= 1` arm is where Geant4 mixes an absolute index into a per-multiplicity
/// array; this refuses instead, for the one channel where the two differ (see note 2).
/// `sigma_buf` must have room for `kMaxChannelsPerMult` doubles and comes from the caller's
/// workspace, not from this function's stack.
///
/// That is not style. Written with a local `double buf[96]`, this function gave
/// `bertini_tables_probe` a **992-byte stack frame** under `-Xptxas -v`; with the buffer passed
/// in it is 224 bytes. A cascade at 5 GeV has hundreds of particles in flight and every one of
/// them calls this, so 768 bytes of per-thread local memory is 768 bytes of L1 that the nucleus
/// model's tables wanted - and `sigmaBuf` is a `std::vector` data member in Geant4 for the same
/// reason, reused across calls rather than reallocated.
template <typename Rng>
__host__ __device__ inline ChannelRefusal outgoing_particle_types(
    const ChannelTable& t, int mult, double ke, Rng& rng, int* kinds, int& out_channel,
    bool& fell_off, double* sigma_buf) {
  fell_off = false;
  out_channel = -1;
  if (!t.valid()) { return ChannelRefusal::kNoTable; }
  const int max_mult = t.max_multiplicity();
  if (mult > max_mult) {
    // Geant4 prints " Illegal multiplicity" and CLAMPS to the maximum rather than failing, so
    // the clamp is reproduced and the refusal is reported alongside it: the caller gets a
    // usable final state and a flag saying its multiplicity was not the one requested.
    mult = max_mult;
  }
  if (mult < 2) { return ChannelRefusal::kMultiplicityAboveMax; }

  const int start = t.def->index[mult - 2];
  const int stop = t.def->index[mult - 1];
  int channel;
  if (stop - start <= 1) {
    if (start != 0) { return ChannelRefusal::kSingleChannelAboveMult2; }
    channel = start;
  } else {
    if (stop - start > kMaxChannelsPerMult) { return ChannelRefusal::kBufferTooSmall; }
    const double pos = interp_get_bin(ke, t.bins, t.def->ne);
    for (int i = start; i < stop; ++i) {
      sigma_buf[i - start] = interp_apply(pos, t.xs + i * t.def->ne, t.def->ne);
    }
    channel = sample_flat(sigma_buf, stop - start, rng.uniform(), fell_off);
  }

  const signed char* block = t.fs[mult - 2];
  if (block == nullptr) { return ChannelRefusal::kMultiplicityAboveMax; }
  for (int j = 0; j < mult; ++j) { kinds[j] = block[channel * mult + j]; }
  out_channel = channel;
  return ChannelRefusal::kNone;
}

}  // namespace g4gpu::physics::hadronic::bert

#endif  // G4GPU_BERTINI_CHANNEL_TABLES_CUH
