// G4DecayKineticTracks - decay every short-lived track in a list until none is left.
//
// **This is a CONTRACT HEADER.** It is the one file a caller outside `bic/` includes to get the
// decay engine, in the same shape `bic/nucleus/nucleus_model.cuh` has: plain structs in, plain
// structs out, no knowledge of which model is asking. Everything under `bic/im_r/` is this
// package's private business and nothing outside `bic/` should include it.
//
// Transcribed from G4DecayKineticTracks.{hh,cc} (hadronic/util, 11.1.1) over
// `im_r/decay.cuh`'s `G4KineticTrack::Decay`.
//
// ## WHO CALLS IT
//
// Two entry points in Geant4, and they are the same three lines (docs/HADRONIC_PLAN.md section
// 9.2, written by P11c so that this is built once):
//
//     G4DecayStrongResonances::Propagate(secondaries, nucleus)        [hadronic/util]
//         -> G4DecayKineticTracks decay(secondaries);   // changes the list IN SITU
//         -> then copies every survivor into a G4ReactionProduct
//
//     G4GeneratorPrecompoundInterface::Propagate / PropagateNuclNucl  [binary_cascade]
//         -> G4DecayKineticTracks decay(secondaries);   // the FIRST line of both
//         -> then the capture loop and the residual
//
// The Fritiof string model reaches the first; the binary cascade reaches the second. P11c
// measured what the absence of this engine costs FTFP: of a 96-point generality sweep, 52 points
// refuse and **all 52 are this one refusal**, along with 80% of ion events and 32% of sub-GeV
// anti-nucleon ones. 14.3% of all FTFP tracks are short-lived and 72.6% of its events carry at
// least one.
//
// ## THE SPECIES SET IS THE UNION, AND IT IS A CLOSURE
//
// `im_r/decay_tables.hh` is generated by `tools/extract_bic_decay.pl` from
// `ref/oracle/bic_imr_decaytable.csv`, which `ref/dump/dump_bic.cc` fills out of Geant4's own
// `G4DecayTable` objects - never from memory, one row per channel. Its seed set is the binary
// cascade's production set (both nucleons, the three pions, all 25 resonance multiplets in every
// charge state) PLUS FTFP's 27 short-lived species from section 9.3, and it is closed under "is a
// decay daughter of". That closure is 126 species and 638 channels.
//
// Widening it is one line: add the codes to `kSeeds` in `write_imr_decay`. Do NOT try to seed it
// from `G4ParticleTable` with everything whose `IsShortLived()` is true - it reaches the
// anti-baryon resonances and the dumper dies part-way through `anti_N(2250)0`, mid-`fprintf`,
// with nothing on stderr.
//
// ## WHAT THE CALLER OWNS
//
//   * the array and its capacity. The list GROWS - a Delta becomes two tracks - and the engine
//     appends in place, so `capacity` must have room. `KineticDecayRefusal::list_full` is set and
//     the decay that would have overflowed is abandoned, leaving the parent in the list.
//   * the random engine, as an object with `double uniform()`. The draw ORDER is part of the
//     contract: this engine consumes exactly what Geant4 consumes, in the same order, so a caller
//     that shares a stream with the rest of an event stays in step.
//   * the PDG codes. A code the table does not carry sets `unknown_species` and leaves that track
//     alone rather than guessing.
//
// ## WHAT IT DOES NOT DO
//
//   * it does not touch a track that is not short-lived, and `IsShortLived` here is Geant4's own
//     flag, carried in the table, not a lifetime cut;
//   * it does not remove a short-lived track whose `Decay()` returns nothing. Geant4 leaves such
//     a track in the list - the null-slot bookkeeping only runs when daughters came back - so a
//     resonance with a zero total actual width survives the pass unchanged. So does this.
#ifndef G4GPU_BIC_KINETIC_DECAY_CUH
#define G4GPU_BIC_KINETIC_DECAY_CUH

#include <cmath>

#include "physics/hadronic/bic/im_r/decay.cuh"

namespace g4gpu::bic {

/// One track in and out of the engine. The three `parent_resonance*`/`creator_model_id` fields
/// are Geant4's bookkeeping: it sets them on every daughter and nothing in QBBC's scoring reads
/// them, so they are carried rather than reproduced for their effect.
struct DecayTrack {
  int pdg = 0;
  imr::LorentzVector momentum;
  deex::Vec3d position{0.0, 0.0, 0.0};
  double formation_time = 0.0;
  int creator_model_id = -1;
  int parent_resonance_pdg = 0;
  int parent_resonance_id = 0;
};

/// What the pass could not do. None of these is fatal: each leaves the track it concerns in the
/// list, untouched, and the pass carries on.
struct KineticDecayRefusal {
  bool list_full = false;          ///< a decay's daughters would not fit in `capacity`
  bool unknown_species = false;    ///< a PDG code the generated table does not carry
  bool too_many_daughters = false; ///< a channel with more than four daughters
  bool below_threshold = false;    ///< Pmx would have thrown after 10,000 resamplings
  bool phase_space_failed = false; ///< a rejection loop gave up
  int refused_pdg = 0;
  __host__ __device__ bool any() const {
    return list_full || unknown_species || too_many_daughters || below_threshold ||
           phase_space_failed;
  }
};

/// Whether the engine will decay a track with this code: `G4ParticleDefinition::IsShortLived`,
/// from the generated table. Returns false for a code the table does not carry.
__host__ __device__ inline bool kinetic_decay_is_short_lived(int pdg) {
  const int i = imr::decay_species_index(pdg);
  return (i >= 0) && (imr::decay_species_shortlived()[i] != 0);
}

/// Whether the generated table carries this code at all.
__host__ __device__ inline bool kinetic_decay_knows(int pdg) {
  return imr::decay_species_index(pdg) >= 0;
}

/// The number of decay channels the engine needs room for - `kDecayMaxChannels` is the bound over
/// every species in the table, so a caller sizing a scratch array can use it directly.
inline constexpr int kKineticDecayMaxChannels = imr::kDecayMaxChannels;

/// `G4KineticTrack::SampleResidualLifetime` for one track, for a caller that schedules decays in
/// time rather than doing them all at once - which is what `G4BCDecay` does inside the cascade.
/// Returns a negative number and sets `unknown_species` for a code the table does not carry.
template <typename Rng>
__host__ __device__ inline double kinetic_decay_residual_lifetime(int pdg,
                                                                  const imr::LorentzVector& p,
                                                                  Rng& rng,
                                                                  KineticDecayRefusal& ref) {
  const double actual_mass = std::sqrt(std::fabs(p.e * p.e - g4gpu::mag2(p.v)));
  double widths[kKineticDecayMaxChannels];
  imr::DecayRefusal dref;
  const int n = imr::kinetic_track_actual_widths(pdg, actual_mass, widths,
                                                 kKineticDecayMaxChannels, dref);
  if (n < 0) {
    ref.unknown_species = dref.unknown_species;
    ref.refused_pdg = dref.refused_pdg;
    return -1.0;
  }
  const double total = imr::evaluate_total_actual_width(widths, n);
  if (!(total > 0.0)) { return -1.0; }
  // `the4Momentum.gamma()` is E/m.
  const double gamma = (actual_mass > 0.0) ? p.e / actual_mass : 1.0;
  return imr::sample_residual_lifetime(total, gamma, rng);
}

/// One track's decay, for a caller that already knows it wants this one to go now. `out` must
/// have room for `kDecayMaxDaughters`; returns the number of products, or 0 for Geant4's NULL.
template <typename Rng>
__host__ __device__ inline int kinetic_decay_one(const DecayTrack& track, DecayTrack* out,
                                                 Rng& rng, KineticDecayRefusal& ref) {
  const imr::LorentzVector& p = track.momentum;
  const double actual_mass = std::sqrt(std::fabs(p.e * p.e - g4gpu::mag2(p.v)));
  double widths[kKineticDecayMaxChannels];
  imr::DecayRefusal dref;
  const int n = imr::kinetic_track_actual_widths(track.pdg, actual_mass, widths,
                                                 kKineticDecayMaxChannels, dref);
  if (n < 0) {
    ref.unknown_species = dref.unknown_species;
    ref.too_many_daughters = dref.too_many_daughters;
    ref.refused_pdg = dref.refused_pdg;
    return 0;
  }
  const imr::DecayResult res = imr::kinetic_track_decay(track.pdg, actual_mass, p, widths, n, rng,
                                                        dref);
  if (dref.any()) {
    ref.unknown_species = ref.unknown_species || dref.unknown_species;
    ref.too_many_daughters = ref.too_many_daughters || dref.too_many_daughters;
    ref.below_threshold = ref.below_threshold || dref.below_threshold;
    ref.phase_space_failed = ref.phase_space_failed || dref.phase_space_failed;
    ref.refused_pdg = dref.refused_pdg;
  }
  // "Use the integer round mass in keV to get an unique ID for the parent resonance" - the
  // invariant mass, not the actual mass, and `round` and not a truncation.
  const int unique_id = static_cast<int>(std::round(p.mag() / u::keV<double>()));
  for (int i = 0; i < res.n; ++i) {
    out[i].pdg = res.prod[i].pdg;
    out[i].momentum = res.prod[i].p;
    out[i].position = track.position;
    out[i].formation_time = 0.0;
    out[i].creator_model_id = track.creator_model_id;
    out[i].parent_resonance_pdg = track.pdg;
    out[i].parent_resonance_id = unique_id;
  }
  return res.n;
}

/// `G4DecayKineticTracks::Decay(G4KineticTrackVector*)`.
///
/// Walks the list forwards while it GROWS, which is what makes the pass transitive: a daughter
/// that is itself short-lived is decayed when the walk reaches it, with no recursion. A parent
/// whose decay produced daughters is removed; a parent whose `Decay()` returned nothing is not.
/// The surviving order is the index order that remains after the nulls are erased - the
/// non-decaying originals first, in their original order, then the daughters generation by
/// generation. The cascade's track list takes that order and so does every later random number
/// (docs/RISK.md V151).
///
/// `n` is updated in place and the return is the new length.
template <typename Rng>
__host__ __device__ inline int decay_kinetic_tracks(DecayTrack* tracks, int& n, int capacity,
                                                    Rng& rng, KineticDecayRefusal& ref) {
  // A decayed parent's slot is marked by `pdg = 0`, which is Geant4's `(*tracks)[i] = nullptr`.
  // No real track carries code 0, and marking in place means there is no auxiliary array and so
  // no second capacity to get wrong.
  DecayTrack daughters[imr::kDecayMaxDaughters];
  for (int i = 0; i < n; ++i) {
    if (tracks[i].pdg == 0) { continue; }
    if (!kinetic_decay_is_short_lived(tracks[i].pdg)) {
      if (!kinetic_decay_knows(tracks[i].pdg)) {
        ref.unknown_species = true;
        ref.refused_pdg = tracks[i].pdg;
      }
      continue;
    }
    const int nd = kinetic_decay_one(tracks[i], daughters, rng, ref);
    if (nd == 0) { continue; }  // Geant4's NULL: the parent stays in the list
    if (n + nd > capacity) {
      ref.list_full = true;
      ref.refused_pdg = tracks[i].pdg;
      continue;
    }
    for (int k = 0; k < nd; ++k) { tracks[n + k] = daughters[k]; }
    n += nd;
    tracks[i].pdg = 0;
  }
  // "Find and remove null pointers created by decays above". Geant4 walks backwards erasing one
  // slot at a time, which is an order-preserving compaction done the slow way; this is the same
  // result in one forward pass.
  int w = 0;
  for (int r = 0; r < n; ++r) {
    if (tracks[r].pdg == 0) { continue; }
    if (w != r) { tracks[w] = tracks[r]; }
    ++w;
  }
  n = w;
  return n;
}

}  // namespace g4gpu::bic

#endif
