// CLHEP::RandGaussQ - which is what `G4RandGauss` is, at every call site in Geant4.
//
// `Randomize.hh` line 47 (source/global/HEPRandom/include) reads
//
//     #define G4RandGauss CLHEP::RandGaussQ
//
// so every `G4RandGauss::shoot` in Geant4 11.1.1 is the table-driven quick Gaussian of
// externals/clhep/src/RandGaussQ.cc and include/CLHEP/Random/RandGaussQ.icc: ONE uniform in and
// one value out, by `transformQuick` - linear interpolation in the 1,250-entry inverse-normal-CDF
// table of gaussQTables.cdat (core/randgaussq_table.hh, generated by tools/extract_randgaussq.pl)
// with `transformSmall`'s asymptotic series below r = 2e-6 - and NO state of any kind. It is not
// `CLHEP::RandGauss`, the polar method, which costs 2.55 uniforms per PAIR and caches the second
// value of each pair in a static; and it is not Box-Muller, which costs two uniforms per value.
//
// P9e transcribed this for the Binary cascade (docs/RISK.md V180) in bic/nucleus/
// fancy_3d_nucleus.cuh, and P17 moved it here UNCHANGED when the other call sites QBBC reaches
// turned out to need the same function (docs/RISK.md V185). The arithmetic is P9e's to the
// operation: the twenty taped ion events of bic_blir_tape.csv replay Geant4's own stream through
// three of these per C12 nucleon, and they are bitwise before and after the move.
//
// The sites, each of them `G4RandGauss::shoot(...)` in 11.1.1 and each one uniform per value:
//
//   G4Fancy3DNucleus::ChoosePositions, C12     .cc:383/391/410/429  bic/nucleus/fancy_3d_nucleus
//   G4UniversalFluctuation::SampleFluctuations .cc:138              em/fluctuation.cuh
//   G4UniversalFluctuation::SampleGauss        .hh:156              em/fluctuation.cuh
//   G4IonFluctuations::SampleFluctuations      .cc:149              em/ion_fluctuation.cuh
//   G4UrbanMscModel::Randomizetlimit           .hh:220              em/urban_msc.cuh
//   G4WentzelVIModel::SampleScattering, x, y   .cc:658-659          em/wentzel_msc.cuh
//   G4CompetitiveFission::FissionCharge        .cc:292              deexcitation/fission.cuh
//   G4CompetitiveFission::FissionKineticEnergy .cc:363              deexcitation/fission.cuh
//
// **WHAT THIS FUNCTION IS NOT, measured against the exact inverse normal CDF (docs/RISK.md
// V185).** It is not an exact normal, and the float truncation is the smallest part of why.
// Linear interpolation of the inverse CDF on a uniform PROBABILITY grid is good where the curve
// is straight and poor where it bends: the worst error in z is 2.5e-7 for |z| < 0.67, 1.4e-6 for
// |z| < 1.28, 9.8e-5 at |z| = 2.32 - and 1.6e-2 at |z| = 3.19 (r = 7.2e-4) and 1.2e-2 at
// |z| = 4.53 (r = 2.9e-6), in the first bin of each table. Every bin still carries exactly its
// probability, so the distribution is right bin by bin and wrong WITHIN the tail bins, where it
// is uniform in z instead of falling; that makes it WIDER than a normal: E[z^2] = 1.000135 and
// E[z^4] = 3.0024, by quadrature over r. Geant4's every Gaussian is that one. And the tail does
// not stop where the table stops (|z| = 4.61 at r = 2e-6): `transformSmall` carries it on, and
// what bounds it is the engine's smallest uniform - 2^-33 for this port's Philox<double>, where
// it returns |z| = 6.338 - not the table.
#ifndef G4GPU_CORE_RAND_GAUSS_Q_CUH
#define G4GPU_CORE_RAND_GAUSS_Q_CUH

#include <cmath>

#include "core/randgaussq_table.hh"
#include "core/units.cuh"

namespace g4gpu {

/// `CLHEP::RandGaussQ::transformSmall(r)` - the tail, for `r <= 2e-6`, where the table stops.
///
/// It solves the asymptotic expansion of the complementary error integral for `-v` by fixed-point
/// iteration from a guess of 7.5, at most 50 times, stopping when two iterates agree to 1e-7.
/// The series is carried to `13*11*9*7*5*3 / v^14` - further than the accuracy of the answer
/// justifies, and the source says why: "to ensure smoothness with the table generator". It is
/// reached whenever r or 1 - r is at most 2e-6, so with probability 4e-6 per draw, once in
/// 250,000 - CLHEP's own comment beside it says "less than one time in a million firings", which
/// is a factor of four low - and a transport run draws millions of Gaussians.
///
/// `r == 0` gives NaN, in CLHEP and here - `log(s1/0)` is infinite on the first pass and the
/// second pass is `0*inf`. No CLHEP engine returns 0, and `Philox<double>::uniform()` cannot
/// either (it is `(k + 0.5)/2^32`); `Philox<float>` can return exactly 1.0f, which mirrors to 0.
/// docs/RISK.md V185 has what that means for a G4GPU_FP32 build.
__host__ __device__ inline double rand_gauss_q_small(double r) {
  const double eps = 1.0e-7;
  double guess = 7.5;
  double v = guess;
  for (int i = 1; i < 50; ++i) {
    const double vn2 = 1.0 / (guess * guess);
    double s1 = -13.0 * 11.0 * 9.0 * 7.0 * 5.0 * 3.0 * vn2 * vn2 * vn2 * vn2 * vn2 * vn2 * vn2;
    s1 += 11.0 * 9.0 * 7.0 * 5.0 * 3.0 * vn2 * vn2 * vn2 * vn2 * vn2 * vn2;
    s1 += -9.0 * 7.0 * 5.0 * 3.0 * vn2 * vn2 * vn2 * vn2 * vn2;
    s1 += 7.0 * 5.0 * 3.0 * vn2 * vn2 * vn2 * vn2;
    s1 += -5.0 * 3.0 * vn2 * vn2 * vn2;
    s1 += 3.0 * vn2 * vn2 - vn2 + 1.0;
    v = std::sqrt(2.0 * std::log(s1 / (r * guess * std::sqrt(units::twopi<double>()))));
    if (std::fabs(v - guess) < eps) { break; }
    guess = v;
  }
  return -v;
}

/// `CLHEP::RandGaussQ::transformQuick(r)` - **this is what `G4RandGauss::shoot()` is**.
///
/// `Randomize.hh` line 47 is `#define G4RandGauss CLHEP::RandGaussQ`, so every
/// `G4RandGauss::shoot` in Geant4 is this: ONE uniform in, one Gaussian out, by table lookup and
/// linear interpolation, with no state of any kind. It is NOT `CLHEP::RandGauss`, the Box-Muller
/// polar method, which costs 2.55 uniforms per PAIR of values and caches the second of each pair
/// in a process-wide static. The Binary cascade used to implement that one; docs/RISK.md V180 is
/// what that cost and how it was found, and V185 is the six other sites that had the same fault.
///
/// Three branches, and the boundaries are exact comparisons:
///
///   * `r > 0.5` is mirrored to `1 - r` with the sign flipped, so the table only ever covers the
///     lower half. `r == 0.5` is not special-cased here and does not need to be: it lands on the
///     `index == Table1size` return of exactly zero.
///   * `r >= 5e-4` indexes the coarse table, `index = int(2000 * r)`, and `int(2000 * 0.5)` is
///     1000, which is the one value that returns 0.0 outright.
///   * `2e-6 < r < 5e-4` indexes the fine table through `rr = r * 2000`, and below that the
///     series above takes over.
///
/// **The result is cast to `float` before it is returned**, in CLHEP and here. The interpolation
/// runs in double and the answer does not: a port that kept the double would agree with Geant4
/// to about seven digits and then diverge, which for a replayed stream is the same as being
/// wrong.
__host__ __device__ inline double rand_gauss_q_transform(double r) {
  double sign = 1.0;
  if (r > 0.5) {
    r = 1.0 - r;
    sign = -1.0;
  }
  int index = 0;
  double dx = 0.0;
  if (r >= kGaussQTable1Step) {
    index = static_cast<int>((kGaussQTable1Size << 1) * r);
    if (index == kGaussQTable1Size) { return 0.0; }
    dx = (kGaussQTable1Size << 1) * r - index;
    index += kGaussQTable0Size - 1;   // Table1offset - 1
  } else if (r > kGaussQTable0Step) {
    const double rr = r * (1.0 / kGaussQTable1Step);   // Table0scale
    index = static_cast<int>(kGaussQTable0Size * rr);
    dx = kGaussQTable0Size * rr - index;
    index += -1;                      // Table0offset - 1
  } else {
    return sign * rand_gauss_q_small(r);
  }
  const float* t = gauss_q_table();
  const double y0 = t[index++];
  const double y1 = t[index];
  return static_cast<double>(static_cast<float>(sign * (y1 * dx + y0 * (1.0 - dx))));
}

/// `G4RandGauss::shoot()` - `RandGaussQ::shoot()` is `transformQuick(engine->flat())`.
///
/// `Rng` needs one member, `uniform()`, in (0, 1) - the port's stand-in for `flat()`. One call,
/// one uniform: the draw count is what tests/test_rand_gauss_q.cu asserts at every site.
template <typename Rng>
__host__ __device__ inline double rand_gauss_q(Rng& rng) {
  return rand_gauss_q_transform(rng.uniform());
}

/// `G4RandGauss::shoot(mean, stdDev)` and `G4RandGauss::shoot(engine, mean, stdDev)`.
///
/// Both are `shoot()*stdDev + mean` in RandGaussQ.icc - the product first, then the sum - and
/// both draw from the engine exactly once; the only difference is whose engine, and this port
/// has one stream per track either way.
///
/// `real_t` is the CALLER's arithmetic type, deduced from `mean` and `std_dev`, so the EM
/// package's `real_t` call sites compile as they are. The Gaussian itself is computed in double
/// as CLHEP computes it, and converted to `real_t` on the way out; for `real_t = double` - the
/// default build, and the only one the cascade has - the two casts are the identity and this is
/// P9e's `rand_gauss_q(rng, mean, std_dev)` exactly.
template <typename Rng, typename real_t>
__host__ __device__ inline real_t rand_gauss_q(Rng& rng, real_t mean, real_t std_dev) {
  // `RandGaussQ::shoot(mean, stdDev)` is `transformQuick(flat())*stdDev + mean`, in that order.
  return static_cast<real_t>(rand_gauss_q_transform(rng.uniform()) *
                                 static_cast<double>(std_dev) +
                             static_cast<double>(mean));
}

}  // namespace g4gpu

#endif
