#!/bin/bash
# Extracts Q. Yang's ion-fluctuation coefficients from G4IonFluctuations.cc into
# src/data/yang_fluctuation.hh.
#
#   bash tools/extract_yang.sh
#
# The table is a[96][4], indexed by Zeff-2 (helium first, so index 0 is Z=2), holding the four
# coefficients of
#
#     ss = 1 + a0 * E^a1 + a2 * E^a3          E in MeV/amu, reduced by the projectile mass
#
# from Q. Yang, D.J. O'Connor, Z. Wang, NIM B61 (1991) 149-155. Geant4 hard-codes it in the
# middle of a function body; it is pulled out here rather than retyped because 384 numbers
# retyped by hand is 384 chances to transpose a digit, and a transposed digit in a variance
# is invisible in every mean.
#
# Asserted below: exactly 96 rows, exactly 4 values in each. If Geant4 ever reshapes the
# table this fails loudly instead of writing a short one.
set -euo pipefail

G4SRC="$(dirname "$0")/g4src.sh"
if [ -x "$G4SRC" ]; then
  ROOT="$(bash "$G4SRC")/source"
else
  ROOT="D:/Documents/Geant4/Windows/geant4-v11.1.1/source"
fi
SRC="$ROOT/processes/electromagnetic/standard/src/G4IonFluctuations.cc"
OUT="src/data/yang_fluctuation.hh"

if [ ! -f "$SRC" ]; then
  echo "cannot find $SRC" >&2
  exit 1
fi

# Everything between the declaration and the closing brace of the initialiser, one row per
# line, braces and trailing commas stripped.
rows="$(awk '
  /static const G4double a\[96\]\[4\]/ { grab = 1; next }
  grab && /^[[:space:]]*}[[:space:]]*;/ { grab = 0 }
  grab {
    line = $0
    gsub(/[{}]/, "", line)
    gsub(/[[:space:]]/, "", line)
    sub(/,$/, "", line)
    if (line != "") { print line }
  }
' "$SRC")"

n="$(printf '%s\n' "$rows" | grep -c .)"
if [ "$n" -ne 96 ]; then
  echo "expected 96 rows of Yang coefficients, extracted $n" >&2
  exit 1
fi

bad="$(printf '%s\n' "$rows" | awk -F, 'NF != 4 { print NR": "NF" fields" }')"
if [ -n "$bad" ]; then
  echo "rows with other than 4 coefficients:" >&2
  echo "$bad" >&2
  exit 1
fi

{
  cat <<'HEADER'
// Generated by tools/extract_yang.sh from G4IonFluctuations.cc - do not edit.
//
// Q. Yang, D.J. O'Connor and Z. Wang, NIM B61 (1991) 149-155: the empirical widening of the
// energy-loss straggling of a slow ion, over and above the Bohr/Bethe variance, caused by the
// ion's own charge state fluctuating as it picks up and loses electrons.
//
//     ss = 1 + a0 * E^a1 + a2 * E^a3           E = kinetic energy in MeV per amu
//
// Row index is Zeff - 2 clamped to [0, 95], so row 0 is helium and row 95 is curium; Geant4
// clamps the same way, which means hydrogen shares helium's row rather than having one.
//
// Used only below beta^2 < 3 * theBohrBeta2 * Z. Above that the relativistic factor of
// H. Geissel et al., NIM B195 (2002) 3 is used on its own.
#ifndef G4GPU_DATA_YANG_FLUCTUATION_HH
#define G4GPU_DATA_YANG_FLUCTUATION_HH

namespace g4gpu::data {

/// Number of tabulated Z values, starting at Z = 2.
constexpr int kYangRows = 96;
constexpr int kYangZMin = 2;

/// Row-major [96][4]: a0, a1, a2, a3. Index with `yang_coefficients() + 4 * row`.
///
/// Unlike every other table in src/data, this one is read inside a stepping kernel rather than
/// once on the host to build a table - an alpha's fluctuation is sampled every step. That
/// changes nothing about how it is written, but it does mean these 384 doubles land in device
/// code, which is worth knowing when the alpha kernel's register pressure is next in question.
__host__ __device__ inline const double* yang_coefficients() {
  static const double v[kYangRows * 4] = {
HEADER
  printf '%s\n' "$rows" | awk -F, '{ printf "      %s, %s, %s, %s,\n", $1, $2, $3, $4 }'
  cat <<'FOOTER'
  };
  return v;
}

}  // namespace g4gpu::data

#endif  // G4GPU_DATA_YANG_FLUCTUATION_HH
FOOTER
} > "$OUT"

echo "wrote $OUT: $n rows, $((n * 4)) coefficients"
