#!/bin/sh
# Extracts fMottCoef[93][5][6] from G4MottData.hh into tools/mott_raw.hh.
#
#   sh tools/extract_mott.sh [<geant4 source root>]
#
# The tree comes from tools/g4src.sh, which refuses a version that does not match the oracle
# (docs/RISK.md O7).
#
# 2790 G4double coefficients: for each Z from 0 to 92, a 5x6 matrix of the polynomial
# G4ScreeningMottCrossSection::RatioMottRutherfordCosT evaluates -
#
#     R = sum_j ( sum_k coef[Z][j][k] * (beta - 0.7181228)^k ) * sqrt(1 - cos(theta))^j
#
# with j over 0..4 and k over 0..5. Row 0 of the table is Z = 0 and is all zeros, which is why
# the first index runs to 93 and not 92.
#
# The count is asserted. A table of the right shape and the wrong data passes every other check
# there is (RISK.md O6), so the values are checked afterwards against Geant4's own
# RatioMottRutherfordCosT answers in ref/oracle/mott_ratio.csv.
set -e
G4=$(sh "$(dirname "$0")/g4src.sh" ${1:+"$1"}) || exit 1
SRC="$G4/source/processes/electromagnetic/standard/include/G4MottData.hh"
OUT="$(dirname "$0")/mott_raw.hh"
[ -f "$SRC" ] || { echo "no $SRC" >&2; exit 1; }

# Everything between `fMottCoef[93][5][6] = {` and the matching `};`, with comments and
# braces stripped so what is left is a comma-separated list of 2790 numbers. The element-name
# comments (`//H....`, `//He....`) are why the comment strip has to come first: without it the
# flattener would swallow the value after each one, which is exactly how the NIST material
# names lost one in ten (RISK.md O6).
VALS=$(awk '
  index($0, "fMottCoef[93][5][6]") > 0 { on = 1; next }
  on {
    l = $0
    sub(/\/\/.*$/, "", l)
    # The table ends `}};` on the same line as the last row, not `};` on a line of its own.
    if (l ~ /\}\};/) { sub(/\}\};.*$/, "", l); gsub(/[{}]/, "", l); gsub(/[ \t\r]/, "", l)
                       print out l; exit }
    gsub(/[{}]/, "", l)
    gsub(/[ \t\r]/, "", l)
    out = out l
  }' "$SRC")

n=$(echo "$VALS" | tr ',' '\n' | grep -c '[0-9]')
[ "$n" = 2790 ] || { echo "fMottCoef came out with $n values, not 2790" >&2; exit 1; }

{
  cat <<HDR
// Generated by tools/extract_mott.sh from G4MottData.hh - do not edit.
//
// The Mott-to-Rutherford ratio coefficients: for each Z from 0 to 92, a 5x6 matrix. Z = 0 is
// all zeros, which is why the first extent is 93.
//
// These are G4double in Geant4 and are emitted as such - unlike the ICRU 90 stopping powers,
// which are G4float there and have to be rounded through float to match (RISK.md O11).
#ifndef G4GPU_MOTT_RAW_HH
#define G4GPU_MOTT_RAW_HH

namespace g4gpu::data::mott_raw {

/// Flat, [Z*30 + j*6 + k]. Reshaped by tools/gen_mott.cc.
constexpr double kMottCoef[2790] = {
HDR
  echo "$VALS" | tr ',' '\n' | awk 'NF{printf "%s%s,", (n%6?" ":(n?"\n    ":"    ")), $0; ++n} END{print ""}'
  cat <<FTR
};

}  // namespace g4gpu::data::mott_raw

#endif  // G4GPU_MOTT_RAW_HH
FTR
} > "$OUT"
echo "wrote $OUT ($n coefficients)"
