#!/bin/sh
# Extracts vFermi[92] and lFactor[92] from G4IonisParamElm.cc into src/data/fermi_velocity.hh.
#
#   sh tools/extract_fermi.sh [<geant4 source root>]
#
# The tree comes from tools/g4src.sh, which refuses one whose version does not match the
# oracle's - see docs/RISK.md O7.
#
# Both tables are indexed Z-1 and clamped to index 91, so the header exposes them as functions
# of Z with the clamp built in rather than as raw arrays: an off-by-one here is a silent
# wrong-element bug, which is precisely how the stopping-power extraction failed (RISK.md O6).
# The count is asserted; a table that came out the wrong length stops the script.
set -e
G4=$(sh "$(dirname "$0")/g4src.sh" ${1:+"$1"}) || exit 1
SRC="$G4/source/materials/src/G4IonisParamElm.cc"
OUT="$(dirname "$0")/../src/data/fermi_velocity.hh"
[ -f "$SRC" ] || { echo "no $SRC" >&2; exit 1; }

# Flatten one `static const G4double <name>[92] = { ... };` initialiser to a comma list.
# Comments are stripped first: `// 0 - 9` annotations inside a Geant4 table swallowed the next
# entry the last time this was done without stripping them.
grab() {
  awk -v want="$1" '
    index($0, "G4double " want "[92]") > 0 { on = 1 }
    on {
      l = $0
      sub(/\/\/.*$/, "", l)
      sub(/^[^{]*\{/, "", l)
      if (index(l, "}") > 0) { sub(/\}.*$/, "", l); done = 1 }
      gsub(/[ \t\r]/, "", l)
      out = out l
      if (done) { print out; exit }
    }' "$SRC"
}

count() { echo "$1" | tr ',' '\n' | grep -c '[0-9]'; }

VF=$(grab vFermi)
LF=$(grab lFactor)
nvf=$(count "$VF")
nlf=$(count "$LF")
[ "$nvf" = 92 ] || { echo "vFermi came out with $nvf values, not 92" >&2; exit 1; }
[ "$nlf" = 92 ] || { echo "lFactor came out with $nlf values, not 92" >&2; exit 1; }

wrap() { echo "$1" | tr ',' '\n' | awk 'NF{printf "%s%s", (n%8?" ":(n?"\n    ":"    ")), $0 ", "; ++n} END{print ""}'; }

cat > "$OUT" <<HDR
// Generated by tools/extract_fermi.sh from G4IonisParamElm.cc - do not edit.
//
// Ziegler, Biersack and Littmark, "The Stopping and Range of Ions in Matter" vol. 1 (1985),
// as Geant4 tabulates it. Both tables are indexed Z-1 in Geant4 and clamped to index 91, so
// anything above uranium reads uranium's value; that clamp is reproduced here.
//
// vFermi is the Fermi velocity in units where the material's Fermi energy is 25 keV * vF^2.
// lFactor is Ziegler's L-factor, used by the low-energy ion stopping models.
#ifndef G4GPU_DATA_FERMI_VELOCITY_HH
#define G4GPU_DATA_FERMI_VELOCITY_HH

namespace g4gpu::data {

/// vFermi[Z-1] from G4IonisParamElm, $nvf entries.
__host__ __device__ inline double fermi_velocity_table(int z) {
  static const double kVFermi[92] = {
$(wrap "$VF")
  };
  int iz = z - 1;
  if (iz < 0) { iz = 0; }
  if (iz > 91) { iz = 91; }  // Geant4's own clamp: "if(91 < iz) { iz = 91; }"
  return kVFermi[iz];
}

/// lFactor[Z-1] from G4IonisParamElm, $nlf entries.
__host__ __device__ inline double ziegler_l_factor(int z) {
  static const double kLFactor[92] = {
$(wrap "$LF")
  };
  int iz = z - 1;
  if (iz < 0) { iz = 0; }
  if (iz > 91) { iz = 91; }
  return kLFactor[iz];
}

}  // namespace g4gpu::data

#endif  // G4GPU_DATA_FERMI_VELOCITY_HH
HDR
echo "wrote $OUT ($nvf vFermi, $nlf lFactor)"
