#!/usr/bin/perl
# Extracts the set of naturally occurring isotopes out of G4NistElementBuilder (Geant4 11.1.1)
# and writes it as src/data/natural_isotopes.hh.
#
#   perl tools/extract_natural_isotopes.pl
#
# Why the de-excitation module needs it: G4Evaporation::BreakFragment and
# G4ExcitationHandler::SortSecondaryFragment both ask
# `G4NistManager::GetIsotopeAbundance(Z, A) > 0.0` and use the answer as a BOOLEAN - a cold
# fragment that is a natural isotope is released, one that is not is evaporated again. The
# abundances themselves are never read, so what is transcribed here is the predicate, not the
# table: 311 (Z, A) pairs instead of 2908 numbers.
#
# The argument really is A and not N, despite the parameter being named `N`:
# G4NistElementBuilder::AddElement is called with the `XxN[]` arrays, and those hold mass
# numbers - `HN[6] = {1, 2, 3, 4, 5, 6}` for hydrogen, `HeN[8] = {3, 4, ...}` for helium.
# `nFirstIsotope[Z]` is therefore the first tabulated A, and the callers above pass A. The
# naming is a trap and the code is right.
use strict;
use warnings;

my $g4 = $ENV{G4SRC} || 'D:/Documents/Geant4/Windows/geant4-v11.1.1';
my $src = "$g4/source/materials/src/G4NistElementBuilder.cc";
my $hh  = "$g4/source/materials/include/G4NistElementBuilder.hh";

my $maxz = 0;
{
  open my $fh, '<', $hh or die "cannot open $hh: $!";
  while (my $l = <$fh>) { $maxz = $1 if $l =~ /const\s+G4int\s+maxNumElements\s*=\s*(\d+)/; }
  close $fh;
}
die "no maxNumElements in $hh\n" if !$maxz;

# Slurp the file and pull out every array initialiser by name, then every AddElement call.
open my $fh, '<', $src or die "cannot open $src: $!";
my $text = do { local $/; <$fh> };
close $fh;
$text =~ s{//[^\n]*}{}g;

my %arr;
while ($text =~ /\b(?:G4int|G4double)\s+(\w+)\s*\[\s*\d*\s*\]\s*=\s*\{(.*?)\}\s*;/gs) {
  my ($name, $body) = ($1, $2);
  my @v = ($body =~ /(-?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)/g);
  $arr{$name} = \@v;
}

my @rows;
my ($nelem, $niso, $nnat) = (0, 0, 0);
while ($text =~ /AddElement\(\s*"(\w+)"\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*\*(\w+)\s*,\s*\*(\w+)\s*,\s*\*(\w+)\s*,\s*\*(\w+)\s*\)/g) {
  my ($sym, $Z, $nc, $nName, $aName, $sName, $wName) = ($1, $2, $3, $4, $5, $6, $7);
  ++$nelem;
  die "AddElement $sym: no array $nName\n" if !$arr{$nName};
  die "AddElement $sym: no array $wName\n" if !$arr{$wName};
  my @N = @{$arr{$nName}};
  my @W = @{$arr{$wName}};
  die "AddElement $sym: $nc isotopes but N has " . scalar(@N) . "\n" if @N < $nc;
  die "AddElement $sym: $nc isotopes but W has " . scalar(@W) . "\n" if @W < $nc;
  $niso += $nc;
  for my $i (0 .. $nc - 1) {
    next if $W[$i] + 0 <= 0;
    push @rows, [$Z, $N[$i] + 0, $sym];
    ++$nnat;
  }
}

# 107 elements, 2908 tabulated isotopes, 311 with a non-zero abundance - which is more than
# the 288 nuclides usually called naturally occurring, because the table also carries the
# primordial radioisotopes (K40, Rb87, In115, Th232, U235, U238 and the rest) that a list of
# STABLE nuclides leaves out. Asserted so that a release which retunes the table fails here.
die "found $nelem AddElement calls, expected 107\n"       if $nelem != 107;
die "found $niso tabulated isotopes, expected 2908\n"     if $niso != 2908;
die "found $nnat natural isotopes, expected 311\n"        if $nnat != 311;

my $out = 'src/data/natural_isotopes.hh';
open my $o, '>', $out or die "cannot write $out: $!";
print $o <<"HDR";
// The naturally occurring isotopes of G4NistElementBuilder, as a predicate.
//
// GENERATED by tools/extract_natural_isotopes.pl from Geant4 11.1.1 - do not edit by hand.
// $nnat (Z, A) pairs out of $niso tabulated isotopes over $nelem elements.
//
// G4Evaporation::BreakFragment and G4ExcitationHandler::SortSecondaryFragment ask
// `G4NistManager::GetIsotopeAbundance(Z, A) > 0.0` and use only the sign of the answer: a
// cold fragment that is a natural isotope is released, one that is not goes back into the
// evaporation list. So the abundances are not needed and are not here - only the set.
//
// The second argument is a MASS NUMBER. G4NistManager::GetIsotopeAbundance names it `N` and
// G4NistElementBuilder indexes `relAbundance[A - nFirstIsotope[Z] + idxIsotopes[Z]]` with it,
// but nFirstIsotope[Z] is filled from the `XxN[]` arrays, which hold mass numbers. Both
// callers in the de-excitation module pass A, and they are right to.
#ifndef G4GPU_DATA_NATURAL_ISOTOPES_HH
#define G4GPU_DATA_NATURAL_ISOTOPES_HH

namespace g4gpu::data {

/// G4NistElementBuilder's maxNumElements. `GetIsotopeAbundance` returns zero outside
/// `0 < Z < maxNumElements` whatever the table holds, so the guard is part of the answer.
constexpr int kNistMaxNumElements = $maxz;

HDR

# One 32-bit mask word per (Z, A/32) would be denser, but a sorted (Z, A) run table is what a
# reader can check against the source by eye, and 311 entries fit in cache either way.
printf $o "/// The pairs, sorted by Z then A, as `1000*Z + A`.\n";
printf $o "__host__ __device__ inline const int* natural_isotope_codes() {\n";
printf $o "  static const int v[%d] = {\n", scalar(@rows);
my $last_sym = '';
for my $r (@rows) {
  if ($r->[2] ne $last_sym) {
    printf $o "    // %s\n", $r->[2];
    $last_sym = $r->[2];
  }
  printf $o "    %d,\n", $r->[0] * 1000 + $r->[1];
}
printf $o "  };\n  return v;\n}\n\n";
printf $o "constexpr int kNumNaturalIsotopes = %d;\n\n", scalar(@rows);

print $o <<'TAIL';
/// `G4NistManager::GetIsotopeAbundance(Z, A) > 0.0`. Linear scan: the table is sorted by Z,
/// so the loop stops at the first entry past Z rather than running to the end.
__host__ __device__ inline bool is_natural_isotope(int Z, int A) {
  if (Z <= 0 || Z >= kNistMaxNumElements) { return false; }
  const int code = 1000 * Z + A;
  const int* v = natural_isotope_codes();
  for (int i = 0; i < kNumNaturalIsotopes; ++i) {
    if (v[i] == code) { return true; }
    if (v[i] > code) { return false; }
  }
  return false;
}

}  // namespace g4gpu::data

#endif
TAIL
close $o;
print "wrote $out: $nnat natural isotopes of $niso over $nelem elements\n";
