#!/bin/sh
# Extracts G4RayleighAngularGenerator's nine fit-parameter tables into
# src/data/rayleigh_angular_tables.cuh.
#
#   sh tools/extract_rayleigh_angular.sh [<geant4 source root>]
#
# PP0..PP2 are the weights of a three-term fit to the atomic form factor, PP3..PP5 the slopes,
# PP6..PP8 the exponents, indexed by Z from 0 to 100. Geant4 compiles them in - they are NOT
# the re-ff-Z.dat files in G4EMLOW, which are the *cross section*, not the angular distribution.
# So there is no data file to replace when Geant4 changes them, and no way to notice except by
# re-extracting.
#
# WHY THIS EXISTS
#
# This table was the one baked table in the port with neither an extractor nor a test. It is
# read by data::sample_rayleigh_direction, which perturbs a photon's direction and transfers no
# energy - so a wrong table moves a dose slightly and breaks nothing loudly. That is the worst
# combination there is: consequential enough to matter and quiet enough not to be found.
# tools/refresh_tables.sh named it explicitly for that reason; this closes the half of it that
# a script can close.
#
# THE TRAP, and it has been sprung here before. The arrays carry `// 1-10` annotations every
# tenth entry. Flattening the lines without stripping comments first turns the annotation into
# a line comment that swallows the following entry - which is exactly how extract_stopping.sh
# once dropped one material name in every ten, left the array the right length, and gave
# G4_WATER the stopping power of G4_TEFLON. Comments are stripped before anything else, and the
# count is asserted at 101 per table rather than trusted.
set -euo pipefail

G4SRC="$(dirname "$0")/g4src.sh"
G4="${1:-}"
G4=$(sh "$G4SRC" ${G4:+"$G4"}) || exit 1

SRC="$G4/source/processes/electromagnetic/lowenergy/src/G4RayleighAngularGenerator.cc"
OUT="$(dirname "$0")/../src/data/rayleigh_angular_tables.cuh"

if [ ! -f "$SRC" ]; then
  echo "cannot find $SRC" >&2
  exit 1
fi

# One table: everything between `G4RayleighAngularGenerator::PPn[101] = {` and the closing
# `};`, with comments stripped, flattened to one value per line.
table() {
  awk -v want="G4RayleighAngularGenerator::PP$1[101]" '
    index($0, want) > 0 { grab = 1 }
    grab {
      line = $0
      sub(/\/\/.*$/, "", line)          # kill the // 1-10 annotations FIRST
      sub(/.*\{/, "", line)             # drop everything up to the opening brace
      if (line ~ /\}/) { sub(/\}.*$/, "", line); grab = 2 }
      gsub(/[[:space:]]/, "", line)
      n = split(line, a, ",")
      for (i = 1; i <= n; ++i) { if (a[i] != "") print a[i] }
      if (grab == 2) { exit }
    }
  ' "$SRC"
}

tmp="$(dirname "$0")/.rayl_angular.tmp"
: > "$tmp"
for i in 0 1 2 3 4 5 6 7 8; do
  vals="$(table "$i")"
  n="$(printf '%s\n' "$vals" | grep -c .)"
  if [ "$n" -ne 101 ]; then
    echo "PP$i: expected 101 values, extracted $n" >&2
    rm -f "$tmp"
    exit 1
  fi
  printf '%s\n' "$vals" > "$tmp.$i"
done

{
  cat <<'HEADER'
// Generated by tools/extract_rayleigh_angular.sh from G4RayleighAngularGenerator.cc.
// Do not edit.
//
// Rayleigh angular-distribution fit parameters, 101 entries per table (Z = 0..100).
//
// These are a three-term fit to the atomic form factor, not the re-ff-Z.dat files in G4EMLOW -
// Geant4 compiles them in and reads no data file for the angular distribution. PP0..PP2 are
// the term weights, PP3..PP5 the slopes, PP6..PP8 the exponents.
//
// Index 0 is a placeholder zero in Geant4 and is kept as one here, so that Z indexes directly.
#pragma once
#include "core/units.cuh"

namespace g4gpu::data {

constexpr int kRaylPPSize = 101;
HEADER
  for i in 0 1 2 3 4 5 6 7 8; do
    printf '\ntemplate <typename real_t> __host__ __device__ inline const real_t* rayl_pp%s() {\n' "$i"
    printf '  static const real_t v[101] = {\n'
    awk '{ printf "      real_t(%s),\n", $0 }' "$tmp.$i"
    printf '  };\n  return v;\n}\n'
  done
  cat <<'FOOTER'

}  // namespace g4gpu::data
FOOTER
} > "$OUT"

rm -f "$tmp" "$tmp".[0-8]
echo "wrote $OUT: 9 tables x 101 parameters"
