#!/bin/sh
# Extracts the Barashenkov nucleon-nucleus cross-section tables from G4BarashenkovData.hh
# into tools/barashenkov_raw.hh.
#
#
# The arrays are `static constexpr`, not `inline constexpr`. This header is included by exactly
# one translation unit - tools/gen_barashenkov.cc - so `static` is correct, and it is what lets
# the whole refresh chain build with the MinGW g++ that ships alongside Git for Windows.
# `inline` variables are C++17 and GCC 6.3 accepts `-std=c++17` without implementing them, so
# the previous form compiled only under nvcc and quietly made this one table the only piece of
# the refresh that needed the full MSVC toolchain.
#
#   sh tools/extract_barashenkov.sh [<geant4 source root>]
#
# The tree comes from tools/g4src.sh, which refuses a version that does not match the oracle
# (docs/RISK.md O7).
#
# What is in there: 17 elements - He Be C N O Na Al Si Ca Fe Cu Mo Cd Sn W Pb U - each with a
# total cross section and two inelastic ones (a neutron's and a proton's), tabulated against one
# of six shared energy grids e1..e6 of 44 to 48 points running from 14 MeV to 1 TeV. 57 arrays,
# 2600 numbers.
#
# It is worth saying why the tables are transcribed rather than the cross section being sampled
# on a grid of its own. G4ComponentBarNucleonNucleusXsc interpolates linearly in energy inside
# one element's table and then between two elements in A, so the function has kinks exactly at
# the tabulated energies. Re-sampling it onto any other grid rounds those corners, and the
# result would agree with Geant4 everywhere except where the physics actually changes. With the
# real tables and Geant4's own two interpolations the answer is the same number, not a close
# one.
#
# Values are in millibarn as written; the caller converts. Energies are in GeV as written -
# note that G4PiData multiplies them by GeV on construction, so the grid arrays here are the
# raw numbers and the conversion belongs to whoever builds the table.
set -e
G4=$(sh "$(dirname "$0")/g4src.sh" ${1:+"$1"}) || exit 1
SRC="$G4/source/processes/hadronic/cross_sections/include/G4BarashenkovData.hh"
OUT="$(dirname "$0")/barashenkov_raw.hh"
[ -f "$SRC" ] || { echo "no $SRC" >&2; exit 1; }

# Every `static const G4double <name>[<n>] = { ... };`, flattened. Unlike the Mott table these
# are one-dimensional and each ends with `};` on its own line or at the end of a value line, so
# a single state machine over all of them works; the name and the declared extent are carried
# through so the count can be asserted per array rather than only in total.
emit_arrays() {
  awk '
    /static const G4double [a-z0-9_]+\[[0-9]+\]/ {
      match($0, /[a-z0-9_]+\[[0-9]+\]/)
      decl = substr($0, RSTART, RLENGTH)
      split(decl, p, "[")
      name = p[1]
      n = p[2]; sub(/\]/, "", n)
      on = 1; buf = ""
      # A declaration line may already carry values after the `{`.
      if (index($0, "{") > 0) { rest = substr($0, index($0, "{") + 1); buf = rest }
      next
    }
    on {
      l = $0
      sub(/\/\/.*$/, "", l)
      gsub(/{/, "", l)
      if (index(l, "}") > 0) {
        sub(/\}.*$/, "", l)
        buf = buf l
        gsub(/[ \t\r]/, "", buf)
        sub(/,$/, "", buf)
        printf "%s %s %s\n", name, n, buf
        on = 0
        next
      }
      buf = buf l
    }
  ' "$SRC"
}

TMP="${TMPDIR:-/tmp}/barash.$$"
emit_arrays > "$TMP"
trap 'rm -f "$TMP"' EXIT

narr=$(wc -l < "$TMP")
[ "$narr" = 57 ] || { echo "found $narr arrays, expected 57" >&2; exit 1; }

# Per-array count check. A table of the right shape and the wrong length is the failure mode
# that RISK.md O6 is about, and it is silent: the interpolator would just read past the end of
# one element's energies into the next element's cross sections.
total=0
while read -r name n vals; do
  got=$(printf '%s' "$vals" | tr ',' '\n' | grep -c '[0-9]')
  [ "$got" = "$n" ] || { echo "$name: $got values, declared $n" >&2; exit 1; }
  total=$((total + got))
done < "$TMP"

{
  cat <<HDR
// Generated by tools/extract_barashenkov.sh from G4BarashenkovData.hh - do not edit.
//
// Barashenkov's nucleon-nucleus total and inelastic cross sections, the tables behind
// G4ComponentBarNucleonNucleusXsc and so behind every nucleon elastic and inelastic cross
// section QBBC uses between 14 MeV and 91 GeV.
//
// Seventeen elements against six shared energy grids. \`*_m_t\` is the total cross section,
// which a proton and a neutron share; \`*_m_in\` is a neutron's inelastic and \`*_p_in\` a
// proton's. Cross sections are in millibarn and energies in GeV, both exactly as Geant4
// writes them - G4PiData applies the units when it builds its table, so the raw numbers are
// what belongs here.
#ifndef G4GPU_BARASHENKOV_RAW_HH
#define G4GPU_BARASHENKOV_RAW_HH

namespace g4gpu::data::barashenkov_raw {

HDR
  while read -r name n vals; do
    printf 'static constexpr double %s[%s] = {%s};\n' "$name" "$n" "$vals"
  done < "$TMP"
  cat <<'FTR'

}  // namespace g4gpu::data::barashenkov_raw

#endif
FTR
} > "$OUT"

echo "wrote $OUT: $narr arrays, $total values"
