#!/usr/bin/perl
# Generates src/physics/hadronic/bic/nucleus/randgaussq_table.hh from CLHEP's own table.
#
# WHY THIS EXISTS. `G4RandGauss` is `#define`d to `CLHEP::RandGaussQ` (Randomize.hh:47), not to
# `CLHEP::RandGauss` - docs/RISK.md V180 - and `RandGaussQ::transformQuick` is a lookup in a
# 1,250-entry table of the inverse normal CDF with linear interpolation between bins. The table
# lives in `CLHEP/Random/gaussQTables.cdat`, 1,250 float literals with the argument of each in a
# trailing comment, and it is 5 kilobytes of numbers: exactly the kind of thing that must be
# extracted and never retyped.
#
# The five geometry constants come from RandGaussQ.cc and are read out of it here rather than
# written down, for the same reason: a release that changes `Table1step` changes which bin every
# draw lands in.
#
# Usage:  perl tools/extract_randgaussq.pl [clhep-root]
use strict;
use warnings;

my $g4src = $ARGV[0] || 'D:/Documents/Geant4/Windows/geant4-v11.1.1';
my $cdat  = "$g4src/source/externals/clhep/include/CLHEP/Random/gaussQTables.cdat";
my $src   = "$g4src/source/externals/clhep/src/RandGaussQ.cc";
my $out   = 'src/physics/hadronic/bic/nucleus/randgaussq_table.hh';

# ---------------------------------------------------------------------------- the constants
open(my $sh, '<', $src) or die "cannot read $src: $!\n";
my $stext = do { local $/; <$sh> };
close $sh;
my %c;
for my $name (qw(Table0size Table1size Table0step Table1step)) {
    $stext =~ /^#define\s+$name\s+(\S+)\s*$/m
        or die "$name not found in $src - RandGaussQ has been rewritten\n";
    my $v = $1;
    $v =~ s/[()]//g;
    $c{$name} = $v;
}
die "Table0size is $c{Table0size}, expected 250\n"  unless $c{Table0size} == 250;
die "Table1size is $c{Table1size}, expected 1000\n" unless $c{Table1size} == 1000;
die "Table0step is $c{Table0step}\n" unless abs($c{Table0step} - 2.0e-6) < 1e-18;
die "Table1step is $c{Table1step}\n" unless abs($c{Table1step} - 5.0e-4) < 1e-16;

# `Table0scale` is `1.0/Table1step` and `Table0offset`/`Table1offset` are 0 and Table0size.
$stext =~ /#define\s+Table0scale\s+\(1\.0\/Table1step\)/
    or die "Table0scale is no longer 1/Table1step\n";
$stext =~ /#define\s+Table0offset\s+0\b/    or die "Table0offset is no longer 0\n";
$stext =~ /#define\s+Table1offset\s+\(Table0size\)/
    or die "Table1offset is no longer Table0size\n";
# And the truncation to float on the way out, which is part of the answer.
$stext =~ /return\s+\(float\)\s*\(\s*sign\s*\*\s*\(\s*y1\s*\*\s*dx\s*\+\s*y0\s*\*\s*\(1\.0-dx\)\s*\)\s*\)/
    or die "transformQuick no longer casts its result to float\n";

# ---------------------------------------------------------------------------- the table
open(my $fh, '<', $cdat) or die "cannot read $cdat: $!\n";
my (@v, @arg);
while (my $line = <$fh>) {
    next unless $line =~ /^\s*(-?[0-9.]+(?:[eE][-+]?\d+)?)f\s*,\s*(?:\/\/\s*(\S+))?/;
    push @v, $1;
    push @arg, defined($2) ? $2 : '';
}
close $fh;

my $n = scalar @v;
my $want = $c{Table0size} + $c{Table1size};
die "found $n entries in $cdat, the constants say $want\n" unless $n == $want;

# Structure, asserted rather than assumed. The table is the inverse CDF on (0, 0.5], so it is
# NEGATIVE everywhere except the last entry, which is the median and is exactly zero, and it
# increases monotonically: a bigger tail probability is a smaller number of sigmas.
die "the last entry is $v[$n-1], expected exactly 0\n" unless $v[$n-1] + 0 == 0.0;
for my $i (0 .. $n - 2) {
    die "entry $i is $v[$i], expected negative\n" unless $v[$i] + 0 < 0.0;
    # The one repeat is the seam: entry 249 and entry 250 are both errInt(5e-4), which is what
    # makes the two index formulas agree there. Everywhere else the table strictly increases.
    my $strict = ($i != $c{Table0size} - 1);
    if ($strict) {
        die "entry $i ($v[$i]) is not below entry " . ($i+1) . " ($v[$i+1])\n"
            unless $v[$i] + 0 < $v[$i+1] + 0;
    } else {
        die "the seam at $i is $v[$i] against $v[$i+1], expected equal\n"
            unless $v[$i] eq $v[$i+1];
    }
}
# The two halves meet: the last entry of table 0 and the first of table 1 are both errInt(5e-4).
die "the tables do not meet at 5e-4: $v[$c{Table0size}-1] against $v[$c{Table0size}]\n"
    unless $v[$c{Table0size} - 1] eq $v[$c{Table0size}];
# The arguments in the comments are the grid the constants describe, which is the check that the
# table and the constants are the same release.
die "table 0 starts at argument $arg[0], expected 2e-06\n" unless $arg[0] eq '2e-06';
die "table 1 ends at argument $arg[$n-1], expected 0.5\n"  unless $arg[$n-1] eq '0.5';

# ---------------------------------------------------------------------------- emit
open(my $o, '>', $out) or die "cannot write $out: $!\n";
print $o <<"HDR";
// GENERATED by tools/extract_randgaussq.pl from CLHEP's gaussQTables.cdat - do not edit.
//
// `CLHEP::RandGaussQ::transformQuick`'s inverse-normal-CDF table, $n float entries: the first
// $c{Table0size} on a grid of $c{Table0step} from 2e-06 to 5e-04, the next $c{Table1size} on a grid of
// $c{Table1step} from 5e-04 to 0.5. Both halves hold the SAME value at 5e-04, which is what makes the
// two index formulas in `transformQuick` agree on the boundary.
//
// They are `float` in CLHEP and they are `float` here: `transformQuick` interpolates in double
// and then casts the result back to float on the way out, so the answer carries float precision
// however it is stored, and storing the table as double would only hide where that happens.
//
// See docs/RISK.md V180 for why this table is in the port at all.
#ifndef G4GPU_BIC_NUCLEUS_RANDGAUSSQ_TABLE_HH
#define G4GPU_BIC_NUCLEUS_RANDGAUSSQ_TABLE_HH

namespace g4gpu::bic {

inline constexpr int kGaussQTable0Size = $c{Table0size};
inline constexpr int kGaussQTable1Size = $c{Table1size};
inline constexpr int kGaussQTableSize = $n;
inline constexpr double kGaussQTable0Step = $c{Table0step};
inline constexpr double kGaussQTable1Step = $c{Table1step};

__host__ __device__ inline const float* gauss_q_table() {
  static const float t[kGaussQTableSize] = {
HDR

for (my $i = 0; $i < $n; $i += 4) {
    my @row;
    for my $j ($i .. $i + 3) {
        last if $j >= $n;
        push @row, sprintf('%sf', $v[$j]);
    }
    print $o '      ', join(', ', @row), ",\n";
}

print $o <<'FTR';
  };
  return t;
}

}  // namespace g4gpu::bic

#endif
FTR
close $o;
printf "wrote %s: %d entries, tables of %d and %d\n", $out, $n, $c{Table0size}, $c{Table1size};
