#!/bin/sh
# Extracts the NIST stopping-power tables from Geant4 11.1.1's sources into one header.
#
# The tables are hard-coded in Geant4 too - they are the published PSTAR, ASTAR and ICRU 90
# tabulations, not something computed - so copying them is copying data, not duplicating an
# implementation. What this script guarantees, and hand transcription would not, is that
# every number is the number Geant4 has: it reads the same .cc files the library compiles.
#
#   sh extract_stopping.sh <geant4 source root> <output header>
set -e
G4="$1"
OUT="$2"
NIST="$G4/source/processes/electromagnetic/standard/include/G4NISTStoppingData.hh"
PSTAR="$G4/source/processes/electromagnetic/standard/src/G4PSTARStopping.cc"
ASTAR="$G4/source/processes/electromagnetic/standard/src/G4ASTARStopping.cc"

for f in "$NIST" "$PSTAR" "$ASTAR"; do
  if [ ! -f "$f" ]; then echo "missing: $f" >&2; exit 1; fi
done

# One brace-delimited initialiser list, by the name that precedes it, flattened to one line.
#
# index() rather than a regex: the array name is followed by '[', and getting a literal
# bracket through a shell single-quoted awk program into a regex takes four backslashes and is
# wrong three of those ways.
#
# The // comment strip is not cosmetic. nameNIST is annotated every ten entries -
#     "G4_B-100_BONE",  // 0 - 9
# - and without stripping it the flattened line reads `"G4_B-100_BONE",//0-9"G4_Be",`, whose
# next comma-separated field is `//0-9"G4_Be"`. That emits as a C++ comment, so the entry
# vanishes, every following name shifts up by one, and C++ zero-fills the tail. The generated
# array is then still 74 long and still compiles, and G4_WATER gets G4_TEFLON's stopping
# power. It took a numeric comparison against Geant4 to see it; see docs/RISK.md O6.
flatten() {
  awk -v want="$2" '
    index($0, want) > 0 { on = 1 }
    on {
      line = $0
      sub(/\/\/.*$/, "", line)
      sub(/^[^{]*\{/, "", line)
      if (index(line, "}") > 0) { sub(/\}.*$/, "", line); done = 1 }
      gsub(/f/, "", line)
      gsub(/\* *mvx/, "", line)
      gsub(/[ \t]/, "", line)
      out = out line
      if (done) { print out; exit }
    }
  ' "$1"
}

nvals() { echo "$1" | tr ',' '\n' | grep -c '[0-9]'; }

{
  cat <<'HEADER'
// NIST stopping-power tables: PSTAR (protons) and ASTAR (alphas), for 74 NIST materials.
//
// GENERATED by tools/extract_stopping.sh from Geant4 11.1.1's own sources -
// G4NISTStoppingData.hh, G4PSTARStopping.cc and G4ASTARStopping.cc. Do not edit by hand;
// re-run the script.
//
// These are the published PSTAR and ASTAR tabulations, hard-coded in Geant4 exactly as they
// are hard-coded here, so this is copied data rather than a duplicated implementation. The
// script reads the same files the library compiles, which is what makes "every number is the
// number Geant4 has" a fact rather than a hope.
//
// Units, and the one place it is easy to go wrong: the tables hold MeV cm2/g, a *mass*
// stopping power. Geant4 multiplies by MeV*cm2/g on load and by the material density at use.
// They are kept in the published units here and converted at the point of use, so that a
// number in this file can be checked against a NIST table by eye.
//
// The energy grid is the kinetic energy in MeV - of the proton for PSTAR, of the alpha for
// ASTAR. PSTAR uses the first 60 points, ASTAR all 78. Below 1 keV both scale as sqrt(T),
// which is what Geant4 does.
#pragma once

namespace g4gpu::data {

constexpr int kNistStoppingMaterials = 74;
constexpr int kPstarPoints = 60;
constexpr int kAstarPoints = 78;
/// Below this the stopping power is extrapolated as sqrt(T/emin), as G4PSTARStopping and
/// G4ASTARStopping both do.
constexpr double kNistStoppingEmin = 1.0e-3;  // MeV

HEADER

  printf 'constexpr double kNistStoppingT[78] = {\n'
  flatten "$NIST" "G4double T0[78]" | tr ',' '\n' | grep '[0-9]' \
    | awk '{printf "    %s,\n", $0}'
  printf '};\n\n'

  printf 'constexpr const char* kNistStoppingNames[74] = {\n'
  flatten "$NIST" "G4String nameNIST[74]" | tr ',' '\n' | grep '"' \
    | awk '{printf "    %s,\n", $0}'
  printf '};\n\n'

  printf '/// Materials Geant4 recognises by chemical formula rather than by name, and the\n'
  printf '/// NIST table each maps to. G4BraggModel checks these when the name does not match.\n'
  printf 'constexpr int kNistStoppingMolecula = 12;\n'
  printf 'constexpr const char* kNistMolecularNames[12] = {\n'
  flatten "$NIST" "G4String molecularName[numberO" | tr ',' '\n' | grep '"' \
    | awk '{printf "    %s,\n", $0}'
  printf '};\n'
  printf 'constexpr int kNistMolecularIndex[12] = {\n'
  flatten "$NIST" "G4int molecularIndex[numberO" | tr ',' '\n' | grep '[0-9]' \
    | awk '{printf "    %s,\n", $0}'
  printf '};\n\n'

  printf '/// Proton mass stopping power, MeV cm2/g, on the first 60 grid points.\n'
  printf 'constexpr float kPstarRaw[74][60] = {\n'
  i=0
  while [ $i -lt 74 ]; do
    vals=$(flatten "$PSTAR" "G4float e$i[")
    n=$(nvals "$vals")
    if [ "$n" -ne 60 ]; then echo "PSTAR e$i: $n values, expected 60" >&2; exit 1; fi
    printf '    {%s},\n' "$(echo "$vals" | sed 's/,$//')"
    i=$((i + 1))
  done
  printf '};\n\n'

  printf '/// Alpha mass stopping power, MeV cm2/g, on all 78 grid points.\n'
  printf 'constexpr float kAstarRaw[74][78] = {\n'
  i=0
  while [ $i -lt 74 ]; do
    vals=$(flatten "$ASTAR" "G4float e$i[")
    n=$(nvals "$vals")
    if [ "$n" -ne 78 ]; then echo "ASTAR e$i: $n values, expected 78" >&2; exit 1; fi
    printf '    {%s},\n' "$(echo "$vals" | sed 's/,$//')"
    i=$((i + 1))
  done
  printf '};\n\n'

  printf '}  // namespace g4gpu::data\n'
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
