#!/bin/sh
# Extracts ICRU 90 electronic stopping powers from G4ICRU90StoppingData.cc into
# src/data/icru90_raw.hh, for tools/gen_icru90.cc to spline.
#
#   sh tools/extract_icru90.sh [<geant4 source root>]
#
# The tree comes from tools/g4src.sh, which refuses a version that does not match the oracle
# (docs/RISK.md O7).
#
# Eight arrays: the proton and alpha energy grids (57 and 49 points, non-uniform, in MeV) and
# three stopping-power tables each for G4_AIR, G4_WATER and G4_GRAPHITE, in MeV cm^2/g. Geant4
# holds the stopping powers as `G4float` and converts on the way into the vector, so they are
# read as float here too and widened once - a float literal parsed as double would not be the
# same number.
#
# Every count is asserted. An extraction of the right shape and the wrong data passes every
# other check there is (RISK.md O6), so the values are checked afterwards by
# tools/check_icru90.cc against Geant4's own answers.
set -e
G4=$(sh "$(dirname "$0")/g4src.sh" ${1:+"$1"}) || exit 1
SRC="$G4/source/materials/src/G4ICRU90StoppingData.cc"
OUT="$(dirname "$0")/icru90_raw.hh"
[ -f "$SRC" ] || { echo "no $SRC" >&2; exit 1; }

# Flattens one `... <name>[<n>] = { ... };` initialiser to a comma list, stripping comments.
grab() {
  awk -v want="$1" '
    index($0, want "[") > 0 && index($0, "=") > 0 { on = 1 }
    on {
      l = $0
      sub(/\/\/.*$/, "", l)
      sub(/^[^{]*\{/, "", l)
      if (index(l, "}") > 0) { sub(/\}.*$/, "", l); done = 1 }
      gsub(/[ \t\r]/, "", l)
      gsub(/f,/, ",", l)      # G4float literals: 119.70f -> 119.70
      gsub(/f$/, "", l)
      out = out l
      if (done) { print out; exit }
    }' "$SRC"
}
count() { echo "$1" | tr ',' '\n' | grep -c '[0-9]'; }
wrap() { echo "$1" | tr ',' '\n' | awk 'NF{printf "%s%s", (n%6?" ":(n?"\n    ":"    ")), $0 ", "; ++n} END{print ""}'; }

emit() {  # name expected-count array-name comment
  v=$(grab "$3")
  n=$(count "$v")
  [ "$n" = "$2" ] || { echo "$3 came out with $n values, not $2" >&2; exit 1; }
  printf '/// %s\nconstexpr double %s[%s] = {\n%s};\n\n' "$4" "$1" "$2" "$(wrap "$v")"
}

{
  cat <<HDR
// Generated by tools/extract_icru90.sh from G4ICRU90StoppingData.cc - do not edit.
//
// ICRU Report 90 electronic stopping powers, for the three materials Geant4 tabulates:
// G4_AIR, G4_WATER and G4_GRAPHITE. Energies in MeV, stopping powers in MeV cm^2/g.
//
// Geant4 reads these only when G4EmParameters::SetUseICRU90Data(true) has been called; they
// are off by default, and when they are on they take precedence over PSTAR for those three
// materials (G4BraggModel::ElectronicDEDX resolves iICRU90 first and only falls through to
// iPSTAR when it is negative).
//
// The alpha tables are indexed by *scaled* kinetic energy - the alpha's energy divided by its
// mass ratio to a proton - which is what G4BraggIonModel passes in.
#ifndef G4GPU_DATA_ICRU90_RAW_HH
#define G4GPU_DATA_ICRU90_RAW_HH

namespace g4gpu::data::icru90_raw {

HDR
  emit kProtonGrid 57 T0_proton "Proton kinetic energies, MeV. Non-uniform."
  emit kAlphaGrid 49 T0_alpha "Alpha scaled kinetic energies, MeV. Non-uniform."
  emit kProtonAir 57 e0_proton "G4_AIR, protons, MeV cm^2/g."
  emit kProtonWater 57 e1_proton "G4_WATER, protons."
  emit kProtonGraphite 57 e2_proton "G4_GRAPHITE, protons."
  emit kAlphaAir 49 e0_alpha "G4_AIR, alphas, MeV cm^2/g."
  emit kAlphaWater 49 e1_alpha "G4_WATER, alphas."
  emit kAlphaGraphite 49 e2_alpha "G4_GRAPHITE, alphas."
  cat <<FTR
}  // namespace g4gpu::data::icru90_raw

#endif  // G4GPU_DATA_ICRU90_RAW_HH
FTR
} > "$OUT"
echo "wrote $OUT"
grep -c "constexpr double" "$OUT"
