// Turns the Mott coefficient table and the target nuclear masses into src/data/mott.hh.
//
//   tools/extract_mott.sh   G4MottData.hh          ->  tools/mott_raw.hh
//   ref/dump/g4dump.cc      Geant4, at run time    ->  ref/oracle/mott_target.csv
//   tools/gen_mott.cc       both                   ->  src/data/mott.hh
//
// The coefficients come from Geant4's source, like every other table here. The 92 target
// nuclear masses do not: they come from the oracle CSV, because Geant4 gets them from
// G4NucleiProperties - an AME12 mass table with the Cameron mass-excess formula behind it for
// nuclides the table does not have. Transcribing that to produce 92 numbers would be a
// thousand lines to reach the same values.
//
// Reading them from the oracle would be circular if nothing else checked them. Something does:
// tests/test_mott.cu compares the *ratio* against Geant4's own answers, and the ratio depends
// on the masses through beta. A wrong mass moves the fcost = 0 column, which is why the dump
// includes it.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#ifndef __CUDACC__
#define __host__
#define __device__
#endif

#include "mott_raw.hh"

int main(int argc, char** argv) {
  const char* out_path = (argc > 1) ? argv[1] : "../src/data/mott.hh";
  const char* csv_path = (argc > 2) ? argv[2] : "../ref/oracle/mott_target.csv";

  // ---- the 92 target nuclear masses, from the oracle
  std::vector<double> mass(93, 0.0);
  std::vector<int> nucleons(93, 0);
  int read = 0;
  {
    std::FILE* c = std::fopen(csv_path, "r");
    if (c == nullptr) {
      std::printf("cannot read %s\n", csv_path);
      return 2;
    }
    char line[512];
    if (std::fgets(line, sizeof line, c) == nullptr) {
      std::fclose(c);
      return 2;
    }
    while (std::fgets(line, sizeof line, c) != nullptr) {
      int z = 0, a = 0;
      double amu = 0, m = 0;
      if (std::sscanf(line, "%d,%d,%lf,%lf", &z, &a, &amu, &m) != 4) { continue; }
      if (z < 1 || z > 92) { continue; }
      mass[static_cast<std::size_t>(z)] = m;
      nucleons[static_cast<std::size_t>(z)] = a;
      ++read;
    }
    std::fclose(c);
  }
  if (read != 92) {
    // Not a warning. A short table would leave some Z with a zero mass, beta would come out
    // as 1, and the ratio would be quietly wrong for exactly those elements.
    std::printf("%s gave %d masses, expected 92\n", csv_path, read);
    return 2;
  }

  std::FILE* f = std::fopen(out_path, "w");
  if (f == nullptr) {
    std::printf("cannot write %s\n", out_path);
    return 2;
  }

  std::fprintf(f, "%s",
      "// The Mott-to-Rutherford ratio: G4ScreeningMottCrossSection's rejection function for\n"
      "// electron and positron single scattering.\n"
      "//\n"
      "// GENERATED by tools/gen_mott.cc. Do not edit by hand.\n"
      "//\n"
      "// G4WentzelOKandVIxSection makes one of these for e- and e+ unconditionally - the\n"
      "// comment in Geant4 reads \"Mott corrections always added\" - and uses the ratio in\n"
      "// place of the analytic Rutherford-plus-spin expression when it samples a single\n"
      "// scatter. Every other particle keeps the analytic form. So this is not an optional\n"
      "// refinement: for e+- it *is* the single-scattering angular distribution.\n"
      "//\n"
      "// Two tables. The coefficients are Geant4's own, from G4MottData.hh. The 92 target\n"
      "// nuclear masses are read out of the oracle, because Geant4 takes them from\n"
      "// G4NucleiProperties - an AME12 mass table with a mass-excess formula behind it - and\n"
      "// what this needs from all of that is 92 numbers. They are checked through the ratio:\n"
      "// beta depends on the target mass, and the ratio depends on beta.\n"
      "#pragma once\n"
      "#include <cmath>\n"
      "\n"
      "namespace g4gpu::data {\n"
      "\n"
      "/// Nuclear mass in MeV of the isotope Geant4 picks for element Z: the one whose\n"
      "/// nucleon count is the rounded standard atomic weight. Z runs 1..92; index 0 is zero\n"
      "/// and Z above 92 is clamped to 92, as G4ScreeningMottCrossSection::SetupKinematic\n"
      "/// does with `std::min(92, Z)`.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline real_t mott_target_mass(int z) {\n"
      "  static const real_t v[93] = {\n");
  for (int z = 0; z <= 92; ++z) {
    std::fprintf(f, "%sreal_t(%.17g)%s", (z % 4 == 0) ? "    " : " ", mass[z],
                 (z < 92) ? "," : "");
    if (z % 4 == 3 || z == 92) { std::fprintf(f, "\n"); }
  }
  std::fprintf(f, "%s",
      "  };\n"
      "  if (z < 1) { return real_t(0); }\n"
      "  return v[(z > 92) ? 92 : z];\n"
      "}\n"
      "\n"
      "/// Nucleon count for element Z, the rounded standard atomic weight. Emitted alongside\n"
      "/// the masses so a reader can see which isotope each mass belongs to.\n"
      "__host__ __device__ inline int mott_target_nucleons(int z) {\n"
      "  static const int v[93] = {\n");
  for (int z = 0; z <= 92; ++z) {
    std::fprintf(f, "%s%d%s", (z % 16 == 0) ? "    " : " ", nucleons[z], (z < 92) ? "," : "");
    if (z % 16 == 15 || z == 92) { std::fprintf(f, "\n"); }
  }
  std::fprintf(f, "%s",
      "  };\n"
      "  if (z < 1) { return 0; }\n"
      "  return v[(z > 92) ? 92 : z];\n"
      "}\n"
      "\n"
      "/// The 5x6 coefficient matrix for element Z, flattened as [j*6 + k]. Z = 0 is all\n"
      "/// zeros, which is Geant4's row 0.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline const real_t* mott_coef(int z) {\n"
      "  static const real_t v[93][30] = {\n");
  for (int z = 0; z <= 92; ++z) {
    std::fprintf(f, "    {");
    for (int i = 0; i < 30; ++i) {
      std::fprintf(f, "real_t(%.17g)%s",
                   g4gpu::data::mott_raw::kMottCoef[static_cast<std::size_t>(z) * 30 + i],
                   (i < 29) ? "," : "");
    }
    std::fprintf(f, "}%s\n", (z < 92) ? "," : "");
  }
  std::fprintf(f, "%s",
      "  };\n"
      "  if (z < 1) { return v[0]; }\n"
      "  return v[(z > 92) ? 92 : z];\n"
      "}\n"
      "\n"
      "/// beta of the projectile-nucleus relative system, from\n"
      "/// G4ScreeningMottCrossSection::SetupKinematic.\n"
      "///\n"
      "/// Not the lab beta. Geant4 works in the relative system, with the relativistic\n"
      "/// reduced mass of Martynenko and Faustov, Teoret. mat. Fiz. 64 (1985) 179:\n"
      "///\n"
      "///     Ecm    = sqrt(m^2 + M^2 + 2 E M)\n"
      "///     mu_rel = m M / Ecm\n"
      "///     momCM  = p M / Ecm\n"
      "///     beta   = 1 / sqrt(1 + mu_rel^2 / momCM^2)\n"
      "///\n"
      "/// with m the projectile mass, M the target nuclear mass, E and p its lab total energy\n"
      "/// and momentum. For an electron on a heavy nucleus this is close to the lab beta and\n"
      "/// on hydrogen it is not, which is why the target mass has to be right.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline real_t mott_beta(int z, real_t kinetic, real_t mass) {\n"
      "  const real_t target = mott_target_mass<real_t>(z);\n"
      "  if (target <= real_t(0) || kinetic <= real_t(0)) { return real_t(0); }\n"
      "  const real_t mom_lab2 = kinetic * (kinetic + real_t(2) * mass);\n"
      "  const real_t etot = kinetic + mass;\n"
      "  const real_t ptot = sqrt(mom_lab2);\n"
      "  const real_t ecm =\n"
      "      sqrt(mass * mass + target * target + real_t(2) * etot * target);\n"
      "  const real_t mu_rel = mass * target / ecm;\n"
      "  const real_t mom_cm = ptot * target / ecm;\n"
      "  const real_t mom2 = mom_cm * mom_cm;\n"
      "  if (mom2 <= real_t(0)) { return real_t(0); }\n"
      "  return sqrt(real_t(1) / (real_t(1) + mu_rel * mu_rel / mom2));\n"
      "}\n"
      "\n"
      "/// The Mott/Rutherford ratio, verbatim from\n"
      "/// G4ScreeningMottCrossSection::RatioMottRutherfordCosT.\n"
      "///\n"
      "/// @param fcost sqrt(1 - cos(theta)), which is what the sampler passes: sqrt(z1).\n"
      "///\n"
      "/// A double polynomial - order 5 in (beta - 0.7181228) and order 4 in fcost - fitted\n"
      "/// per element. The 0.7181228 shift is Geant4's; it centres the beta expansion on the\n"
      "/// region the fit was made in, and using beta itself would give a different answer.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline real_t mott_ratio(int z, real_t beta, real_t fcost) {\n"
      "  const real_t* c = mott_coef<real_t>(z);\n"
      "  constexpr real_t kShift = real_t(0.7181228);\n"
      "  const real_t beta0 = beta - kShift;\n"
      "  real_t b[6];\n"
      "  real_t p = real_t(1);\n"
      "  for (int k = 0; k < 6; ++k) {\n"
      "    b[k] = p;\n"
      "    p *= beta0;\n"
      "  }\n"
      "  real_t r = real_t(0);\n"
      "  real_t f = real_t(1);\n"
      "  for (int j = 0; j <= 4; ++j) {\n"
      "    real_t a = real_t(0);\n"
      "    for (int k = 0; k <= 5; ++k) { a += c[j * 6 + k] * b[k]; }\n"
      "    r += a * f;\n"
      "    f *= fcost;\n"
      "  }\n"
      "  return r;\n"
      "}\n"
      "\n"
      "}  // namespace g4gpu::data\n");
  std::fclose(f);
  std::printf("wrote %s (%d target masses, 2790 coefficients)\n", out_path, read);
  return 0;
}
