# Writes one translation unit per stepping kernel for a project's own step hook, plus the
# header of `extern template` declarations that keeps those kernels out of the project's own
# object.
#
# WHY THIS EXISTS. docs/RISK.md V65 split the engine because one translation unit holding all
# eighteen stepping kernels takes 25 minutes and, with the Urban ion branch live, kills ptxas
# outright. A project with its own hook type has exactly the same file: `tests/test_custom_hook.cu`
# instantiates `TransportEngine<double, QualityFactorScoring>` and the eighteen launches inside
# BeamOn instantiate eighteen kernels into it. Splitting the ENGINE did nothing for that unit,
# because its kernels are a different specialisation - the hook type is a template parameter -
# so it died the same way, from the same cause, through a different door.
#
# THE KERNEL LIST IS READ OUT OF transport_run_impl.cuh RATHER THAN WRITTEN HERE, and that is
# the point of doing this in a script at all. The stock engine's `extern template` block is the
# one place that knows which kernels exist; a copy of that list here would be right on the day
# it was written and silently wrong the first time a species was added - the new kernel would
# have no unit, no declaration, and would quietly go back to being instantiated in the project's
# own object, which is the failure this whole mechanism exists to prevent. So the block is
# parsed, and the only substitution is the hook type for StepTap<double>.
#
#   -ImplHeader   src\host\transport_run_impl.cuh - the source of truth for the kernel list
#   -HookHeader   the project's header that DEFINES the hook class (included by every unit)
#   -HookType     the type name, exactly as the project writes it
#   -OutDir       where to write the units and hook_kernels.cuh
param(
  [Parameter(Mandatory = $true)][string]$ImplHeader,
  [Parameter(Mandatory = $true)][string]$HookHeader,
  [Parameter(Mandatory = $true)][string]$HookType,
  [Parameter(Mandatory = $true)][string]$OutDir
)
$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $ImplHeader)) { Write-Output "FATAL: no $ImplHeader"; exit 1 }
if (-not (Test-Path -LiteralPath $HookHeader)) { Write-Output "FATAL: no $HookHeader"; exit 1 }
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# The hook header is included by absolute path. The units live in out\, not beside the project,
# and giving build_engine_unit.bat a second -I for every hook would mean a different compile
# line per project; an absolute path in a generated file that is regenerated on every build has
# no such cost and cannot resolve to the wrong header.
$hookAbs = (Resolve-Path -LiteralPath $HookHeader).Path -replace '\\', '/'

$kernels = @()
foreach ($line in Get-Content -LiteralPath $ImplHeader) {
  if ($line -match '^\s*extern template\s+(G4GPU_STEP_\w+)\((.*)\);\s*$') {
    $macro = $Matches[1]
    $karg  = $Matches[2]
    # The stock hook is the last argument. Replacing it by name rather than by position keeps
    # this honest if an argument is ever added in front of it.
    if ($karg -notmatch 'StepTap<\s*double\s*>') {
      Write-Output "FATAL: '$line' does not name StepTap<double>; this script cannot rewrite it."
      exit 1
    }
    $hookArgs = $karg -replace 'StepTap<\s*double\s*>', $HookType
    # A unit name that says what is in it: gamma, lepton_true, hadron_kGenericIon, ...
    $tag = $macro -replace '^G4GPU_STEP_', ''
    $rest = ($karg -replace ',?\s*StepTap<\s*double\s*>\s*$', '').Trim()
    $rest = $rest -replace '^ParticleType::', '' -replace '[^A-Za-z0-9_]', ''
    $name = if ($rest -eq '') { $tag.ToLower() } else { ($tag.ToLower() + '_' + $rest) }
    $kernels += [pscustomobject]@{ Name = $name; Macro = $macro; Args = $hookArgs }
  }
}

# A list that came out short is the failure mode this script must not have: fewer units than
# kernels links cleanly for the ones it has and fails at link time for the rest, which is
# survivable - but an EMPTY list would emit no declarations at all and put every kernel back in
# the project's object, which is the 25-minute unit this exists to abolish, silently.
if ($kernels.Count -lt 10) {
  Write-Output "FATAL: parsed only $($kernels.Count) kernels out of $ImplHeader."
  Write-Output "       The 'extern template G4GPU_STEP_*(...);' block is what this reads."
  exit 1
}

foreach ($k in $kernels) {
  $body = @"
// GENERATED by tools\gen_hook_units.ps1 - do not edit; every build overwrites it.
//
// One stepping kernel for one project hook type, in a translation unit of its own, which is
// the shape docs/RISK.md V65 measured to be the only one ptxas compiles for every arrangement
// of this physics. The project's own .cu declares the same kernel `extern template` (see
// hook_kernels.cuh beside this file) and therefore no longer instantiates it.
#include "$hookAbs"
#include "host/transport_run_impl.cuh"

namespace g4gpu::host {

template $($k.Macro)($($k.Args));

}  // namespace g4gpu::host
"@
  $unit = Join-Path $OutDir ("hook_" + $k.Name + ".cu")
  Set-Content -LiteralPath $unit -Value $body -Encoding ASCII
}

$decls = ($kernels | ForEach-Object { "extern template $($_.Macro)($($_.Args));" }) -join "`n"
$header = @"
// GENERATED by tools\gen_hook_units.ps1 - do not edit; every build overwrites it.
//
// The declarations that keep this project's stepping kernels out of the object that launches
// them. Include it AFTER host/transport_run_impl.cuh and after the hook class is defined: it
// is written against that header's G4GPU_STEP_* macros, so that a parameter added to a kernel
// cannot leave a declaration here disagreeing with the definition in the unit beside it.
//
// Without this include the project compiles - and instantiates all $($kernels.Count) kernels
// into its own translation unit, which takes 25 minutes when it works and kills ptxas when it
// does not. docs/RISK.md V65.
#ifndef G4GPU_STEP_GAMMA
#error "include host/transport_run_impl.cuh before hook_kernels.cuh"
#endif

namespace g4gpu::host {

$decls

}  // namespace g4gpu::host
"@
Set-Content -LiteralPath (Join-Path $OutDir 'hook_kernels.cuh') -Value $header -Encoding ASCII
Write-Output "$($kernels.Count)"
