// Reshapes tools/barashenkov_raw.hh into src/data/barashenkov.hh, the device-side form.
//
//   nvcc -std=c++17 -O2 -o tools/gen_barashenkov.exe tools/gen_barashenkov.cc
//   tools/gen_barashenkov.exe
//
// The raw header is 57 separate arrays of three different lengths sharing six energy grids,
// which is how a host-side G4PiData vector-of-pairs wants them and not how a kernel does. This
// flattens them into five parallel arrays indexed by one running offset, so a device lookup is
// two integer loads and a linear scan rather than a pointer chase.
//
// It also fixes the units once, here, rather than at every call site: energies to MeV and
// cross sections to mm^2, which are the port's units throughout. Geant4 writes GeV and
// millibarn and applies CLHEP's factors in the G4PiData constructor.
//
// The element order is G4ComponentBarNucleonNucleusXsc::LoadData's, and so is the element to
// energy-grid mapping. Both are asserted below against the Z list that file declares, because
// getting the mapping wrong would put oxygen's cross sections on nitrogen's energy grid - the
// two grids differ, the numbers would still be plausible, and nothing downstream could tell.
#include <cstdio>
#include <cstdlib>

#include "barashenkov_raw.hh"

using namespace g4gpu::data::barashenkov_raw;

namespace {

struct Element {
  const char* name;
  int z;
  const double* total;    // shared by proton and neutron
  const double* inel_n;
  const double* inel_p;
  const double* energy;
  int n;
};

// LoadData's order, which is ascending in Z; the Z list is
// G4ComponentBarNucleonNucleusXsc::theZ and the lookup below relies on it being sorted.
const Element kElements[] = {
    {"He", 2, he_m_t, he_m_in, he_p_in, e1, 44},
    {"Be", 4, be_m_t, be_m_in, be_p_in, e1, 44},
    {"C", 6, c_m_t, c_m_in, c_p_in, e1, 44},
    {"N", 7, n_m_t, n_m_in, n_p_in, e2, 44},
    {"O", 8, o_m_t, o_m_in, o_p_in, e2, 44},
    {"Na", 11, na_m_t, na_m_in, na_p_in, e2, 44},
    {"Al", 13, al_m_t, al_m_in, al_p_in, e3, 45},
    {"Si", 14, si_m_t, si_m_in, si_p_in, e3, 45},
    {"Ca", 20, ca_m_t, ca_m_in, ca_p_in, e3, 45},
    {"Fe", 26, fe_m_t, fe_m_in, fe_p_in, e4, 47},
    {"Cu", 29, cu_m_t, cu_m_in, cu_p_in, e4, 47},
    {"Mo", 42, mo_m_t, mo_m_in, mo_p_in, e4, 47},
    {"Cd", 48, cd_m_t, cd_m_in, cd_p_in, e5, 48},
    {"Sn", 50, sn_m_t, sn_m_in, sn_p_in, e5, 48},
    {"W", 74, w_m_t, w_m_in, w_p_in, e5, 48},
    {"Pb", 82, pb_m_t, pb_m_in, pb_p_in, e6, 46},
    {"U", 92, u_m_t, u_m_in, u_p_in, e6, 46},
};
constexpr int kNZ = static_cast<int>(sizeof kElements / sizeof kElements[0]);

// Geant4's own theZ, repeated so the mapping above can be checked against it rather than
// trusted. A transposed pair here is invisible in every downstream number.
const int kTheZ[kNZ] = {2, 4, 6, 7, 8, 11, 13, 14, 20, 26, 29, 42, 48, 50, 74, 82, 92};

}  // namespace

int main() {
  int total_points = 0;
  for (int i = 0; i < kNZ; ++i) {
    if (kElements[i].z != kTheZ[i]) {
      std::printf("element %d is Z=%d, G4ComponentBarNucleonNucleusXsc::theZ says %d\n", i,
                  kElements[i].z, kTheZ[i]);
      return 1;
    }
    if (i > 0 && kElements[i].z <= kElements[i - 1].z) {
      std::printf("Z is not ascending at index %d\n", i);
      return 1;
    }
    total_points += kElements[i].n;
  }

  FILE* f = std::fopen("src/data/barashenkov.hh", "w");
  if (f == nullptr) {
    std::printf("cannot write src/data/barashenkov.hh - run from the repository root\n");
    return 1;
  }

  std::fprintf(f, "%s",
      "// Generated by tools/gen_barashenkov.exe from tools/barashenkov_raw.hh - do not edit.\n"
      "//\n"
      "// Barashenkov's nucleon-nucleus total and inelastic cross sections: seventeen elements\n"
      "// from helium to uranium, 14 MeV to 1 TeV. These are what G4ComponentBarNucleonNucleusXsc\n"
      "// interpolates, and so what every nucleon elastic and inelastic cross section in QBBC\n"
      "// rests on between 14 MeV and 91 GeV.\n"
      "//\n"
      "// Flattened: one running offset indexes four parallel arrays, so a lookup is two integer\n"
      "// loads and a scan. Energies are MeV and cross sections mm^2 - converted here rather than\n"
      "// at the call sites, since Geant4 writes GeV and millibarn and applies the factors in the\n"
      "// G4PiData constructor.\n"
      "//\n"
      "// The elastic cross section is not tabulated anywhere: it is total minus inelastic, which\n"
      "// is how Geant4 forms it too.\n"
      "#pragma once\n"
      "\n"
      "namespace g4gpu::data::barashenkov {\n"
      "\n");

  std::fprintf(f, "constexpr int kNZ = %d;\n", kNZ);
  std::fprintf(f, "constexpr int kNPoints = %d;\n\n", total_points);

  std::fprintf(f, "/// Tabulated atomic numbers, ascending. A target Z between two of these is\n");
  std::fprintf(f, "/// interpolated in A; outside the range it is clamped to 92.\n");
  std::fprintf(f, "__host__ __device__ inline const int* z() {\n  static const int v[kNZ] = {");
  for (int i = 0; i < kNZ; ++i) { std::fprintf(f, "%s%d", i ? ", " : "", kElements[i].z); }
  std::fprintf(f, "};\n  return v;\n}\n\n");

  std::fprintf(f, "/// Points per element, and where each element's run starts.\n");
  std::fprintf(f, "__host__ __device__ inline const int* npoints() {\n  static const int v[kNZ] = {");
  for (int i = 0; i < kNZ; ++i) { std::fprintf(f, "%s%d", i ? ", " : "", kElements[i].n); }
  std::fprintf(f, "};\n  return v;\n}\n\n");

  std::fprintf(f, "__host__ __device__ inline const int* offset() {\n  static const int v[kNZ] = {");
  {
    int off = 0;
    for (int i = 0; i < kNZ; ++i) {
      std::fprintf(f, "%s%d", i ? ", " : "", off);
      off += kElements[i].n;
    }
  }
  std::fprintf(f, "};\n  return v;\n}\n\n");

  // The four value arrays. Energies GeV -> MeV; cross sections millibarn -> mm^2.
  // 1 millibarn = 1e-3 barn = 1e-3 * 1e-22 mm^2 = 1e-25 mm^2.
  struct Column {
    const char* fn;
    const char* doc;
    int which;  // 0 energy, 1 total, 2 inel_n, 3 inel_p
  };
  const Column cols[] = {
      {"energy", "Kinetic energy, MeV.", 0},
      {"total", "Total cross section, mm^2. Shared by protons and neutrons.", 1},
      {"inelastic_n", "Neutron inelastic cross section, mm^2.", 2},
      {"inelastic_p", "Proton inelastic cross section, mm^2.", 3},
  };
  for (const Column& c : cols) {
    std::fprintf(f, "/// %s\n", c.doc);
    std::fprintf(f, "__host__ __device__ inline const double* %s() {\n", c.fn);
    std::fprintf(f, "  static const double v[kNPoints] = {\n");
    int col = 0;
    for (int i = 0; i < kNZ; ++i) {
      const Element& e = kElements[i];
      for (int k = 0; k < e.n; ++k) {
        double x = 0;
        switch (c.which) {
          case 0: x = e.energy[k] * 1e3; break;          // GeV -> MeV
          case 1: x = e.total[k] * 1e-25; break;         // mb  -> mm^2
          case 2: x = e.inel_n[k] * 1e-25; break;
          default: x = e.inel_p[k] * 1e-25; break;
        }
        std::fprintf(f, "%s%.17g,", (col % 4 == 0) ? "\n      " : " ", x);
        ++col;
      }
    }
    std::fprintf(f, "\n  };\n  return v;\n}\n\n");
  }

  std::fprintf(f, "%s", "}  // namespace g4gpu::data::barashenkov\n");
  std::fclose(f);
  std::printf("wrote src/data/barashenkov.hh: %d elements, %d points per column\n", kNZ,
              total_points);
  return 0;
}
