// Turns the raw NIST stopping tables into the two headers the transport uses.
//
//   tools/extract_stopping.sh   Geant4's sources  ->  tools/nist_stopping_raw.hh
//   tools/gen_stopping.cc       that              ->  src/data/nist_stopping_names.hh
//                                                     src/data/nist_stopping.hh
//
// Two generator steps because the second derivatives of a cubic spline are a tridiagonal
// solve, and there is nowhere good to do it at runtime: the device cannot, and doing it on the
// host at upload time would mean carrying 20,000 more doubles through the upload path for a
// quantity that never changes. Computed here, once, and emitted as data.
//
// Two *output* headers because of compile time, not tidiness. The names and the energy grid
// are needed wherever a material is built - materials.cuh, G4Material.hh, nist_materials.hh -
// and are a couple of hundred lines. The tables are 370 kB and are needed only by
// physics/em/bragg.cuh. One header would have put the 370 kB into every translation unit.
//
// Run tools/regen_stopping.sh rather than this directly: it extracts, *recompiles this*, and
// then checks the result against Geant4's own answers, in that order and for good reasons.
#include <cstdio>
#include <vector>

// Compiled as plain C++. The spline header is __host__ __device__ because the transport needs
// it on both sides; this generator uses only the host half, so the qualifiers are defined
// away rather than dragging in the CUDA toolchain to run a code generator.
#ifndef __CUDACC__
#define __host__
#define __device__
#endif

#include "data/g4spline.hh"
#include "nist_stopping_raw.hh"

using namespace g4gpu::data;

int main(int argc, char** argv) {
  const char* names_path = (argc > 1) ? argv[1] : "../src/data/nist_stopping_names.hh";
  const char* tables_path = (argc > 2) ? argv[2] : "../src/data/nist_stopping.hh";

  // ---------------------------------------------------------------- names header
  {
    std::FILE* f = std::fopen(names_path, "w");
    if (f == nullptr) {
      std::printf("cannot write %s\n", names_path);
      return 2;
    }
    std::fprintf(f, "%s",
        "// The NIST stopping-power material list, and the two lookups that turn a material\n"
        "// into a row in it.\n"
        "//\n"
        "// GENERATED by tools/gen_stopping.cc. Do not edit by hand.\n"
        "//\n"
        "// Separate from nist_stopping.hh, which holds the tables themselves, because this is\n"
        "// needed wherever a material is built and that one is 370 kB and needed only by\n"
        "// physics/em/bragg.cuh.\n"
        "#pragma once\n"
        "#include <cstring>\n"
        "\n"
        "namespace g4gpu::data {\n"
        "\n");

    std::fprintf(f, "constexpr int kNistStoppingMaterials = %d;\n", kNistStoppingMaterials);
    std::fprintf(f, "constexpr int kPstarPoints = %d;\n", kPstarPoints);
    std::fprintf(f, "constexpr int kAstarPoints = %d;\n", kAstarPoints);
    std::fprintf(f,
        "/// Below this the stopping power is extrapolated as sqrt(T/emin), as\n"
        "/// G4PSTARStopping and G4ASTARStopping both do.\n"
        "constexpr double kNistStoppingEmin = %.17g;  // MeV\n\n", kNistStoppingEmin);

    std::fprintf(f,
        "/// The 74 NIST materials, in table order. G4PSTARStopping matches on these names.\n");
    std::fprintf(f, "constexpr const char* const kNistStoppingNames[%d] = {\n",
                 kNistStoppingMaterials);
    for (int i = 0; i < kNistStoppingMaterials; ++i) {
      std::fprintf(f, "    \"%s\",\n", kNistStoppingNames[i]);
    }
    std::fprintf(f, "};\n\n");

    std::fprintf(f,
        "/// Kinetic energy grid, MeV. PSTAR uses the first %d points, ASTAR all %d.\n",
        kPstarPoints, kAstarPoints);
    std::fprintf(f,
        "template <typename real_t> __host__ __device__ inline const real_t* nist_energies() {\n"
        "  static const real_t v[%d] = {\n", kAstarPoints);
    for (int i = 0; i < kAstarPoints; ++i) {
      std::fprintf(f, "%sreal_t(%.17g)", (i % 5 == 0) ? "      " : ", ", kNistStoppingT[i]);
      if (i % 5 == 4) { std::fprintf(f, ",\n"); }
    }
    std::fprintf(f, "};\n  return v;\n}\n\n");

    std::fprintf(f, "%s",
        "/// The row in the PSTAR and ASTAR tables for a material named @p name, or -1.\n"
        "///\n"
        "/// Host only, and called once per material when the material is built: an exact\n"
        "/// string match against 74 names, which is the first half of\n"
        "/// G4PSTARStopping::Initialise.\n"
        "inline int nist_stopping_index(const char* name) {\n"
        "  if (name == nullptr) { return -1; }\n"
        "  for (int i = 0; i < kNistStoppingMaterials; ++i) {\n"
        "    if (std::strcmp(name, kNistStoppingNames[i]) == 0) { return i; }\n"
        "  }\n"
        "  return -1;\n"
        "}\n"
        "\n");

    std::fprintf(f, "%s",
        "/// Chemical formulae G4PSTARStopping recognises when a material's *name* is not one\n"
        "/// of the 74, and the NIST row each resolves to.\n"
        "///\n"
        "/// This is the second half of G4PSTARStopping::Initialise, and it matters more than\n"
        "/// it looks. G4BraggModel has its own eleven-compound list with its own ICRU 49\n"
        "/// parameterisation for exactly these formulae, and that branch is unreachable - in\n"
        "/// Geant4 as much as here - because this list is a superset of it and resolves first,\n"
        "/// to a table. A material called \"MyWater\" with the formula \"H_2O\" gets G4_WATER's\n"
        "/// tabulated stopping power, not a fit. Measured: tests/test_bragg.cu builds exactly\n"
        "/// that material and the oracle dumps Geant4's answer for it.\n");
    std::fprintf(f, "constexpr int kNistFormulae = %d;\n", kNistStoppingMolecula);
    std::fprintf(f, "constexpr const char* const kNistFormulaNames[%d] = {\n",
                 kNistStoppingMolecula);
    for (int i = 0; i < kNistStoppingMolecula; ++i) {
      std::fprintf(f, "    \"%s\",\n", kNistMolecularNames[i]);
    }
    std::fprintf(f, "};\n");
    std::fprintf(f, "constexpr int kNistFormulaRow[%d] = {", kNistStoppingMolecula);
    for (int i = 0; i < kNistStoppingMolecula; ++i) {
      std::fprintf(f, "%s%d", (i > 0) ? ", " : "", kNistMolecularIndex[i]);
    }
    std::fprintf(f, "};\n\n");

    std::fprintf(f, "%s",
        "/// The NIST row a chemical formula resolves to, or -1. Host only.\n"
        "inline int nist_stopping_index_by_formula(const char* formula) {\n"
        "  if (formula == nullptr || formula[0] == 0) { return -1; }\n"
        "  for (int i = 0; i < kNistFormulae; ++i) {\n"
        "    if (std::strcmp(formula, kNistFormulaNames[i]) == 0) { return kNistFormulaRow[i]; }\n"
        "  }\n"
        "  return -1;\n"
        "}\n"
        "\n"
        "}  // namespace g4gpu::data\n");
    std::fclose(f);
    std::printf("wrote %s\n", names_path);
  }

  // ---------------------------------------------------------------- tables header
  std::FILE* f = std::fopen(tables_path, "w");
  if (f == nullptr) {
    std::printf("cannot write %s\n", tables_path);
    return 2;
  }

  std::fprintf(f, "%s",
      "// PSTAR and ASTAR stopping powers, with the second derivatives of Geant4's spline.\n"
      "//\n"
      "// GENERATED by tools/gen_stopping.cc from tools/nist_stopping_raw.hh, which is itself\n"
      "// generated by tools/extract_stopping.sh from Geant4 11.1.1's sources. Do not edit by\n"
      "// hand.\n"
      "//\n"
      "// The tables are the published PSTAR (proton) and ASTAR (alpha) tabulations, in\n"
      "// MeV cm2/g against kinetic energy in MeV - a *mass* stopping power, so a dE/dx in\n"
      "// MeV/mm is the table value times the density in g/cm3, divided by ten.\n"
      "//\n"
      "// Geant4 loads them into a G4PhysicsFreeVector with spline interpolation, so\n"
      "// reproducing its numbers between the grid points needs the spline as well as the\n"
      "// table: the grids are 60 and 78 points across a Bragg peak, where linear\n"
      "// interpolation is low in the curvature and high on the flanks. The second derivatives\n"
      "// are the not-a-knot ones from G4PhysicsVector::ComputeSecDerivative1.\n"
      "//\n"
      "// Accessors rather than plain arrays, following data/icru73qo_tables.cuh: a\n"
      "// function-local static in a __host__ __device__ function is how this project carries a\n"
      "// large constant table to both sides of the machine.\n"
      "#pragma once\n"
      "#include \"data/g4spline.hh\"\n"
      "#include \"data/nist_stopping_names.hh\"\n"
      "\n"
      "namespace g4gpu::data {\n"
      "\n");

  struct Set {
    const char* name;
    const char* what;
    int n;
    const float* rows;  // [74][n], row-major
  };
  const Set sets[2] = {
      {"pstar", "Proton", kPstarPoints, &kPstarRaw[0][0]},
      {"astar", "Alpha", kAstarPoints, &kAstarRaw[0][0]},
  };

  for (const Set& s : sets) {
    std::vector<double> x(static_cast<std::size_t>(s.n));
    for (int i = 0; i < s.n; ++i) { x[static_cast<std::size_t>(i)] = kNistStoppingT[i]; }

    std::fprintf(f,
        "/// %s mass stopping power, MeV cm2/g, one row per NIST material.\n"
        "template <typename real_t> __host__ __device__ inline const real_t* %s_row(int i) {\n"
        "  static const real_t v[%d][%d] = {\n",
        s.what, s.name, kNistStoppingMaterials, s.n);
    for (int m = 0; m < kNistStoppingMaterials; ++m) {
      std::fprintf(f, "    {");
      for (int i = 0; i < s.n; ++i) {
        std::fprintf(f, "%sreal_t(%.9g)", (i > 0) ? "," : "",
                     static_cast<double>(s.rows[m * s.n + i]));
      }
      std::fprintf(f, "},\n");
    }
    std::fprintf(f, "  };\n  return v[(i < 0 || i >= %d) ? 0 : i];\n}\n\n",
                 kNistStoppingMaterials);

    std::fprintf(f,
        "/// Not-a-knot second derivatives of the %s rows above, for Geant4's spline.\n"
        "template <typename real_t> __host__ __device__ inline const real_t* %s_d2(int i) {\n"
        "  static const real_t v[%d][%d] = {\n",
        s.what, s.name, kNistStoppingMaterials, s.n);
    for (int m = 0; m < kNistStoppingMaterials; ++m) {
      std::vector<double> y(static_cast<std::size_t>(s.n));
      for (int i = 0; i < s.n; ++i) {
        y[static_cast<std::size_t>(i)] = static_cast<double>(s.rows[m * s.n + i]);
      }
      std::vector<double> d2(static_cast<std::size_t>(s.n), 0.0);
      fill_second_derivatives(x.data(), y.data(), s.n, d2.data());
      std::fprintf(f, "    {");
      for (int i = 0; i < s.n; ++i) {
        std::fprintf(f, "%sreal_t(%.9g)", (i > 0) ? "," : "", d2[static_cast<std::size_t>(i)]);
      }
      std::fprintf(f, "},\n");
    }
    std::fprintf(f, "  };\n  return v[(i < 0 || i >= %d) ? 0 : i];\n}\n\n",
                 kNistStoppingMaterials);
  }

  std::fprintf(f, "%s",
      "/// Mass stopping power from a table row and its second derivatives, MeV cm2/g.\n"
      "///\n"
      "/// Verbatim from G4PSTARStopping::GetElectronicDEDX and its ASTAR twin, including the\n"
      "/// sqrt extrapolation below 1 keV - which is not a nicety. Without it the spline runs\n"
      "/// off the end of the table and can go negative, and a negative stopping power makes a\n"
      "/// track gain energy as it slows down.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline real_t nist_mass_stopping(const real_t* row,\n"
      "                                                     const real_t* d2, int n,\n"
      "                                                     real_t t_MeV) {\n"
      "  const real_t emin = static_cast<real_t>(kNistStoppingEmin);\n"
      "  if (t_MeV < emin) { return row[0] * sqrt(t_MeV / emin); }\n"
      "  return spline_value(nist_energies<real_t>(), row, d2, n, t_MeV);\n"
      "}\n"
      "\n"
      "/// Proton electronic stopping power of NIST material @p idx at @p t_MeV, MeV cm2/g.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline real_t pstar_mass_stopping(int idx, real_t t_MeV) {\n"
      "  return nist_mass_stopping(pstar_row<real_t>(idx), pstar_d2<real_t>(idx), kPstarPoints,\n"
      "                            t_MeV);\n"
      "}\n"
      "\n"
      "/// Alpha electronic stopping power of NIST material @p idx at @p t_MeV, MeV cm2/g.\n"
      "template <typename real_t>\n"
      "__host__ __device__ inline real_t astar_mass_stopping(int idx, real_t t_MeV) {\n"
      "  return nist_mass_stopping(astar_row<real_t>(idx), astar_d2<real_t>(idx), kAstarPoints,\n"
      "                            t_MeV);\n"
      "}\n"
      "\n"
      "}  // namespace g4gpu::data\n");
  std::fclose(f);
  std::printf("wrote %s\n", tables_path);
  return 0;
}
