#!/bin/sh
# Re-extracts every physics table this port bakes from a Geant4 source tree, and reports the
# ones it cannot.
#
#   sh tools/refresh_tables.sh [<geant4 source root>]
#   sh tools/refresh_tables.sh --list        inventory only, extract nothing
#
# WHY THIS EXISTS
#
# Three different kinds of Geant4 data end up in this port, and only one of them is a file you
# can download:
#
#   1. G4EMLOW datasets - photoelectric (epics2017/phot), Rayleigh (epics2017/rayl),
#      Seltzer-Berger (brem_SB). These are READ AT RUNTIME from $G4LEDATA. Drop in a new
#      G4EMLOW and this port picks it up; nothing here needs regenerating, and a missing
#      dataset is fatal rather than silent (see host/pe_upload.cuh).
#
#   2. Tables Geant4 hard-codes as C++ literals in its own source - PSTAR, ASTAR, Mott,
#      Barashenkov, Urban's coefficients, Yang's, Ziegler, ICRU73QO, ICRU49 nuclear stopping,
#      the NIST tables. There is no data file to replace: they change when Geant4's *source*
#      changes. Those are what this script re-extracts.
#
#   3. ref/oracle/*.csv - test fixtures. No model reads them.
#
# The problem this solves is not that regenerating is hard; each chain below is already a
# working script. It is that there are eight of them, they have an order, several have a trap
# in that order, and a Geant4 upgrade means remembering which. "Remembering which" is how the
# stopping tables were once extracted from 11.5.0 and checked against an 11.1.1 oracle for most
# of a day - see docs/RISK.md and the comment in tools/regen_stopping.sh.
#
# THE TRAP, since it is shared by three of these chains: the generators #include the raw table
# header they were built from. Re-extracting the raw header and then running the *existing*
# generator binary produces the old tables from the new data, silently and successfully. Every
# chain below recompiles its generator before running it, for that reason.
#
# WHAT THIS SCRIPT CANNOT DO, which is the part worth reading. Eight of the baked tables were
# extracted by a tool that is no longer in the repository, and have no reproducible path from a
# Geant4 source tree. They are listed at the end. Most are still *caught* by an oracle test if
# Geant4 changes them - the test compares against a freshly dumped Geant4, so a stale table
# fails rather than passing - but catching is not regenerating, and a failure there means a
# manual re-transcription.
set -e

HERE="$(dirname "$0")"
ROOT="$HERE/.."
LIST_ONLY=""
G4ARG=""
for a in "$@"; do
  case "$a" in
    --list) LIST_ONLY=1 ;;
    *) G4ARG="$a" ;;
  esac
done

# ---------------------------------------------------------------- inventory
#
# Every generated file under src/data, what produces it, and what checks it. Printed whether or
# not anything is extracted, because the inventory is half the point: it is the answer to "what
# do I have to do after upgrading Geant4".
inventory() {
  echo ""
  echo "=============================================================================="
  echo " src/data - what produces each table, and what checks it"
  echo "=============================================================================="
  echo ""
  echo " REGENERATED BY THIS SCRIPT, from Geant4's source"
  echo "   nist_stopping.hh            regen_stopping.sh     check_pstar (vs bragg.csv)"
  echo "   nist_stopping_names.hh      regen_stopping.sh     check_pstar"
  echo "   icru90.hh                   regen_icru90.sh       test_icru90"
  echo "   mott.hh                     extract+gen_mott      test_mott"
  echo "   barashenkov.hh              extract+gen_barash.   test_nucleon_xs"
  echo "   fermi_velocity.hh           extract_fermi.sh      test_ion_charge"
  echo "   yang_fluctuation.hh         extract_yang.sh       test_ion_fluctuation"
  echo "   rayleigh_angular_tables.cuh extract_rayleigh_ang. test_rayleigh_angular"
  echo ""
  echo " REGENERATED BY THE ORACLE DUMP (ref/oracle/run.bat)"
  echo "   nist_materials.hh           ref/dump/g4dump.cc    test_all_materials"
  echo ""
  echo " READ AT RUNTIME from \$G4LEDATA - nothing to regenerate, replace the dataset"
  echo "   photoelectric_data.cuh      epics2017/phot        test_photoelectric"
  echo "   rayleigh_data.cuh           epics2017/rayl        test_rayleigh"
  echo "   brems_data.cuh              brem_SB               test_brems"
  echo ""
  echo " NO EXTRACTOR - transcribed by a tool that is no longer in the repository."
  echo " A Geant4 upgrade cannot regenerate these. The right-hand column is what would"
  echo " FAIL if Geant4 changed them, which is the only protection they have."
  echo "   urban_msc_tables.cuh        (none)                test_urban_general"
  echo "   ziegler_tables.cuh          (none)                test_bragg"
  echo "   ziegler_ion_tables.cuh      (none)                test_bragg"
  echo "   icru73qo_tables.cuh         (none)                test_icru73qo"
  echo "   nuclear_stopping_table.cuh  (none)                test_nuclear_stopping"
  echo "   em_correction_tables.cuh    (none)                test_corrections"
  echo "   atomic_masses.cuh           (none)                test_constants"
  echo ""
  echo " Every table above now has something that would fail if Geant4 changed it. The last"
  echo " one without - rayleigh_angular_tables.cuh - was given both an extractor and a test,"
  echo " and the test found a live bug on its first run: fFactor was hard-coded nine orders"
  echo " of magnitude wrong, so Rayleigh scattering deflected nothing at all. The table"
  echo " itself turned out to be perfect - the extractor reproduced all 909 hand-transcribed"
  echo " parameters exactly. See docs/RISK.md V9."
  echo ""
  echo " NOT TABLES - algorithms, or computed at build time"
  echo "   g4pow.hh  g4spline.hh  nist_excitation.hh  materials.cuh  production_cuts.cuh"
  echo ""
}

if [ -n "$LIST_ONLY" ]; then
  inventory
  exit 0
fi

# ---------------------------------------------------------------- the tree
#
# Resolved through g4src.sh, never named here. g4src.sh reads G4VERSION_NUMBER from both the
# source tree and the install the oracle links against, and refuses if they differ - which is
# the whole reason a wrong-version extraction cannot get this far.
G4=$(sh "$HERE/g4src.sh" $G4ARG) || exit 1
echo "Geant4 source: $G4"
echo ""

step=0
total=8
next() { step=$((step + 1)); echo ""; echo "[$step/$total] $1"; }

next "NIST stopping powers (PSTAR, ASTAR)  ->  src/data/nist_stopping{,_names}.hh"
sh "$HERE/regen_stopping.sh" "$G4"

next "ICRU 90 stopping  ->  src/data/icru90.hh"
sh "$HERE/regen_icru90.sh" "$G4"

next "Mott coefficients  ->  src/data/mott.hh"
sh "$HERE/extract_mott.sh" "$G4"
# Recompile before running - see THE TRAP above.
g++ -std=c++17 -O2 -I "$HERE" -I "$ROOT/src" -o "$HERE/gen_mott.exe" "$HERE/gen_mott.cc"
# gen_mott defaults its paths relative to tools/, and needs ref/oracle/mott_target.csv:
# the 92 target nuclear masses come from Geant4 at run time (G4NucleiProperties, an AME12
# table with the Cameron formula behind it), not from a source literal, so this one chain
# depends on the oracle having been dumped. Passed explicitly rather than left to the cwd.
( cd "$HERE" && ./gen_mott.exe ../src/data/mott.hh ../ref/oracle/mott_target.csv )

next "Barashenkov nucleon-nucleus cross sections  ->  src/data/barashenkov.hh"
sh "$HERE/extract_barashenkov.sh" "$G4"
g++ -std=c++17 -O2 -I "$HERE" -I "$ROOT/src" -o "$HERE/gen_barashenkov.exe" "$HERE/gen_barashenkov.cc"
( cd "$ROOT" && ./tools/gen_barashenkov.exe )

next "Fermi velocities  ->  src/data/fermi_velocity.hh"
sh "$HERE/extract_fermi.sh" "$G4"

next "Yang ion-fluctuation coefficients  ->  src/data/yang_fluctuation.hh"
( cd "$ROOT" && sh tools/extract_yang.sh )

next "Rayleigh angular fit  ->  src/data/rayleigh_angular_tables.cuh"
sh "$HERE/extract_rayleigh_angular.sh" "$G4"

next "what changed"
if command -v git >/dev/null 2>&1 && ( cd "$ROOT" && git rev-parse --is-inside-work-tree >/dev/null 2>&1 ); then
  ( cd "$ROOT" && git status --short src/data/ ) || true
  echo ""
  echo "  An empty list above means this Geant4 tree produces byte-identical tables to the"
  echo "  ones checked in. That is the expected result when the version has not moved, and"
  echo "  it is worth running for that reason alone: it proves the extractors still work."
else
  echo "  (not a git checkout - diff src/data/ against your previous copy by hand)"
fi

inventory

cat <<'EOT'
==============================================================================
 NEXT, and neither is optional
==============================================================================

 1. Regenerate the oracle. The tables above are checked against Geant4's own
    answers, and those answers come from ref/oracle/*.csv - which were dumped
    by whatever Geant4 was installed at the time.

        ref\dump\build.bat  &&  ref\oracle\run.bat

 2. Run the pipeline. It is the only thing that decides whether the port is
    still correct.

        build_all.bat

 A table that changed between Geant4 versions shows up as a failing test with
 a number attached, which is what you want. A table that changed and has no
 extractor shows up the same way - but fixing it means transcribing by hand.
EOT
