// The naturally occurring isotopes of G4NistElementBuilder, as a predicate.
//
// GENERATED by tools/extract_natural_isotopes.pl from Geant4 11.1.1 - do not edit by hand.
// 311 (Z, A) pairs out of 2908 tabulated isotopes over 107 elements.
//
// G4Evaporation::BreakFragment and G4ExcitationHandler::SortSecondaryFragment ask
// `G4NistManager::GetIsotopeAbundance(Z, A) > 0.0` and use only the sign of the answer: a
// cold fragment that is a natural isotope is released, one that is not goes back into the
// evaporation list. So the abundances are not needed and are not here - only the set.
//
// The second argument is a MASS NUMBER. G4NistManager::GetIsotopeAbundance names it `N` and
// G4NistElementBuilder indexes `relAbundance[A - nFirstIsotope[Z] + idxIsotopes[Z]]` with it,
// but nFirstIsotope[Z] is filled from the `XxN[]` arrays, which hold mass numbers. Both
// callers in the de-excitation module pass A, and they are right to.
#ifndef G4GPU_DATA_NATURAL_ISOTOPES_HH
#define G4GPU_DATA_NATURAL_ISOTOPES_HH

namespace g4gpu::data {

/// G4NistElementBuilder's maxNumElements. `GetIsotopeAbundance` returns zero outside
/// `0 < Z < maxNumElements` whatever the table holds, so the guard is part of the answer.
constexpr int kNistMaxNumElements = 108;

/// The pairs, sorted by Z then A, as `1000*Z + A`.
__host__ __device__ inline const int* natural_isotope_codes() {
  static const int v[311] = {
    // H
    1001,
    1002,
    // He
    2003,
    2004,
    // Li
    3006,
    3007,
    // Be
    4009,
    // B
    5010,
    5011,
    // C
    6012,
    6013,
    // N
    7014,
    7015,
    // O
    8016,
    8017,
    8018,
    // F
    9019,
    // Ne
    10020,
    10021,
    10022,
    // Na
    11023,
    // Mg
    12024,
    12025,
    12026,
    // Al
    13027,
    // Si
    14028,
    14029,
    14030,
    // P
    15031,
    // S
    16032,
    16033,
    16034,
    16036,
    // Cl
    17035,
    17037,
    // Ar
    18036,
    18038,
    18040,
    // K
    19039,
    19040,
    19041,
    // Ca
    20040,
    20042,
    20043,
    20044,
    20046,
    20048,
    // Sc
    21045,
    // Ti
    22046,
    22047,
    22048,
    22049,
    22050,
    // V
    23050,
    23051,
    // Cr
    24050,
    24052,
    24053,
    24054,
    // Mn
    25055,
    // Fe
    26054,
    26056,
    26057,
    26058,
    // Co
    27059,
    // Ni
    28058,
    28060,
    28061,
    28062,
    28064,
    // Cu
    29063,
    29065,
    // Zn
    30064,
    30066,
    30067,
    30068,
    30070,
    // Ga
    31069,
    31071,
    // Ge
    32070,
    32072,
    32073,
    32074,
    32076,
    // As
    33075,
    // Se
    34074,
    34076,
    34077,
    34078,
    34080,
    34082,
    // Br
    35079,
    35081,
    // Kr
    36078,
    36080,
    36082,
    36083,
    36084,
    36086,
    // Rb
    37085,
    37087,
    // Sr
    38084,
    38086,
    38087,
    38088,
    // Y
    39089,
    // Zr
    40090,
    40091,
    40092,
    40094,
    40096,
    // Nb
    41093,
    // Mo
    42092,
    42094,
    42095,
    42096,
    42097,
    42098,
    42100,
    // Tc
    43098,
    // Ru
    44096,
    44098,
    44099,
    44100,
    44101,
    44102,
    44104,
    // Rh
    45103,
    // Pd
    46102,
    46104,
    46105,
    46106,
    46108,
    46110,
    // Ag
    47107,
    47109,
    // Cd
    48106,
    48108,
    48110,
    48111,
    48112,
    48113,
    48114,
    48116,
    // In
    49113,
    49115,
    // Sn
    50112,
    50114,
    50115,
    50116,
    50117,
    50118,
    50119,
    50120,
    50122,
    50124,
    // Sb
    51121,
    51123,
    // Te
    52120,
    52122,
    52123,
    52124,
    52125,
    52126,
    52128,
    52130,
    // I
    53127,
    // Xe
    54124,
    54126,
    54128,
    54129,
    54130,
    54131,
    54132,
    54134,
    54136,
    // Cs
    55133,
    // Ba
    56130,
    56132,
    56134,
    56135,
    56136,
    56137,
    56138,
    // La
    57138,
    57139,
    // Ce
    58136,
    58138,
    58140,
    58142,
    // Pr
    59141,
    // Nd
    60142,
    60143,
    60144,
    60145,
    60146,
    60148,
    60150,
    // Pm
    61145,
    // Sm
    62144,
    62147,
    62148,
    62149,
    62150,
    62152,
    62154,
    // Eu
    63151,
    63153,
    // Gd
    64152,
    64154,
    64155,
    64156,
    64157,
    64158,
    64160,
    // Tb
    65159,
    // Dy
    66156,
    66158,
    66160,
    66161,
    66162,
    66163,
    66164,
    // Ho
    67165,
    // Er
    68162,
    68164,
    68166,
    68167,
    68168,
    68170,
    // Tm
    69169,
    // Yb
    70168,
    70170,
    70171,
    70172,
    70173,
    70174,
    70176,
    // Lu
    71175,
    71176,
    // Hf
    72174,
    72176,
    72177,
    72178,
    72179,
    72180,
    // Ta
    73180,
    73181,
    // W
    74180,
    74182,
    74183,
    74184,
    74186,
    // Re
    75185,
    75187,
    // Os
    76184,
    76186,
    76187,
    76188,
    76189,
    76190,
    76192,
    // Ir
    77191,
    77193,
    // Pt
    78190,
    78192,
    78194,
    78195,
    78196,
    78198,
    // Au
    79197,
    // Hg
    80196,
    80198,
    80199,
    80200,
    80201,
    80202,
    80204,
    // Tl
    81203,
    81205,
    // Pb
    82204,
    82206,
    82207,
    82208,
    // Bi
    83209,
    // Po
    84209,
    // At
    85210,
    // Rn
    86222,
    // Fr
    87223,
    // Ra
    88226,
    // Ac
    89227,
    // Th
    90232,
    // Pa
    91231,
    // U
    92234,
    92235,
    92238,
    // Np
    93237,
    // Pu
    94244,
    // Am
    95243,
    // Cm
    96247,
    // Bk
    97247,
    // Cf
    98251,
    // Es
    99252,
    // Fm
    100257,
    // Md
    101258,
    // No
    102259,
    // Lr
    103262,
    // Rf
    104261,
    // Db
    105262,
    // Sg
    106266,
    // Bh
    107264,
  };
  return v;
}

constexpr int kNumNaturalIsotopes = 311;

/// `G4NistManager::GetIsotopeAbundance(Z, A) > 0.0`. Linear scan: the table is sorted by Z,
/// so the loop stops at the first entry past Z rather than running to the end.
__host__ __device__ inline bool is_natural_isotope(int Z, int A) {
  if (Z <= 0 || Z >= kNistMaxNumElements) { return false; }
  const int code = 1000 * Z + A;
  const int* v = natural_isotope_codes();
  for (int i = 0; i < kNumNaturalIsotopes; ++i) {
    if (v[i] == code) { return true; }
    if (v[i] > code) { return false; }
  }
  return false;
}

}  // namespace g4gpu::data

#endif
