// The NIST stopping-power material list, and the two lookups that turn a material
// into a row in it.
//
// GENERATED by tools/gen_stopping.cc. Do not edit by hand.
//
// Separate from nist_stopping.hh, which holds the tables themselves, because this is
// needed wherever a material is built and that one is 370 kB and needed only by
// physics/em/bragg.cuh.
#pragma once
#include <cstring>

namespace g4gpu::data {

constexpr int kNistStoppingMaterials = 74;
constexpr int kPstarPoints = 60;
constexpr int kAstarPoints = 78;
/// Below this the stopping power is extrapolated as sqrt(T/emin), as
/// G4PSTARStopping and G4ASTARStopping both do.
constexpr double kNistStoppingEmin = 0.001;  // MeV

/// The 74 NIST materials, in table order. G4PSTARStopping matches on these names.
constexpr const char* const kNistStoppingNames[74] = {
    "G4_A-150_TISSUE",
    "G4_ACETYLENE",
    "G4_ADIPOSE_TISSUE_ICRP",
    "G4_Ag",
    "G4_AIR",
    "G4_Al",
    "G4_ALUMINUM_OXIDE",
    "G4_Ar",
    "G4_Au",
    "G4_B-100_BONE",
    "G4_Be",
    "G4_BONE_COMPACT_ICRU",
    "G4_C",
    "G4_GRAPHITE_POROUS",
    "G4_ETHYLENE",
    "G4_C-552",
    "G4_CARBON_DIOXIDE",
    "G4_CALCIUM_FLUORIDE",
    "G4_CERIC_SULFATE",
    "G4_CELLULOSE_NITRATE",
    "G4_BONE_CORTICAL_ICRP",
    "G4_CESIUM_IODIDE",
    "G4_Cu",
    "G4_Fe",
    "G4_FERROUS_SULFATE",
    "G4_Gd",
    "G4_Ge",
    "G4_Pyrex_Glass",
    "G4_H",
    "G4_He",
    "G4_KAPTON",
    "G4_Kr",
    "G4_LITHIUM_TETRABORATE",
    "G4_LITHIUM_FLUORIDE",
    "G4_M3_WAX",
    "G4_MS20_TISSUE",
    "G4_METHANE",
    "G4_Mo",
    "G4_MUSCLE_WITH_SUCROSE",
    "G4_MUSCLE_WITHOUT_SUCROSE",
    "G4_MUSCLE_SKELETAL_ICRP",
    "G4_MUSCLE_STRIATED_ICRU",
    "G4_N",
    "G4_SODIUM_IODIDE",
    "G4_Ne",
    "G4_NYLON-6-6",
    "G4_O",
    "G4_PARAFFIN",
    "G4_Pb",
    "G4_PHOTO_EMULSION",
    "G4_PLASTIC_SC_VINYLTOLUENE",
    "G4_POLYCARBONATE",
    "G4_POLYETHYLENE",
    "G4_MYLAR",
    "G4_PLEXIGLASS",
    "G4_POLYPROPYLENE",
    "G4_POLYSTYRENE",
    "G4_TEFLON",
    "G4_POLYVINYL_CHLORIDE",
    "G4_PROPANE",
    "G4_Pt",
    "G4_Si",
    "G4_SILICON_DIOXIDE",
    "G4_STILBENE",
    "G4_Ti",
    "G4_Sn",
    "G4_TISSUE-METHANE",
    "G4_TISSUE-PROPANE",
    "G4_TOLUENE",
    "G4_U",
    "G4_W",
    "G4_WATER",
    "G4_WATER_VAPOR",
    "G4_Xe",
};

/// Kinetic energy grid, MeV. PSTAR uses the first 60 points, ASTAR all 78.
template <typename real_t> __host__ __device__ inline const real_t* nist_energies() {
  static const real_t v[78] = {
      real_t(0.001), real_t(0.0015), real_t(0.002), real_t(0.0025000000000000001), real_t(0.0030000000000000001),
      real_t(0.0040000000000000001), real_t(0.0050000000000000001), real_t(0.0060000000000000001), real_t(0.0070000000000000001), real_t(0.0080000000000000002),
      real_t(0.0089999999999999993), real_t(0.01), real_t(0.012500000000000001), real_t(0.014999999999999999), real_t(0.017500000000000002),
      real_t(0.02), real_t(0.022499999999999999), real_t(0.025000000000000001), real_t(0.0275), real_t(0.029999999999999999),
      real_t(0.035000000000000003), real_t(0.040000000000000001), real_t(0.044999999999999998), real_t(0.050000000000000003), real_t(0.055),
      real_t(0.059999999999999998), real_t(0.065000000000000002), real_t(0.070000000000000007), real_t(0.074999999999999997), real_t(0.080000000000000002),
      real_t(0.085000000000000006), real_t(0.089999999999999997), real_t(0.095000000000000001), real_t(0.10000000000000001), real_t(0.125),
      real_t(0.14999999999999999), real_t(0.17499999999999999), real_t(0.20000000000000001), real_t(0.22500000000000001), real_t(0.25),
      real_t(0.27500000000000002), real_t(0.29999999999999999), real_t(0.34999999999999998), real_t(0.40000000000000002), real_t(0.45000000000000001),
      real_t(0.5), real_t(0.55000000000000004), real_t(0.59999999999999998), real_t(0.65000000000000002), real_t(0.69999999999999996),
      real_t(0.75), real_t(0.80000000000000004), real_t(0.84999999999999998), real_t(0.90000000000000002), real_t(0.94999999999999996),
      real_t(1), real_t(1.25), real_t(1.5), real_t(1.75), real_t(2),
      real_t(2.25), real_t(2.5), real_t(2.75), real_t(3), real_t(3.5),
      real_t(4), real_t(4.5), real_t(5), real_t(5.5), real_t(6),
      real_t(6.5), real_t(7), real_t(7.5), real_t(8), real_t(8.5),
      real_t(9), real_t(9.5), real_t(10)};
  return v;
}

/// The row in the PSTAR and ASTAR tables for a material named @p name, or -1.
///
/// Host only, and called once per material when the material is built: an exact
/// string match against 74 names, which is the first half of
/// G4PSTARStopping::Initialise.
inline int nist_stopping_index(const char* name) {
  if (name == nullptr) { return -1; }
  for (int i = 0; i < kNistStoppingMaterials; ++i) {
    if (std::strcmp(name, kNistStoppingNames[i]) == 0) { return i; }
  }
  return -1;
}

/// Chemical formulae G4PSTARStopping recognises when a material's *name* is not one
/// of the 74, and the NIST row each resolves to.
///
/// This is the second half of G4PSTARStopping::Initialise, and it matters more than
/// it looks. G4BraggModel has its own eleven-compound list with its own ICRU 49
/// parameterisation for exactly these formulae, and that branch is unreachable - in
/// Geant4 as much as here - because this list is a superset of it and resolves first,
/// to a table. A material called "MyWater" with the formula "H_2O" gets G4_WATER's
/// tabulated stopping power, not a fit. Measured: tests/test_bragg.cu builds exactly
/// that material and the oracle dumps Geant4's answer for it.
constexpr int kNistFormulae = 12;
constexpr const char* const kNistFormulaNames[12] = {
    "Al_2O_3",
    "CO_2",
    "CH_4",
    "(C_2H_4)_N-Polyethylene",
    "(C_2H_4)_N-Polypropylene",
    "(C_8H_8)_N",
    "C_3H_8",
    "SiO_2",
    "CsI",
    "H_2O",
    "H_2O-Gas",
    "Graphite",
};
constexpr int kNistFormulaRow[12] = {6, 16, 36, 52, 55, 54, 56, 62, 21, 71, 72, 13};

/// The NIST row a chemical formula resolves to, or -1. Host only.
inline int nist_stopping_index_by_formula(const char* formula) {
  if (formula == nullptr || formula[0] == 0) { return -1; }
  for (int i = 0; i < kNistFormulae; ++i) {
    if (std::strcmp(formula, kNistFormulaNames[i]) == 0) { return kNistFormulaRow[i]; }
  }
  return -1;
}

}  // namespace g4gpu::data
