// The per-isotope low-energy parameters of G4ChipsNeutronElasticXS::GetPTables (11.1.1).
//
// GENERATED by tools/extract_chips_neutron.pl - do not edit by hand. The script asserts the
// counts it read (422 isotope rows, 99 per-Z lists, each list's length equal to Geant4's own
// N<z>) and refuses to emit anything if one of them is off, because a table that is quietly
// short here reads as a physics disagreement later.
//
// Geant4 stores these as 422 `pZ<z>N<n>[7]` arrays wrapped in `std::pair<G4int,const G4double*>`
// and gathered into 99 per-Z arrays. GetPTables walks the array for tgZ in order and takes the
// FIRST entry whose first element equals tgN; the order is therefore part of the answer and is
// preserved here. Entries whose pair name disagrees with their neutron number (Geant4 has
// `Z3N1(3,pZ3N3)`) carry the number, not the name.
//
// The seven numbers become lastPAR[4], [7], [8], [9], [10], [11], [12] - the low-energy part of
// the nA elastic cross section. An isotope that is not in the list gets Geant4's default row
// {5.2e-7, 22., 0.00026, 1.3e-9, 2.7, 4.e-5, 0.005}, which is in the port beside this table.
//
// Z=0 and the Z=1 N=0 row are Geant4's own "not used (fake)" placeholders: the model treats a
// free proton or neutron target through the pp/np parameterisations before it ever indexes this
// table. They are kept so that the indices line up with Geant4's.
#pragma once

namespace g4gpu::physics::hadronic::chips_data {

/// One isotope row: the neutron number Geant4 matches on, then its seven parameters.
struct NeutronLowERow {
  int n;
  double p[7];
};

constexpr int kNeutronLowENZ = 99;

// The tables are reached through accessor functions returning a pointer to a function-local
// static, which is this port's idiom for a constant table (see data/barashenkov.hh): a
// `constexpr` array at namespace scope is not addressable from device code under nvcc, and the
// same header has to compile for the host tests and for a kernel.
/// Z = 0, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z0() {
  static const NeutronLowERow v[1] = {
    {  1, {0., 0., 0., 0., 0., 0., 0.}},
  };
  return v;
}
/// Z = 1, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z1() {
  static const NeutronLowERow v[3] = {
    {  0, {0., 0., 0., 0., 0., 0., 0.}},
    {  1, {6.E-5, 4., .055, 1.1E-8, .008, 1.2E-8, .019}},
    {  2, {6.E-5, 2.2, .051, 1.E-8, .04, 9.E-8, .0075}},
  };
  return v;
}
/// Z = 2, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z2() {
  static const NeutronLowERow v[2] = {
    {  1, {6.E-5, 3., .06, 4.E-9, .03, 7.E-8, .015}},
    {  2, {3.E-4, .23, 1., 1.5E-9, 2.E-02, 1.E-8, .003}},
  };
  return v;
}
/// Z = 3, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z3() {
  static const NeutronLowERow v[2] = {
    {  3, {3.1E-7, 1.7, 1.3E-4, 1.E-8, .02, 1.1E-7, .0023}},
    {  4, {1.3E-6, 1.8, 7.6E-4, 9.E-9, .03, 1.E-7, .0029}},
  };
  return v;
}
/// Z = 4, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z4() {
  static const NeutronLowERow v[2] = {
    {  3, {2.E-4, 1.4, 2.7, 0., .02, 5.E-8, 0.}},
    {  5, {1.E-6, 5.7, .0011, 3.E-9, .007, 2.E-8, .016}},
  };
  return v;
}
/// Z = 5, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z5() {
  static const NeutronLowERow v[2] = {
    {  5, {8.E-7, 5., 3.4E-4, 7.E-9, 1.E-02, 1.E-07, .0053}},
    {  6, {4.8E-6, 6.6, .0035, 4.E-9, .003, 1.E-8, .012}},
  };
  return v;
}
/// Z = 6, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z6() {
  static const NeutronLowERow v[2] = {
    {  6, {4.9E-6, 6.6, .0035, 4.E-9, .002, 6.E-9, .011}},
    {  7, {4.9E-6, 6.6, .0035, 4.E-9, .002, 6.E-9, .011}},
  };
  return v;
}
/// Z = 7, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z7() {
  static const NeutronLowERow v[2] = {
    {  7, {4.9E-6, 1.6, .03, .4E-9, .02, 6.E-8, .021}},
    {  8, {2.5E-6, 5., .0021, 2.5E-9, .015, 5.E-8, .009}},
  };
  return v;
}
/// Z = 8, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z8() {
  static const NeutronLowERow v[3] = {
    {  8, {2.5E-6, 5.3, .0018, 3.E-9, .01, 1.5E-8, .0075}},
    {  9, {1.4E-6, 2.1, .0025, 1.3E-9, .02, 1.3E-7, .0072}},
    { 10, {1.4E-6, 2.1, .0025, 1.3E-9, .02, 1.3E-7, .0072}},
  };
  return v;
}
/// Z = 9, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z9() {
  static const NeutronLowERow v[1] = {
    { 10, {1.4E-6, 7.5, 6.7E-4, 4.E-9, 2.E-5, 7.E-12, .0066}},
  };
  return v;
}
/// Z = 10, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z10() {
  static const NeutronLowERow v[3] = {
    { 10, {1.4E-5, 7., .01, 0., 3.E-11, 7.E-24, .12}},
    { 11, {1.4E-6, 7.5, 6.7E-4, 4.E-9, 2.E-5, 7.E-12, .0066}},
    { 12, {1.4E-5, 7., .01, 0., 3.E-11, 7.E-24, .12}},
  };
  return v;
}
/// Z = 11, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z11() {
  static const NeutronLowERow v[2] = {
    { 11, {1.4E-5, 7., .01, 0., 3.E-11, 7.E-24, .12}},
    { 12, {1.4E-6, 7.6, 6.E-4, 5.E-9, 7.E-9, 3.E-18, .0056}},
  };
  return v;
}
/// Z = 12, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z12() {
  static const NeutronLowERow v[3] = {
    { 12, {8.E-7, 3., .001, 1.8E-9, .0015, .2E-9, .006}},
    { 13, {8.E-7, 7., 3.E-4, 6.E-9, .006, 4.E-8, .0042}},
    { 14, {1.2E-6, 6.8, 5.E-4, 5.E-9, .007, 2.E-8, .0044}},
  };
  return v;
}
/// Z = 13, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z13() {
  static const NeutronLowERow v[1] = {
    { 14, {3.E-7, 5., 8.4E-5, 7.E-9, .008, 2.E-8, .0022}},
  };
  return v;
}
/// Z = 14, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z14() {
  static const NeutronLowERow v[3] = {
    { 14, {1.2E-6, 6., 4.E-4, 6.E-9, .012, 8.E-8, .0029}},
    { 15, {2.4E-6, 4., .0016, 3.E-9, .018, 6.E-8, .0037}},
    { 16, {6.E-7, 4., 3.7E-4, 3.E-9, .018, 6.E-8, .0036}},
  };
  return v;
}
/// Z = 15, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z15() {
  static const NeutronLowERow v[1] = {
    { 16, {6.E-7, 3., 8.2E-4, 1.4E-9, .03, 8.E-8, .0059}},
  };
  return v;
}
/// Z = 16, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z16() {
  static const NeutronLowERow v[4] = {
    { 16, {6.E-7, 3., 1.9E-4, 5.E-9, .03, 6.E-8, .0013}},
    { 17, {2.4E-6, 3., .0023, 2.E-9, .03, 6.5E-8, .004}},
    { 18, {2.4E-6, 1.6, .0031, 1.4E-9, .03, 4.E-08, .0028}},
    { 20, {2.4E-6, 3.1, .0017, 2.5E-9, .03, 5.E-08, .0029}},
  };
  return v;
}
/// Z = 17, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z17() {
  static const NeutronLowERow v[2] = {
    { 18, {1.2E-7, .04, .062, 3.E-12, 3.E-02, 3.E-08, .027}},
    { 20, {1.2E-7, 2., 6.8E-5, 2.7E-9, .03, 4.E-8, .0015}},
  };
  return v;
}
/// Z = 18, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z18() {
  static const NeutronLowERow v[3] = {
    { 18, {1.2E-7, .52, .017, 1.1E-11, .03, 3.E-8, .095}},
    { 20, {1.2E-07, .09, .012, 1.8E-11, .03, 3.E-8, .011}},
    { 22, {1.2E-7, .65, 1.2E-4, 1.5E-9, .03, 5.E-8, 8.E-4}},
  };
  return v;
}
/// Z = 19, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z19() {
  static const NeutronLowERow v[3] = {
    { 20, {1.2E-7, 1.3, 1.9E-4, .9E-9, .04, 5.5E-8, .0026}},
    { 21, {1.6E-7, 1.2, 3.7E-4, .8E-9, .04, 6.5E-8, .0034}},
    { 22, {6.E-8, 1.3, 1.2E-4, .9E-9, .04, 6.E-8, .0031}},
  };
  return v;
}
/// Z = 20, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z20() {
  static const NeutronLowERow v[6] = {
    { 20, {2.4E-7, 3.4, 2.1E-4, 1.5E-9, .035, 6.E-8, .0037}},
    { 22, {6.E-8, 2.7, 2.7E-5, 3.E-9, .035, 6.E-8, .0014}},
    { 23, {1.5E-8, 1.8, 3.4E-5, .6E-9, .04, 6.E-8, .0049}},
    { 24, {3.E-6, 5., .002, 2.E-9, .03, 7.E-8, .0038}},
    { 26, {1.7E-5, 18., .0027, 1.E-8, 2.E-7, 7.E-17, .0047}},
    { 28, {7.6E-6, .4, .07, .13E-9, .05, 4.E-8, .0042}},
  };
  return v;
}
/// Z = 21, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z21() {
  static const NeutronLowERow v[1] = {
    { 24, {3.6E-9, 1.5, 5.2E-5, .1E-9, .05, 1.E-7, .025}},
  };
  return v;
}
/// Z = 22, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z22() {
  static const NeutronLowERow v[5] = {
    { 24, {2.8E-8, 1.8, 5.6E-5, .6E-9, .05, 8.E-8, .0042}},
    { 25, {3.1E-9, 1.6, 6.E-6, .8E-9, .04, 8.E-8, .0036}},
    { 26, {3.E-9, 4., 3.2E-6, 1.4E-9, .05, 2.E-7, .0048}},
    { 27, {1.E-8, 2., 3.4E-6, 4.5E-9, .05, 8.E-8, 7.7E-4}},
    { 28, {4.E-7, 4., 3.7E-4, 1.E-09, .05, 1.E-7, .0041}},
  };
  return v;
}
/// Z = 23, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z23() {
  static const NeutronLowERow v[2] = {
    { 27, {.3E-9, 2., 8.E-7, .55E-9, .07, 1.7E-7, .0055}},
    { 28, {.3E-9, 2., 8.E-7, .55E-9, .07, 1.7E-7, .0055}},
  };
  return v;
}
/// Z = 24, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z24() {
  static const NeutronLowERow v[4] = {
    { 26, {1.2E-9, 2.8, 1.E-6, 1.7E-9, .07, 1.7E-7, .0026}},
    { 28, {4.4E-6, 11., .0012, 5.E-9, .04, 3.E-7, .0032}},
    { 29, {1.8E-9, 2.4, 6.3E-6, .5E-9, .07, 2.E-7, .0085}},
    { 30, {4.8E-8, 2.8, 4.4E-5, 1.4E-9, .07, 2.E-7, .0027}},
  };
  return v;
}
/// Z = 25, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z25() {
  static const NeutronLowERow v[1] = {
    { 30, {6.5E-11, 1.4, 1.E-7, .8E-9, .07, 1.7E-7, .0022}},
  };
  return v;
}
/// Z = 26, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z26() {
  static const NeutronLowERow v[4] = {
    { 28, {3.9E-8, 5., 1.7E-5, 3.E-9, .07, 3.E-7, .0023}},
    { 30, {5.E-9, .4, 1.5E-4, 4.E-11, .1, 3.E-7, .012}},
    { 31, {.5E-9, .5, 2.6E-6, .3E-9, .11, 5.E-7, .0027}},
    { 32, {1.E-7, 3.1, 1.E-4, 1.3E-9, .11, 5.E-7, .0031}},
  };
  return v;
}
/// Z = 27, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z27() {
  static const NeutronLowERow v[2] = {
    { 32, {4.E-7, 5., 5.E-4, 1.2E-9, .13, 6.E-7, .006}},
    { 31, {4.E-7, 3., .004, 0., .11, 4.5E-7, .07}},
  };
  return v;
}
/// Z = 28, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z28() {
  static const NeutronLowERow v[6] = {
    { 30, {1.E-7, 2.5, .001, .14E-9, .13, 6.E-7, .025}},
    { 31, {1.E-7, 19., 1.2E-5, 1.E-8, 4.E-12, 3.E-22, .0024}},
    { 32, {1.E-8, 2.5, 3.9E-6, 3.5E-9, .13, 6.E-7, .001}},
    { 33, {5.E-9, 2.6, 1.5E-5, .42E-9, .13, 7.E-7, .008}},
    { 34, {.24E-9, 2., 1.2E-6, .25E-9, .13, 6.E-7, .0094}},
    { 36, {1.E-8, 3., 5.5E-8, 2.8E-7, .12, 6.E-7, 1.6E-5}},
  };
  return v;
}
/// Z = 29, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z29() {
  static const NeutronLowERow v[2] = {
    { 34, {1.1E-7, 3.5, 1.6E-4, .9E-9, .13, 7.E-7, .005}},
    { 36, {1.1E-7, 3.5, 4.3E-4, .3E-9, .13, 7.E-7, .013}},
  };
  return v;
}
/// Z = 30, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z30() {
  static const NeutronLowERow v[5] = {
    { 34, {1.1E-7, 4., 1.2E-4, 1.2E-9, .17, 7.E-7, .004}},
    { 36, {1.1E-7, 4., 1.2E-4, 1.2E-9, .17, 7.E-7, .004}},
    { 37, {1.1E-7, 4., 1.2E-4, 1.2E-9, .17, 7.E-7, .004}},
    { 38, {1.1E-7, 4., 1.2E-4, 1.2E-9, .17, 7.E-7, .004}},
    { 40, {1.1E-7, 4., 1.2E-4, 1.2E-9, .17, 7.E-7, .004}},
  };
  return v;
}
/// Z = 31, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z31() {
  static const NeutronLowERow v[2] = {
    { 38, {5.E-8, 3.7, 1.1E-4, .55E-9, .17, 8.4E-7, .0076}},
    { 40, {1.E-8, 3.1, 1.7E-5, .7E-9, .17, 9.E-7, .0048}},
  };
  return v;
}
/// Z = 32, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z32() {
  static const NeutronLowERow v[5] = {
    { 38, {5.E-5, 4., .17, .35E-9, .17, 9.E-7, .013}},
    { 40, {5.E-7, 4.4, .001, .6E-9, .17, 9.E-7, .008}},
    { 41, {5.E-9, 3., 8.E-6, .7E-9, .17, 1.E-6, .0043}},
    { 42, {1.E-7, 4.2, 1.7E-4, .7E-9, .17, 1.E-6, .0065}},
    { 44, {1.E-6, 4.6, .0018, .6E-9, .17, 1.E-6, .0073}},
  };
  return v;
}
/// Z = 33, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z33() {
  static const NeutronLowERow v[2] = {
    { 41, {1.E-8, 3.4, 1.5E-5, .72E-9, .17, 1.E-6, .0045}},
    { 42, {1.E-8, 4.1, 1.3E-5, .75E-9, .2, 1.2E-6, .0048}},
  };
  return v;
}
/// Z = 34, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z34() {
  static const NeutronLowERow v[7] = {
    { 40, {6.E-8, 7.2, 6.E-5, 1.E-9, .32, 2.E-6, .0063}},
    { 42, {4.E-5, 7.4, .1, .43E-9, .34, 2.1E-6, .016}},
    { 43, {1.E-7, 6.2, 1.4E-4, .9E-9, .34, 2.1E-6, .0075}},
    { 44, {1.E-7, 6.6, 1.3E-4, .9E-9, .34, 2.1E-6, .0075}},
    { 45, {5.E-8, 6.6, 4.8E-5, 1.2E-9, .4, 2.6E-6, .0055}},
    { 46, {2.E-7, 7.7, 1.3E-4, 1.7E-9, .34, 2.1E-6, .0043}},
    { 48, {2.E-7, 8.3, 1.2E-4, 1.7E-9, .34, 2.1E-6, .0043}},
  };
  return v;
}
/// Z = 35, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z35() {
  static const NeutronLowERow v[2] = {
    { 44, {5.E-8, 6., 2.8E-5, 2.E-9, .34, 2.1E-6, .0028}},
    { 46, {4.E-8, 6.2, 3.7E-5, 1.1E-9, .34, 2.1E-6, .0049}},
  };
  return v;
}
/// Z = 36, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z36() {
  static const NeutronLowERow v[7] = {
    { 42, {1.6E-7, 6.8, 2.E-4, .8E-9, .35, 2.1E-6, .0076}},
    { 44, {1.6E-7, 7.3, 1.6E-4, 1.E-9, .35, 2.1E-6, .0062}},
    { 46, {1.6E-7, 7.3, 3.3E-4, .7E-9, .35, 2.1E-6, .013}},
    { 47, {1.6E-6, 7.3, .003, .6E-9, .35, 2.1E-6, .011}},
    { 48, {1.6E-7, 7.8, 7.6E-5, 2.E-9, .35, 2.1E-6, .0031}},
    { 49, {6.E-7, 8., 4.8E-4, 1.4E-9, .27, 2.1E-6, .0053}},
    { 50, {4.E-7, 8.1, 2.7E-4, 1.6E-9, .35, 2.1E-6, .0045}},
  };
  return v;
}
/// Z = 37, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z37() {
  static const NeutronLowERow v[3] = {
    { 48, {1.6E-7, 7.2, 1.4E-4, 1.2E-9, .35, 2.1E-6, .0052}},
    { 49, {8.E-8, 7.1, 4.7E-5, 1.6E-9, .27, 2.1E-6, .0034}},
    { 50, {1.E-7, 8., 5.5E-5, 1.9E-9, .27, 1.5E-6, .0036}},
  };
  return v;
}
/// Z = 38, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z38() {
  static const NeutronLowERow v[6] = {
    { 46, {8.E-8, 7.3, 6.E-5, 1.3E-9, .27, 2.E-6, .0045}},
    { 48, {8.E-8, 9.7, 2.3E-5, 3.5E-9, .4, 2.7E-6, .0023}},
    { 49, {2.6E-7, 9.5, 1.9E-4, 1.5E-9, .4, 2.7E-6, .0057}},
    { 50, {2.6E-7, 9.5, 2.E-4, 1.4E-9, .37, 3.2E-6, .0059}},
    { 51, {1.3E-7, 9.9, 7.5E-5, 1.7E-9, .37, 3.2E-6, .0046}},
    { 52, {2.6E-7, 9.6, 1.6E-4, 1.8E-9, .37, 2.7E06, .0047}},
  };
  return v;
}
/// Z = 39, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z39() {
  static const NeutronLowERow v[3] = {
    { 50, {2.6E-7, 9.9, 2.E-4, 1.1E-9, .37, 3.2E-6, .0062}},
    { 51, {2.7E-5, 20., .013, 2.2E-9, .37, 1.9E-6, .0078}},
    { 52, {2.E-7, 9.6, 1.2E-4, 1.7E-9, .37, 3.E-6, .0046}},
  };
  return v;
}
/// Z = 40, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z40() {
  static const NeutronLowERow v[7] = {
    { 50, {1.E-7, 9., 6.2E-5, 1.7E-9, .3, 3.E-6, .0044}},
    { 51, {5.E-7, 9.8, 5.E-4, 1.E-9, .25, 2.1E-6, .0079}},
    { 52, {3.E-7, 9.6, 2.2E-4, 1.2E-9, .25, 2.2E-6, .0056}},
    { 53, {2.E-7, 9.6, 1.2E-4, 1.6E-9, .38, 2.9E-6, .0046}},
    { 54, {2.E-7, 9.6, 1.8E-4, 1.1E-9, .25, 2.1E-6, .0067}},
    { 55, {1.8E-7, 9.4, 1.1E-4, 1.6E-9, .33, 2.3E-6, .0045}},
    { 56, {1.8E-7, 9.4, 1.1E-4, 1.6E-9, .2, 1.5E-6, .0045}},
  };
  return v;
}
/// Z = 41, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z41() {
  static const NeutronLowERow v[3] = {
    { 52, {2.6E-7, 8.3, 2.E-4, 1.2E-9, .4, 4.E-6, .0051}},
    { 52, {2.6E-7, 8.3, 2.E-4, 1.2E-9, .4, 4.E-6, .0051}},
    { 52, {2.6E-7, 8.3, 2.E-4, 1.2E-9, .4, 4.E-6, .0051}},
  };
  return v;
}
/// Z = 42, 8 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z42() {
  static const NeutronLowERow v[8] = {
    { 50, {2.E-7, 10., 1.1E-4, 1.8E-9, .3, 2.7E-6, .0044}},
    { 52, {2.1E-7, 10., 1.2E-4, 1.7E-9, .3, 2.8E-6, .0046}},
    { 53, {3.E-7, 10., 1.9E-4, 1.5E-9, .29, 3.E-6, .005}},
    { 54, {1.5E-7, 10., 7.1E-5, 2.1E-9, .29, 2.9E-6, .0037}},
    { 55, {1.9E-7, 9., 1.4E-4, 1.3E-9, .29, 2.8E-6, .0052}},
    { 56, {1.9E-7, 9.9, 1.1E-4, 1.8E-9, .29, 2.4E-6, .0044}},
    { 57, {1.4E-7, 8., 1.E-4, 1.4E-9, .34, 2.5E-6, .0044}},
    { 58, {1.8E-7, 9.5, 1.E-4, 1.7E-9, .27, 2.2E-6, .0041}},
  };
  return v;
}
/// Z = 43, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z43() {
  static const NeutronLowERow v[1] = {
    { 56, {1.E-7, 8., 7.2E-5, 1.4E-9, .24, 2.5E-6, .0044}},
  };
  return v;
}
/// Z = 44, 9 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z44() {
  static const NeutronLowERow v[9] = {
    { 52, {1.9E-7, 10., 1.E-4, 2.1E-9, .4, 4.E-6, .004}},
    { 54, {1.5E-7, 10., 7.7E-5, 2.1E-9, .29, 2.9E-6, .004}},
    { 55, {1.8E-7, 10., 6.6E-5, 2.6E-9, .47, 4.6E-6, .0028}},
    { 56, {1.8E-6, 10., .0017, 1.1E-9, .47, 6.E-6, .0073}},
    { 57, {1.8E-7, 7.8, 1.3E-4, 1.4E-9, .42, 5.E-6, .0043}},
    { 58, {1.7E-6, 9.8, .0015, 1.2E-9, .32, 4.E-6, .0065}},
    { 59, {3.3E-7, 8.7, 1.9E-4, 1.6E-9, .32, 3.8E-6, .0038}},
    { 60, {3.E-7, 8.7, 1.8E-4, 1.6E-9, .3, 3.2E-6, .004}},
    { 61, {3.E-7, 8.8, 1.4E-4, 1.9E-9, .3, 3.2E-6, .003}},
  };
  return v;
}
/// Z = 45, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z45() {
  static const NeutronLowERow v[2] = {
    { 58, {8.E-8, 8.7, 4.E-5, 1.8E-9, .29, 2.9E-6, .0033}},
    { 60, {8.E-8, 8.7, .09, 1.3E-12, .29, 2.9E-6, 7.}},
  };
  return v;
}
/// Z = 46, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z46() {
  static const NeutronLowERow v[7] = {
    { 56, {2.E-7, 9.9, 1.2E-4, 1.5E-9, .35, 3.3E-6, .0045}},
    { 58, {2.E-7, 9.9, 9.5E-5, 1.8E-9, .4, 4.E-6, .0036}},
    { 59, {5.6E-7, 9., 4.6E-4, 1.2E-9, .5, 4.8E-6, .0056}},
    { 60, {2.4E-7, 9.2, 1.2E-4, 1.8E-9, .47, 4.6E-6, .0035}},
    { 61, {1.2E-7, 9.2, 4.4E-5, 2.8E-9, .5, 4.3E-6, .0025}},
    { 62, {1.2E-7, 9.2, 3.2E-5, 3.4E-9, .48, 4.5E-6, .0018}},
    { 64, {4.E-7, 9.1, 2.5E-4, 1.5E-9, .48, 4.7E-6, .0042}},
  };
  return v;
}
/// Z = 47, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z47() {
  static const NeutronLowERow v[4] = {
    { 60, {1.4E-6, 9.7, .0011, 1.4E-9, .55, 5.E-6, .0056}},
    { 62, {3.E-8, 8.7, 8.5E-6, 3.5E-9, .6, 5.6E-6, .0018}},
    { 63, {3.E-6, 9.5, .002, 1.5E-9, .58, 5.E-6, .0047}},
    { 64, {1.5E-7, 9., 9.E-5, 1.7E-9, .58, 5.6E-6, .0039}},
  };
  return v;
}
/// Z = 48, 9 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z48() {
  static const NeutronLowERow v[9] = {
    { 58, {2.9E-7, 10., 1.3E-4, 1.9E-9, .4, 3.8E-6, .0034}},
    { 60, {2.3E-7, 10., 8.2E-5, 2.5E-9, .5, 4.7E-6, .0026}},
    { 62, {2.3E-7, 10., 9.9E-5, 2.5E-9, .5, 4.7E-6, .0031}},
    { 63, {8.4E-7, 11., 4.3E-4, 1.8E-9, .5, 4.5E-6, .0042}},
    { 64, {4.E-7, 11., 1.8E-4, 1.8E-9, .5, 4.6E-6, .0036}},
    { 65, {1.6E-6, 12., .001, 0., .5, 4.6E-6, .013}},
    { 66, {3.E-7, 11., 1.2E-4, 1.9E-9, .5, 4.6E-6, .0031}},
    { 67, {3.8E-7, 11., 1.7E-4, 2.E-9, .6, 6.6E-6, .0035}},
    { 68, {6.E-7, 11., 3.3E-4, 1.9E-9, .5, 4.6E-6, .0043}},
  };
  return v;
}
/// Z = 49, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z49() {
  static const NeutronLowERow v[2] = {
    { 64, {2.7E-7, 12., 8.1E-5, 2.7E-9, .5, 5.E-6, .0026}},
    { 66, {2.7E-7, 12., 5.5E-5, 4.E-9, .5, 5.E-6, .0018}},
  };
  return v;
}
/// Z = 50, 14 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z50() {
  static const NeutronLowERow v[14] = {
    { 62, {4.E-7, 11., 1.6E-4, 2.2E-9, .5, 4.5E-6, .0032}},
    { 63, {4.1E-7, 11., 1.6E-4, 2.4E-9, .54, 6.E-6, .0031}},
    { 64, {5.E-7, 12., 1.9E-4, 2.2E-9, .5, 4.4E-6, .0032}},
    { 65, {1.E-5, 12., .0077, 1.4E-9, .5, 5.E-6, .0066}},
    { 66, {5.E-7, 12., 1.8E-4, 2.4E-9, .5, 5.E-6, .0031}},
    { 67, {1.E-6, 12., 4.4E-4, 1.8E-9, .5, 5.E-6, .0037}},
    { 68, {5.E-7, 12., 2.E-4, 2.4E-9, .5, 5.E-6, .0033}},
    { 69, {6.E-7, 12., 2.5E-4, 2.E-9, .5, 5.E-6, .0035}},
    { 70, {1.E-6, 12., 4.7E-4, 2.E-9, .5, 5.E-6, .0039}},
    { 72, {1.E-6, 12., 3.7E-4, 2.2E-9, .5, 5.E-6, .0031}},
    { 73, {5.E-7, 12., 1.7E-4, 2.8E-9, .5, 5.E-6, .0028}},
    { 74, {5.E-7, 12., 2.E-4, 2.E-9, .5, 5.E-6, .0033}},
    { 75, {5.E-7, 12., 1.9E-4, 2.8E-9, .5, 5.E-6, .003}},
    { 76, {5.E-7, 12., 1.7E-4, 2.8E-9, .5, 5.E-6, .0028}},
  };
  return v;
}
/// Z = 51, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z51() {
  static const NeutronLowERow v[5] = {
    { 70, {6.E-7, 12., 2.E-4, 2.8E-9, .5, 5.E-6, .0028}},
    { 72, {6.E-7, 12., 1.9E-4, 3.E-9, .5, 5.E-6, .0025}},
    { 73, {1.1E-6, 12., 3.5E-4, 2.9E-9, .5, 5.E-6, .0026}},
    { 74, {5.5E-7, 12., 1.9E-4, 2.9E-9, .5, 5.E-6, .0027}},
    { 75, {6.E-7, 12., 2.E-4, 2.9E-9, .5, 5.E-6, .0027}},
  };
  return v;
}
/// Z = 52, 11 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z52() {
  static const NeutronLowERow v[11] = {
    { 68, {2.7E-7, 12., 8.4E-5, 3.2E-9, 1., 8.E-6, .0026}},
    { 70, {2.7E-7, 12., 3.8E-5, 6.E-9, 1., 8.E-6, .0012}},
    { 71, {2.7E-8, 12., 1.8E-6, 2.E-8, 1., 8.E-6, 4.8E-4}},
    { 72, {2.6E-6, 14., .0014, 2.E-9, 1., 9.E-6, .005}},
    { 73, {1.E-6, 14., 2.4E-4, 3.9E-9, 1., 9.E-6, .0022}},
    { 74, {8.E-7, 14., 2.3E-4, 3.6E-9, 1.4, 1.3E-5, .0028}},
    { 75, {8.E-7, 14., 2.1E-4, 3.6E-9, 1.4, 1.3E-5, .0025}},
    { 76, {8.E-7, 14., 2.5E-4, 3.E-9, 1.4, 1.3E-5, .003}},
    { 77, {5.E-7, 15., 1.2E-4, 4.3E-9, 1.4, 1.4E-5, .0023}},
    { 78, {8.E-7, 14., 2.7E-4, 2.7E-9, 1.4, 1.3E-5, .0031}},
    { 80, {4.7E-7, 14., 1.8E-4, 2.2E-9, .83, 1.E-5, .0036}},
  };
  return v;
}
/// Z = 53, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z53() {
  static const NeutronLowERow v[5] = {
    { 74, {9.4E-7, 14., 2.5E-4, 3.E-9, .7, 7.3E-6, .0025}},
    { 76, {2.1E-5, 14., .015, 1.1E-9, 1.1, 1.E-5, .007}},
    { 77, {1.1E-6, 14., 2.4E-4, 3.3E-9, .9, 1.E-5, .0021}},
    { 78, {5.5E-7, 14., 1.5E-4, 3.7E-9, 1.2, 1.2E-5, .0024}},
    { 82, {3.2E-6, 14., .0017, 1.8E-9, .8, 8.E-6, .0024}},
  };
  return v;
}
/// Z = 54, 12 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z54() {
  static const NeutronLowERow v[12] = {
    { 69, {3.E-6, 14., 8.E-4, 3.7E-9, .9, 1.1E-5, .15}},
    { 70, {1.5E-7, 14., 1.4E-6, 9.E-8, .7, 8.E-6, 9.5E-5}},
    { 72, {1.5E-6, 14., 5.6E-4, 3.E-9, 1.2, 1.1E-5, .0036}},
    { 74, {1.8E-6, 14., 8.8E-4, 2.E-9, 1.3, 1.2E-5, .0047}},
    { 75, {1.E-6, 14., 2.6E-4, 3.7E-9, 1.5, 1.4E-5, .0024}},
    { 76, {1.8E-6, 14., 8.E-4, 2.E-9, 1.2, 1.4E-5, .0042}},
    { 77, {2.3E-7, 14., 1.9E-5, 9.E-9, 1.2, 1.4E-5, 7.7E-4}},
    { 78, {6.E-7, 14., 1.6E-4, 3.E-9, 1.2, 1.4E-5, .0025}},
    { 79, {6.E-7, 14., 1.6E-4, 3.3E-9, 1.6, 1.5E-5, .0024}},
    { 80, {6.6E-7, 14., 2.1E-4, 2.5E-9, 1.2, 1.4E-5, .003}},
    { 81, {.03, 40., 2.1, 2.5E-9, 1.E-16, 6.E-36, 140.}},
    { 82, {3.1E-6, 14., .0019, 1.6E-9, 1., 1.3E-5, .0054}},
  };
  return v;
}
/// Z = 55, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z55() {
  static const NeutronLowERow v[5] = {
    { 78, {1.4E-6, 14., 4.E-4, 3.E-9, 1.2, 1.4E-5, .0026}},
    { 79, {.028, 14., 44., .5E-9, 1.2, 1.3E-5, .015}},
    { 80, {2.E-6, 14., 9.5E-4, 2.E-9, 1.2, 1.4E-5, .0042}},
    { 81, {2.5E-7, 14., 6.5E-5, 3.8E-9, 1.2, 1.4E-5, .0023}},
    { 82, {2.5E-7, 14., 6.5E-5, 3.8E-9, 1.2, 1.4E-5, .0023}},
  };
  return v;
}
/// Z = 56, 9 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z56() {
  static const NeutronLowERow v[9] = {
    { 74, {4.E-7, 14., 2.8E-5, 1.2E-8, 1.2, 1.5E-5, 6.6E-4}},
    { 76, {4.E-6, 14., .0022, 1.4E-9, 1.3, 1.6E-5, .0053}},
    { 77, {2.E-7, 14., 3.7E-5, 5.E-9, 1.1, 1.5E-5, .0016}},
    { 78, {1.6E-6, 14., 6.E-4, 2.E-9, 1.3, 1.6E-5, .0033}},
    { 79, {5.E-7, 17., 8.E-5, 4.5E-9, 1.3, 1.6E-5, .0018}},
    { 80, {2.E-6, 20., 3.E-4, 6.E-9, 1.3, 1.8E-5, .0019}},
    { 81, {5.8E-6, 20., .0018, 3.E-9, 1.3, 1.7E-5, .0041}},
    { 82, {2.7E-6, 20., 5.5E-4, 4.E-9, 1.4, 2.E-5, .0027}},
    { 84, {1.1E-6, 21., 1.E-4, 9.E-9, 2., 2.7E-5, .0012}},
  };
  return v;
}
/// Z = 57, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z57() {
  static const NeutronLowERow v[3] = {
    { 81, {2.7E-6, 20., .0017, 1.1E-9, 1.4, 2.E-5, .0083}},
    { 82, {5.4E-6, 20., .0027, 1.5E-9, 1., 1.5E-5, .0065}},
    { 83, {2.7E-6, 20., 2.6E-4, 6.E-9, 1.4, 2.E-5, .0012}},
  };
  return v;
}
/// Z = 58, 8 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z58() {
  static const NeutronLowERow v[8] = {
    { 78, {1.8E-6, 20., 3.7E-4, 4.E-9, 1.4, 2.E-5, .0028}},
    { 80, {1.8E-6, 18., 2.6E-4, 6.E-9, 1.3, 2.1E-5, .0017}},
    { 81, {.0018, 18., 2.9, .6E-9, 1.3, 2.E-5, .02}},
    { 82, {1.8E-6, 18., 3.7E-4, 5.E-9, 1.3, 2.E-5, .0024}},
    { 83, {7.2E-6, 20., .0025, 2.3E-9, 1.1, 1.7E-5, .0045}},
    { 84, {1.2E-6, 18., 2.E-4, 6.E-9, 1.5, 1.9E-5, .0018}},
    { 85, {1.2E-6, 16., 6.E-4, 1.7E-9, 1.4, 2.E-5, .0053}},
    { 86, {6.E-7, 18., 1.E-4, 6.E-9, 1.5, 1.9E-5, .0018}},
  };
  return v;
}
/// Z = 59, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z59() {
  static const NeutronLowERow v[3] = {
    { 82, {9.5E-7, 16., 1.6E-4, 4.E-9, 1.4, 2.E-5, .0017}},
    { 83, {9.5E-7, 16., 1.9E-4, 4.E-9, 1.4, 1.9E-5, .0021}},
    { 84, {9.5E-6, 16., .019, .4E-9, 2., 2.4E-5, .021}},
  };
  return v;
}
/// Z = 60, 8 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z60() {
  static const NeutronLowERow v[8] = {
    { 82, {9.6E-6, 21., .0036, 2.3E-9, 1.4, 2.E-5, .0052}},
    { 83, {9.6E-4, 20., 4., .25E-9, 1.4, 2.E-5, .052}},
    { 84, {4.8E-7, 21., 3.3E-5, 1.E-08, 1.3, 2.2E-5, 9.E-4}},
    { 85, {.0048, 20., 4.5, .9E-9, 1.3, 2.E-5, .012}},
    { 86, {1.2E-6, 16., 7.7E-4, 1.5E-9, 1.3, 1.8E-5, .0066}},
    { 87, {.0012, 15., 8.4, .1E-9, 1.3, 1.5E-5, .071}},
    { 88, {1.5E-7, 16., 4.1E-5, 2.5E-9, 1.3, 1.6E-5, .0027}},
    { 90, {1.5E-7, 16., 4.3E-5, 2.5E-9, 1.3, 1.6E-5, .0029}},
  };
  return v;
}
/// Z = 61, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z61() {
  static const NeutronLowERow v[3] = {
    { 86, {6.E-7, 16., 8.E-4, .6E-9, 3., 2.8E-5, .014}},
    { 87, {6.2E-8, 16., 1.2E-5, 4.E-9, 2.2, 2.5E-5, .0019}},
    { 88, {3.2E-8, 16., 6.4E-6, 4.E-9, 2.2, 2.5E-5, .002}},
  };
  return v;
}
/// Z = 62, 9 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z62() {
  static const NeutronLowERow v[9] = {
    { 82, {1.2E-7, 16., 2.1E-5, 5.E-9, 1.4, 2.E-5, .0017}},
    { 85, {1.2E-7, 16., 5.3E-5, 1.5E-9, 1.3, 1.7E-5, .0045}},
    { 86, {6.E-8, 16., 1.7E-5, 3.E-9, 1.3, 1.7E-5, .0028}},
    { 87, {6.E-8, 15., 5.2E-4, .11E-9, 1.3, 1.5E-5, .074}},
    { 88, {6.E-7, 16., 8.6E-4, .7E-9, 1.3, 1.7E-5, .015}},
    { 89, {6.E-7, 16., 5.E-4, 0., 1.3, 1.6E-5, .053}},
    { 90, {6.E-8, 15., 1.3E-5, 4.5E-9, 1.3, 1.7E-5, .0019}},
    { 91, {6.E-8, 15., 1.5E-5, 2.E-9, 1.3, 1.6E-5, .0024}},
    { 92, {1.2E-7, 15., 8.6E-5, 1.2E-9, 1.3, 1.6E-5, .007}},
  };
  return v;
}
/// Z = 63, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z63() {
  static const NeutronLowERow v[7] = {
    { 88, {6.E-8, 15., 2.8E-5, 2.E-9, 1.3, 1.5E-5, .0046}},
    { 89, {6.E-7, 15., .0011, .5E-9, 2.4, 2.4E-5, .017}},
    { 90, {3.E-7, 15., 1.8E-4, 1.1E-9, 1., 1.2E-5, .0054}},
    { 91, {4.1E-7, 15., 1.4E-4, 1.9E-9, 1., 1.4E-5, .0032}},
    { 92, {5.E-8, 15., 2.4E-5, 2.8E-9, 1., 1.3E-5, .0037}},
    { 93, {4.1E-8, 17., 1.6E-5, 2.E-9, 3.3, 3.4E-5, .004}},
    { 94, {4.2E-8, 17., 1.6E-5, 2.E-9, 1.2, 1.6E-5, .004}},
  };
  return v;
}
/// Z = 64, 8 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z64() {
  static const NeutronLowERow v[8] = {
    { 88, {4.2E-8, 14., 2.E-4, 0., 1.2, 1.3E-5, .19}},
    { 89, {2.E-6, 14., .0016, 1.4E-9, 1.6, 1.6E-5, .0057}},
    { 90, {1.7E-7, 12., 8.4E-5, 2.E-9, 1.8, 2.2E-5, .0035}},
    { 91, {1.7E-7, 13., 5.E-4, .3E-9, 1.7, 1.9E-5, .026}},
    { 92, {1.7E-7, 13., 7.E-5, 2.5E-9, 1.8, 2.2E-5, .003}},
    { 93, {1.7E-6, 12., .002, 0., 1.7, 1.8E-5, .47}},
    { 94, {3.4E-7, 13., 1.5E-4, 2.E-9, 1.8, 2.3E-5, .0034}},
    { 96, {2.6E-6, 13., .0019, 1.2E-9, 1., 1.2E-5, .0056}},
  };
  return v;
}
/// Z = 65, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z65() {
  static const NeutronLowERow v[2] = {
    { 94, {9.E-7, 16., 3.9E-4, 1.7E-9, 2., 2.2E-5, .0042}},
    { 94, {9.E-7, 16., 3.9E-4, 1.7E-9, 2., 2.2E-5, .0042}},
  };
  return v;
}
/// Z = 66, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z66() {
  static const NeutronLowERow v[7] = {
    { 90, {1.2E-7, 13., 4.E-5, 3.E-9, 1.2, 1.4E-5, .0025}},
    { 92, {1.2E-7, 13., 6.7E-5, 2.E-9, 1., 1.1E-5, .004}},
    { 94, {1.2E-7, 13., 5.3E-5, 1.6E-9, 1., 1.1E-5, .0034}},
    { 95, {1.2E-6, 13., .0017, .7E-9, 1.3, 1.3E-5, .011}},
    { 96, {1.2E-7, 13., 8.E-6, 1.5E-7, 1., 1.1E-5, 1.E-4}},
    { 97, {1.5E-7, 13., 4.E-5, 4.E-9, 1.3, 1.3E-5, .002}},
    { 98, {3.E-7, 13., .001, 4.E-9, 1.3, 1.3E-5, .23}},
  };
  return v;
}
/// Z = 67, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z67() {
  static const NeutronLowERow v[2] = {
    { 98, {3.E-7, 13., 2.2E-4, 1.5E-9, 1., 1.E-5, .0054}},
    { 99, {7.5E-8, 13., 2.6E-5, 4.5E-9, 1.5, 1.5E-5, .0021}},
  };
  return v;
}
/// Z = 68, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z68() {
  static const NeutronLowERow v[6] = {
    { 94, {1.2E-7, 13., 7.8E-5, 1.6E-9, .9, 9.E-6, .005}},
    { 96, {1.2E-7, 13., 8.5E-5, 1.2E-9, .9, 8.E-6, .0055}},
    { 98, {1.E-6, 13., .0011, .8E-9, .9, 8.E-6, .0087}},
    { 99, {1.2E-7, 13., 2.5E-5, 4.5E-9, .9, 9.E-6, .0015}},
    {100, {2.E-6, 13., .0015, 1.1E-9, .9, 8.E-6, .0058}},
    {102, {2.E-6, 13., .0018, 1.E-9, .9, 8.E-6, .007}},
  };
  return v;
}
/// Z = 69, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z69() {
  static const NeutronLowERow v[1] = {
    {100, {1.2E-7, 13., 2.5E-5, 4.5E-9, .9, 9.E-6, .0015}},
  };
  return v;
}
/// Z = 70, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z70() {
  static const NeutronLowERow v[7] = {
    { 98, {1.E-6, 13., .0011, .8E-9, .9, 8.E-6, .0087}},
    {100, {2.E-6, 13., .0015, 1.1E-9, .9, 8.E-6, .0058}},
    {101, {1.2E-7, 13., 2.5E-5, 4.5E-9, .9, 9.E-6, .0015}},
    {102, {2.E-6, 13., .0018, 1.E-9, .9, 8.E-6, .007}},
    {103, {5.E-7, 18., .01, 1.7E-6, 1.2, 1.4E-5, 1.4E-5}},
    {104, {5.E-7, 18., 1.9E-4, 2.5E-9, 1.2, 1.4E-5, .004}},
    {106, {5.E-7, 18., 1.3E-4, 2.E-9, 1.2, 1.4E-5, .0027}},
  };
  return v;
}
/// Z = 71, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z71() {
  static const NeutronLowERow v[2] = {
    {104, {5.E-7, 18., 1.8E-4, 2.E-9, .9, 9.E-6, .0036}},
    {105, {2.5E-7, 18., 9.E-5, 1.E-8, .9, 9.E-6, .0016}},
  };
  return v;
}
/// Z = 72, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z72() {
  static const NeutronLowERow v[6] = {
    {102, {1.E-6, 18., 8.8E-4, .8E-9, 1., 1.1E-5, .0092}},
    {104, {5.E-7, 18., 1.9E-4, 2.5E-9, 1.2, 1.4E-5, .004}},
    {105, {5.E-7, 18., .01, 1.7E-6, 1.2, 1.4E-5, 1.4E-5}},
    {106, {5.E-7, 18., 1.3E-4, 2.E-9, 1.2, 1.4E-5, .0027}},
    {107, {2.5E-7, 18., 1.E-4, 2.E-9, 1.2, 1.5E-5, .0041}},
    {108, {1.E-6, 18., .0012, .6E-9, 1.2, 1.5E-5, .012}},
  };
  return v;
}
/// Z = 73, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z73() {
  static const NeutronLowERow v[2] = {
    {108, {5.E-7, 18., 1.7E-4, 2.E-9, 1.2, 1.4E-5, .0035}},
    {108, {5.E-7, 18., 1.7E-4, 2.E-9, 1.2, 1.4E-5, .0035}},
  };
  return v;
}
/// Z = 74, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z74() {
  static const NeutronLowERow v[5] = {
    {106, {5.E-7, 18., 1.3E-4, 2.E-9, 1.2, 1.4E-5, .0027}},
    {108, {4.E-6, 14., .0034, .9E-9, 1.3, 1.4E-5, .0067}},
    {109, {1.2E-7, 14., 3.E-5, 3.E-9, 1.3, 1.4E-5, .0019}},
    {110, {1.2E-7, 14., 3.6E-5, 2.E-9, 1.3, 1.3E-5, .0024}},
    {112, {1.2E-7, 14., 3.E-5, 1.3E-7, 1.3, 1.3E-5, 1.4E-4}},
  };
  return v;
}
/// Z = 75, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z75() {
  static const NeutronLowERow v[2] = {
    {110, {1.2E-7, 14., 8.E-5, 1.2E-9, 1.3, 1.5E-5, .005}},
    {112, {1.2E-7, 14., 8.8E-5, 1.1E-9, 1.3, 1.5E-5, .0055}},
  };
  return v;
}
/// Z = 76, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z76() {
  static const NeutronLowERow v[7] = {
    {108, {4.E-6, 14., .0034, .9E-9, 1.3, 1.4E-5, .0067}},
    {110, {1.2E-7, 14., 3.6E-5, 2.E-9, 1.3, 1.3E-5, .0024}},
    {111, {1.2E-7, 14., 8.8E-5, 1.1E-9, 1.3, 1.5E-5, .0055}},
    {112, {1.2E-7, 14., 3.E-5, 1.3E-7, 1.3, 1.3E-5, 1.4E-4}},
    {113, {1.2E-7, 14., 8.8E-5, 1.1E-9, 1.3, 1.5E-5, .0055}},
    {114, {1.2E-7, 14., 3.E-5, 1.3E-7, 1.3, 1.3E-5, 1.4E-4}},
    {116, {1.2E-7, 14., 3.E-5, 1.3E-7, 1.3, 1.3E-5, 1.4E-4}},
  };
  return v;
}
/// Z = 77, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z77() {
  static const NeutronLowERow v[2] = {
    {114, {4.8E-7, 14., 5.2E-4, .7E-9, 1.5, 1.7E-5, .0082}},
    {116, {4.8E-7, 14., 4.5E-4, .8E-9, 1.8, 2.3E-5, .0073}},
  };
  return v;
}
/// Z = 78, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z78() {
  static const NeutronLowERow v[6] = {
    {112, {6.E-8, 19., 3.3E-4, .1E-9, 1.6, 1.8E-5, .06}},
    {114, {6.E-8, 19., 3.3E-4, .1E-9, 1.6, 1.8E-5, .06}},
    {116, {6.E-8, 19., 3.3E-4, .1E-9, 1.6, 1.8E-5, .06}},
    {117, {9.6E-7, 20., .001, .2E-9, 1.6, 2.E-5, .037}},
    {118, {2.4E-7, 20., 1.6E-4, 1.3E-9, 1.6, 1.8E-5, .007}},
    {120, {2.E-6, 19., .0015, .9E-9, 1.6, 1.8E-5, .0078}},
  };
  return v;
}
/// Z = 79, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z79() {
  static const NeutronLowERow v[1] = {
    {118, {2.4E-7, 19., 1.E-4, 1.4E-9, 1.3, 1.7E-5, .0042}},
  };
  return v;
}
/// Z = 80, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z80() {
  static const NeutronLowERow v[7] = {
    {116, {6.E-8, 19., 3.3E-4, .1E-9, 1.6, 1.8E-5, .06}},
    {118, {2.4E-7, 20., 1.6E-4, 1.3E-9, 1.6, 1.8E-5, .007}},
    {119, {9.6E-7, 20., .001, .2E-9, 1.6, 2.E-5, .037}},
    {120, {2.E-6, 19., .0015, .9E-9, 1.6, 1.8E-5, .0078}},
    {121, {1.E-6, 20., 7.E-4, 1.E-9, 1.6, 1.8E-5, .0076}},
    {122, {2.E-6, 18., .0016, .8E-9, 1.6, 1.8E-5, .0078}},
    {124, {2.0E-6, 18., .0032, .4E-9, 1.6, 1.8E-5, .016}},
  };
  return v;
}
/// Z = 81, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z81() {
  static const NeutronLowERow v[2] = {
    {122, {2.4E-7, 19., 1.E-4, 1.4E-9, 1.3, 1.7E-5, .0042}},
    {124, {0., 0., 0., 0., 0., 0., 0.}},
  };
  return v;
}
/// Z = 82, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z82() {
  static const NeutronLowERow v[4] = {
    {122, {4.E-6, 20., .0022, 1.E-9, 1.6, 1.8E-5, .0058}},
    {124, {4.E-6, 20., .0022, 1.E-9, 1.6, 1.8E-5, .0058}},
    {125, {2.E-6, 20., .0011, 1.2E-9, 1.6, 1.8E-5, .0056}},
    {126, {4.E-6, 20., .0023, 1.2E-9, 1.6, 1.8E-5, .0058}},
  };
  return v;
}
/// Z = 83, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z83() {
  static const NeutronLowERow v[1] = {
    {126, {8.E-7, 23., 3.3E-4, 1.8E-9, 1.6, 1.8E-5, .005}},
  };
  return v;
}
/// Z = 84, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z84() {
  static const NeutronLowERow v[1] = {
    {125, {2.E-6, 20., .0011, 1.2E-9, 1.6, 1.8E-5, .0056}},
  };
  return v;
}
/// Z = 85, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z85() {
  static const NeutronLowERow v[1] = {
    {125, {2.E-6, 20., .0011, 1.2E-9, 1.6, 1.8E-5, .0056}},
  };
  return v;
}
/// Z = 86, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z86() {
  static const NeutronLowERow v[1] = {
    {136, {1.E-7, 23., 5.5E-5, 1.2E-9, 1.6, 1.8E-5, .0062}},
  };
  return v;
}
/// Z = 87, 1 isotope.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z87() {
  static const NeutronLowERow v[1] = {
    {136, {2.E-7, 23., 1.1E-4, 1.2E-9, 1.6, 1.8E-5, .0062}},
  };
  return v;
}
/// Z = 88, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z88() {
  static const NeutronLowERow v[4] = {
    {135, {1.E-7, 23., 5.5E-5, 1.2E-9, 1.6, 1.8E-5, .0062}},
    {136, {1.E-7, 23., 5.5E-5, 1.2E-9, 1.6, 1.8E-5, .0062}},
    {137, {1.E-7, 23., 5.5E-5, 1.2E-9, 1.6, 1.8E-5, .0062}},
    {138, {4.E-7, 23., 1.7E-4, 1.5E-9, 1.6, 1.8E-5, .005}},
  };
  return v;
}
/// Z = 89, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z89() {
  static const NeutronLowERow v[3] = {
    {136, {2.E-7, 23., 1.1E-4, 1.2E-9, 1.6, 1.8E-5, .0062}},
    {137, {4.E-7, 23., 2.2E-4, 1.2E-9, 1.6, 1.8E-5, .0062}},
    {138, {1.E-7, 23., 5.5E-5, 1.2E-9, 1.6, 1.8E-5, .0062}},
  };
  return v;
}
/// Z = 90, 7 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z90() {
  static const NeutronLowERow v[7] = {
    {137, {4.E-7, 23., 2.2E-4, 1.2E-9, 1.6, 1.8E-5, .0062}},
    {138, {1.E-6, 23., .0016, .4E-9, 3., 3.E-5, .019}},
    {139, {2.5E-7, 23., 1.1E-4, 1.4E-9, 2.4, 2.7E-5, .0049}},
    {140, {1.2E-7, 23., 3.E-5, 2.E-9, 3., 3.E-5, .003}},
    {142, {4.E-6, 23., .0023, 1.1E-9, 1.8, 2.3E-5, .0064}},
    {143, {9.4E-7, 23., 5.4E-4, 1.1E-9, 3., 3.E-5, .0066}},
    {144, {2.5E-7, 23., 1.4E-4, 1.1E-9, 3., 3.E-5, .0066}},
  };
  return v;
}
/// Z = 91, 3 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z91() {
  static const NeutronLowERow v[3] = {
    {140, {1.E-5, 23., .0052, 1.6E-9, 1.8, 2.3E-5, .0057}},
    {141, {8.E-6, 23., .006, 0., 3.5, 3.5E-5, .021}},
    {142, {8.E-6, 23., .0042, 1.E-9, 2., 2.5E-5, .006}},
  };
  return v;
}
/// Z = 92, 10 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z92() {
  static const NeutronLowERow v[10] = {
    {140, {1.4E-6, 20., 8.E-4, 1.5E-9, 2.5, 2.8E-5, .0055}},
    {141, {5.6E-6, 20., .0033, 1.E-9, 2.5, 2.8E-5, .006}},
    {142, {5.6E-6, 20., .0034, 0., 2.5, 2.8E-5, .0072}},
    {143, {5.6E-6, 20., .0032, 0., 2., 2.3E-5, .006}},
    {144, {3.6E-7, 20., 1.6E-4, 1.3E-9, 2.2, 2.7E-5, .0043}},
    {145, {3.6E-6, 20., .003, 0., 2.2, 2.7E-5, .045}},
    {146, {3.6E-7, 20., 1.6E-4, 1.3E-9, 2.2, 2.7E-5, .0043}},
    {147, {3.6E-6, 20., .0014, 1.3E-9, 2.2, 2.7E-5, 12.}},
    {148, {3.4E-7, 20., 1.3E-4, 1.3E-9, 2.2, 2.8E-5, .0036}},
    {146, {3.6E-7, 20., 1.6E-4, 1.3E-9, 2.2, 2.7E-5, .0043}},
  };
  return v;
}
/// Z = 93, 5 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z93() {
  static const NeutronLowERow v[5] = {
    {142, {3.4E-6, 20., .002, 1.3E-9, 3., 3.3E-5, .0056}},
    {143, {3.4E-6, 20., .002, 1.6E-9, 3.5, 3.6E-5, .005}},
    {144, {6.8E-6, 18., .0052, .8E-9, 2.4, 3.E-5, .0072}},
    {145, {3.4E-6, 20., .002, 1.E-9, 3.5, 3.6E-5, .006}},
    {146, {3.4E-6, 20., .002, 1.5E-9, 3.5, 3.6E-5, .0053}},
  };
  return v;
}
/// Z = 94, 10 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z94() {
  static const NeutronLowERow v[10] = {
    {142, {6.8E-7, 16., 4.5E-4, 1.7E-9, 2.6, 3.E-5, .0047}},
    {143, {6.8E-6, 18., .0044, .9E-9, 3.3, 3.5E-5, .0058}},
    {144, {6.8E-7, 16., 6.E-4, 0., 2.7, 2.6E-5, .0082}},
    {145, {2.6E-6, 16., .0017, 1.8E-9, 1.8, 2.E-5, .004}},
    {146, {2.5E-7, 20., 9.E-5, 3.6E-8, 3.4, 3.8E-5, 5.4E-4}},
    {147, {1.4E-5, 16., .01, .8E-9, 2.7, 2.6E-5, .0055}},
    {148, {3.4E-7, 20., 1.3E-4, 1.2E-9, 3.2, 3.E-5, .0036}},
    {149, {5.2E-6, 20., .0035, .4E-9, 2.3, 3.E-5, .0095}},
    {150, {3.3E-7, 20., 1.6E-4, 1.2E-9, 3., 3.E-5, .0046}},
    {152, {2.5E-6, 16., .0018, 1.2E-9, 3., 3.1E-5, .0052}},
  };
  return v;
}
/// Z = 95, 4 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z95() {
  static const NeutronLowERow v[4] = {
    {156, {2.5E-6, 18., .0016, .9E-9, 2., 2.3E-5, .0058}},
    {157, {5.E-6, 18., .003, 2.7E-9, 2., 2.3E-5, .0039}},
    {158, {5.E-6, 19., .0033, 2.6E-9, 2., 2.3E-5, .0044}},
    {159, {5.E-5, 20., .029, 1.1E-9, 2., 2.3E-5, .0057}},
  };
  return v;
}
/// Z = 96, 10 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z96() {
  static const NeutronLowERow v[10] = {
    {145, {5.E-5, 22., .027, 1.1E-9, 2.2, 2.2E-5, .006}},
    {146, {5.E-5, 24., .027, 2.E-9, 2.2, 2.2E-5, .0055}},
    {147, {5.E-5, 22., .025, 2.5E-9, 2.2, 2.4E-5, .0044}},
    {148, {5.E-5, 23., .028, 1.9E-9, 2.2, 3.E-5, .0055}},
    {149, {5.E-5, 23., .025, 1.6E-9, 3., 3.5E-5, .0054}},
    {150, {5.E-5, 24., .026, 2.E-9, 3., 3.6E-5, .0045}},
    {151, {5.E-5, 24., .022, 2.4E-9, 3., 3.6E-5, .0039}},
    {152, {6.5E-7, 25., 2.E-4, 3.4E-9, 3., 3.6E-5, .003}},
    {153, {1.6E-6, 21., 7.E-4, 1.4E-9, 3., 3.6E-5, .0045}},
    {154, {1.3E-5, 16., .016, 0., 3., 3.6E-5, .017}},
  };
  return v;
}
/// Z = 97, 2 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z97() {
  static const NeutronLowERow v[2] = {
    {152, {6.5E-7, 22., 3.5E-4, 2.7E-9, 3., 4.E-5, .004}},
    {153, {6.5E-6, 22., .0036, 1.E-9, 2.7, 4.E-5, .006}},
  };
  return v;
}
/// Z = 98, 6 isotopes.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_z98() {
  static const NeutronLowERow v[6] = {
    {151, {6.5E-6, 22., .0035, .9E-9, 3., 4.E-5, .0068}},
    {152, {1.3E-6, 22., 7.E-4, 2.E-9, 2.7, 4.E-5, .0045}},
    {153, {2.6E-6, 22., .0014, 2.1E-9, 2.7, 4.E-5, .0044}},
    {154, {2.6E-6, 22., .0014, 1.3E-9, 2.7, 4.E-5, .0054}},
    {155, {2.6E-5, 22., .03, 0., 2.7, 4.E-5, .03}},
    {156, {5.2E-7, 22., 2.6E-4, 1.3E-9, 2.7, 4.E-5, .005}},
  };
  return v;
}

/// Geant4's NIso[ZMAX], Z = 0..98: how many isotope rows each element has.
__host__ __device__ inline const int* neutron_lowe_niso() {
  static const int v[kNeutronLowENZ] = {
    1, 3, 2, 2, 2, 2, 2, 2, 3, 1, 3, 2, 3, 1, 3, 1,
    4, 2, 3, 3, 6, 1, 5, 2, 4, 1, 4, 2, 6, 2, 5, 2,
    5, 2, 7, 2, 7, 3, 6, 3, 7, 3, 8, 1, 9, 2, 7, 4,
    9, 2, 14, 5, 11, 5, 12, 5, 9, 3, 8, 3, 8, 3, 9, 7,
    8, 2, 7, 2, 6, 1, 7, 2, 6, 2, 5, 2, 7, 2, 6, 1,
    7, 2, 4, 1, 1, 1, 1, 1, 4, 3, 7, 3, 10, 5, 10, 4,
    10, 2, 6,
  };
  return v;
}

/// Geant4's Pars[ZMAX][*]: the per-Z row array. Indexing outside 0..98 is the caller's
/// job to refuse - Geant4 would read past the end of its own array.
__host__ __device__ inline const NeutronLowERow* neutron_lowe_pars(int z) {
  switch (z) {
    case 0: return neutron_lowe_z0();
    case 1: return neutron_lowe_z1();
    case 2: return neutron_lowe_z2();
    case 3: return neutron_lowe_z3();
    case 4: return neutron_lowe_z4();
    case 5: return neutron_lowe_z5();
    case 6: return neutron_lowe_z6();
    case 7: return neutron_lowe_z7();
    case 8: return neutron_lowe_z8();
    case 9: return neutron_lowe_z9();
    case 10: return neutron_lowe_z10();
    case 11: return neutron_lowe_z11();
    case 12: return neutron_lowe_z12();
    case 13: return neutron_lowe_z13();
    case 14: return neutron_lowe_z14();
    case 15: return neutron_lowe_z15();
    case 16: return neutron_lowe_z16();
    case 17: return neutron_lowe_z17();
    case 18: return neutron_lowe_z18();
    case 19: return neutron_lowe_z19();
    case 20: return neutron_lowe_z20();
    case 21: return neutron_lowe_z21();
    case 22: return neutron_lowe_z22();
    case 23: return neutron_lowe_z23();
    case 24: return neutron_lowe_z24();
    case 25: return neutron_lowe_z25();
    case 26: return neutron_lowe_z26();
    case 27: return neutron_lowe_z27();
    case 28: return neutron_lowe_z28();
    case 29: return neutron_lowe_z29();
    case 30: return neutron_lowe_z30();
    case 31: return neutron_lowe_z31();
    case 32: return neutron_lowe_z32();
    case 33: return neutron_lowe_z33();
    case 34: return neutron_lowe_z34();
    case 35: return neutron_lowe_z35();
    case 36: return neutron_lowe_z36();
    case 37: return neutron_lowe_z37();
    case 38: return neutron_lowe_z38();
    case 39: return neutron_lowe_z39();
    case 40: return neutron_lowe_z40();
    case 41: return neutron_lowe_z41();
    case 42: return neutron_lowe_z42();
    case 43: return neutron_lowe_z43();
    case 44: return neutron_lowe_z44();
    case 45: return neutron_lowe_z45();
    case 46: return neutron_lowe_z46();
    case 47: return neutron_lowe_z47();
    case 48: return neutron_lowe_z48();
    case 49: return neutron_lowe_z49();
    case 50: return neutron_lowe_z50();
    case 51: return neutron_lowe_z51();
    case 52: return neutron_lowe_z52();
    case 53: return neutron_lowe_z53();
    case 54: return neutron_lowe_z54();
    case 55: return neutron_lowe_z55();
    case 56: return neutron_lowe_z56();
    case 57: return neutron_lowe_z57();
    case 58: return neutron_lowe_z58();
    case 59: return neutron_lowe_z59();
    case 60: return neutron_lowe_z60();
    case 61: return neutron_lowe_z61();
    case 62: return neutron_lowe_z62();
    case 63: return neutron_lowe_z63();
    case 64: return neutron_lowe_z64();
    case 65: return neutron_lowe_z65();
    case 66: return neutron_lowe_z66();
    case 67: return neutron_lowe_z67();
    case 68: return neutron_lowe_z68();
    case 69: return neutron_lowe_z69();
    case 70: return neutron_lowe_z70();
    case 71: return neutron_lowe_z71();
    case 72: return neutron_lowe_z72();
    case 73: return neutron_lowe_z73();
    case 74: return neutron_lowe_z74();
    case 75: return neutron_lowe_z75();
    case 76: return neutron_lowe_z76();
    case 77: return neutron_lowe_z77();
    case 78: return neutron_lowe_z78();
    case 79: return neutron_lowe_z79();
    case 80: return neutron_lowe_z80();
    case 81: return neutron_lowe_z81();
    case 82: return neutron_lowe_z82();
    case 83: return neutron_lowe_z83();
    case 84: return neutron_lowe_z84();
    case 85: return neutron_lowe_z85();
    case 86: return neutron_lowe_z86();
    case 87: return neutron_lowe_z87();
    case 88: return neutron_lowe_z88();
    case 89: return neutron_lowe_z89();
    case 90: return neutron_lowe_z90();
    case 91: return neutron_lowe_z91();
    case 92: return neutron_lowe_z92();
    case 93: return neutron_lowe_z93();
    case 94: return neutron_lowe_z94();
    case 95: return neutron_lowe_z95();
    case 96: return neutron_lowe_z96();
    case 97: return neutron_lowe_z97();
    case 98: return neutron_lowe_z98();
    default: return nullptr;
  }
}

/// Total isotope rows, asserted by the generator against Geant4's own array lengths.
constexpr int kNeutronLowETotalRows = 422;

}  // namespace g4gpu::physics::hadronic::chips_data
